import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import {
  Play,
  Pause,
  RotateCcw,
  SkipForward,
  SkipBack,
  Sliders,
  Sparkles,
  Compass,
  Eye,
  Activity,
  Zap,
  Lightbulb,
  BookOpen,
  Info,
  ChevronRight,
  CheckCircle2,
  XCircle,
  HelpCircle,
  Radio,
  Layers,
  Gauge,
  ArrowRight,
  ArrowDown,
  ArrowUp,
} from 'lucide-react';

// ==========================================
// CONSTANTS & CURRICULUM CONFIGURATIONS
// ==========================================
const DEFAULT_CONFIG = {
  rpm: 30,
  magneticFieldB: 0.6, // Tesla
  coilTurnsN: 50, // Turns
  coilArea: 0.04, // m^2 (0.2m x 0.2m)
  loadResistance: 10, // Ohms
  commutatorType: 'slip_rings', // 'slip_rings' | 'split_ring'
};

const CAMERA_PRESETS = {
  isometric: { yaw: 0.52, pitch: 0.30, label: '3D Isometric' },
  front: { yaw: 0.0, pitch: 0.08, label: 'Front (Commutator)' },
  top: { yaw: 0.0, pitch: 1.50, label: 'Top View' },
  side: { yaw: 1.57, pitch: 0.15, label: 'Side (North Pole)' },
};

// KCSE Practice Problems
const KCSE_PROBLEMS = [
  {
    id: 'kcse_p1',
    title: 'Problem 1: Peak Induced E.M.F. Calculation',
    question:
      'An alternating current dynamo has a rectangular armature coil of 100 turns, each of area 0.05 m², rotating at 1200 RPM in a uniform horizontal magnetic field of flux density 0.40 T. Calculate the maximum (peak) induced electromotive force ε₀ generated by the dynamo in Volts.',
    unit: 'V',
    target: 251.3,
    tolerance: 5.0,
    hint: 'First find angular velocity ω = 2π × (RPM / 60) rad/s. Then compute peak EMF using ε₀ = N × B × A × ω.',
    solutionSteps: [
      'State formula for peak induced EMF: ε₀ = N B A ω',
      'Convert rotation speed from RPM to angular velocity: ω = 2π × (1200 / 60) = 40π ≈ 125.66 rad/s',
      'Identify parameters: N = 100 turns, B = 0.40 T, A = 0.05 m²',
      'Calculate: ε₀ = 100 × 0.40 × 0.05 × 125.66 = 251.33 V (approx 251 V)',
    ],
  },
  {
    id: 'kcse_p2',
    title: 'Problem 2: Commutator Output Frequency',
    question:
      'A single-loop dynamo rotates at 60 RPM. If the slip rings are replaced with a split-ring commutator to produce pulsating direct current (D.C.), how many voltage crests (pulses) per second appear across the external load (in Hz)?',
    unit: 'Hz',
    target: 2.0,
    tolerance: 0.1,
    hint: 'One revolution produces 1 full AC wave (1 positive crest, 1 negative trough). What does the split-ring commutator do to the negative half-cycle?',
    solutionSteps: [
      'Calculate rotation frequency: f_rotation = 60 RPM / 60 = 1.0 rev/s (1 Hz)',
      'In an AC generator (slip rings), 1 full revolution produces 1 AC cycle (1 Hz).',
      'The split-ring commutator inverts every negative half-cycle so it becomes positive.',
      'Hence, two positive pulsating crests occur in every single mechanical revolution: f_DC = 2 × f_rotation = 2.0 Hz.',
    ],
  },
  {
    id: 'kcse_p3',
    title: 'Problem 3: Coil Orientation for Zero vs Peak E.M.F.',
    question:
      'Consider an armature coil rotating between horizontal magnetic poles. At what coil orientation angle θ (in degrees, where θ = 0° corresponds to the coil plane being strictly vertical / perpendicular to the magnetic field) is the induced E.M.F. at its first positive maximum (+V_peak)?',
    unit: '°',
    target: 90,
    tolerance: 1.0,
    hint: 'Recall that induced EMF is given by ε = ε₀ sin(θ). At what angle is sin(θ) = 1?',
    solutionSteps: [
      'Induced EMF follows Faraday’s law: ε(θ) = ε₀ sin(θ)',
      'At θ = 0° (vertical), the coil arms move parallel to the magnetic field lines (v ∥ B), so rate of cutting flux lines is zero (ε = 0 V).',
      'At θ = 90° (horizontal), the coil arms move perpendicular to the field lines (v ⊥ B), cutting flux at the maximum rate.',
      'Therefore, sin(90°) = 1.0, yielding ε = +ε₀ (+V_peak).',
    ],
  },
];

// Helper: 3D Perspective Projection
function project3D(x, y, z, cx, cy, yaw, pitch, scale = 1.0) {
  const cosY = Math.cos(yaw);
  const sinY = Math.sin(yaw);
  const x1 = x * cosY + z * sinY;
  const z1 = -x * sinY + z * cosY;

  const cosP = Math.cos(pitch);
  const sinP = Math.sin(pitch);
  const y2 = y * cosP - z1 * sinP;
  const z2 = y * sinP + z1 * cosP;

  const fov = 520;
  const depth = fov / (fov + z2);
  return {
    x: cx + x1 * depth * scale,
    y: cy - y2 * depth * scale,
    z: z2,
    depth,
  };
}

export default function ACGeneratorSim({ config = {}, onTelemetry }) {
  // 1. Core Learner Variables
  const [commutatorType, setCommutatorType] = useState(
    config.commutatorType || DEFAULT_CONFIG.commutatorType
  );
  const [rpm, setRpm] = useState(config.rpm || DEFAULT_CONFIG.rpm);
  const [magneticFieldB, setMagneticFieldB] = useState(
    config.magneticFieldB || DEFAULT_CONFIG.magneticFieldB
  );
  const [coilTurnsN, setCoilTurnsN] = useState(
    config.coilTurnsN || DEFAULT_CONFIG.coilTurnsN
  );
  const coilArea = config.coilArea || DEFAULT_CONFIG.coilArea;
  const loadResistance = config.loadResistance || DEFAULT_CONFIG.loadResistance;

  // 2. Playback & Animation State
  const [isPlaying, setIsPlaying] = useState(true);
  const [playbackSpeed, setPlaybackSpeed] = useState(1.0);
  const [theta, setTheta] = useState(0); // in radians [0, 2*PI]

  // 3. 3D Camera Controls
  const [cameraPreset, setCameraPreset] = useState('isometric');
  const [yaw, setYaw] = useState(CAMERA_PRESETS.isometric.yaw);
  const [pitch, setPitch] = useState(CAMERA_PRESETS.isometric.pitch);

  // 4. Interactive Overlays & Toggles
  const [activeTab, setActiveTab] = useState('lab'); // 'lab' | 'fleming' | 'waveform' | 'theory' | 'kcse'
  const [selectedArm, setSelectedArm] = useState('AB'); // 'AB' | 'CD'
  const [showFieldLines, setShowFieldLines] = useState(true);
  const [showVelocityVectors, setShowVelocityVectors] = useState(true);
  const [showCurrentArrows, setShowCurrentArrows] = useState(true);
  const [showElectrons, setShowElectrons] = useState(true);

  // 5. KCSE Practice State
  const [activeProblemIdx, setActiveProblemIdx] = useState(0);
  const [userAnswer, setUserAnswer] = useState('');
  const [practiceStatus, setPracticeStatus] = useState(null); // null | 'correct' | 'incorrect'
  const [showSolution, setShowSolution] = useState(false);

  // Refs for animation & mouse drag
  const canvasRef = useRef(null);
  const animFrameRef = useRef(null);
  const lastTimeRef = useRef(performance.now());
  const thetaRef = useRef(0);
  const isDraggingRef = useRef(false);
  const lastMousePosRef = useRef({ x: 0, y: 0 });

  // Sync thetaRef
  useEffect(() => {
    thetaRef.current = theta;
  }, [theta]);

  // Derived Physics Computations
  const frequencyHz = useMemo(() => rpm / 60, [rpm]);
  const periodSec = useMemo(() => (frequencyHz > 0 ? 1 / frequencyHz : 0), [frequencyHz]);
  const omegaRadPerSec = useMemo(() => 2 * Math.PI * frequencyHz, [frequencyHz]);
  const peakEmf = useMemo(
    () => coilTurnsN * magneticFieldB * coilArea * omegaRadPerSec,
    [coilTurnsN, magneticFieldB, coilArea, omegaRadPerSec]
  );
  const rmsVoltage = useMemo(() => peakEmf / Math.SQRT2, [peakEmf]);

  // Current Instantaneous Quantities at active angle theta
  const thetaDegrees = useMemo(() => {
    const deg = ((theta * 180) / Math.PI) % 360;
    return deg < 0 ? deg + 360 : deg;
  }, [theta]);

  const rawSin = Math.sin(theta);
  const instantaneousEmfAC = peakEmf * rawSin;
  const instantaneousEmfDC = Math.abs(instantaneousEmfAC);
  const activeEmf = commutatorType === 'slip_rings' ? instantaneousEmfAC : instantaneousEmfDC;
  const loadCurrent = activeEmf / loadResistance;
  const instantaneousPower = Math.abs(activeEmf * loadCurrent);
  const maxPower = (peakEmf * peakEmf) / loadResistance;
  const magneticFlux = magneticFieldB * coilArea * Math.cos(theta); // Weber (Wb)

  // Arm Motion & Fleming RHR Analysis
  const armABData = useMemo(() => {
    // AB center: x = r*sin(theta), y = r*cos(theta)
    // Tangential velocity v: vx = r*omega*cos(theta), vy = -r*omega*sin(theta)
    const movingDown = rawSin > 0.05;
    const movingUp = rawSin < -0.05;
    let motionDescription = 'Cutting field lines downwards';
    let currentDir = 'From B to A (Forward to Ring 1)';
    let brushPolarity = '+ Positive Terminal';

    if (movingDown) {
      motionDescription = 'Moving DOWNWARDS across B-field (v ⊥ B)';
      currentDir = 'Induced current flows B ➔ A (Towards viewer)';
      brushPolarity = '+ (Positive Lead)';
    } else if (movingUp) {
      motionDescription = 'Moving UPWARDS across B-field (v ⊥ B)';
      currentDir = 'Induced current flows A ➔ B (Away from viewer)';
      brushPolarity = '- (Negative Lead)';
    } else {
      motionDescription = 'Moving PARALLEL to B-field (v ∥ B, no flux cut)';
      currentDir = 'Zero induced current (0 A)';
      brushPolarity = 'Neutral (0 V)';
    }

    return {
      name: 'Arm AB (Gold Lead)',
      color: '#f59e0b',
      motionDescription,
      currentDir,
      brushPolarity,
      vxSign: Math.cos(theta) > 0 ? '+x (Right)' : '-x (Left)',
      vySign: rawSin > 0 ? '-y (Down)' : '+y (Up)',
    };
  }, [theta, rawSin]);

  const armCDData = useMemo(() => {
    const movingUp = rawSin > 0.05;
    const movingDown = rawSin < -0.05;
    let motionDescription = 'Cutting field lines upwards';
    let currentDir = 'From D to C (Backward to Ring 2)';
    let brushPolarity = '- Negative Terminal';

    if (movingUp) {
      motionDescription = 'Moving UPWARDS across B-field (v ⊥ B)';
      currentDir = 'Induced current flows D ➔ C (Away from viewer)';
      brushPolarity = '- (Negative Lead)';
    } else if (movingDown) {
      motionDescription = 'Moving DOWNWARDS across B-field (v ⊥ B)';
      currentDir = 'Induced current flows C ➔ D (Towards viewer)';
      brushPolarity = '+ (Positive Lead)';
    } else {
      motionDescription = 'Moving PARALLEL to B-field (v ∥ B, no flux cut)';
      currentDir = 'Zero induced current (0 A)';
      brushPolarity = 'Neutral (0 V)';
    }

    return {
      name: 'Arm CD (Teal Lead)',
      color: '#06b6d4',
      motionDescription,
      currentDir,
      brushPolarity,
      vxSign: Math.cos(theta) > 0 ? '-x (Left)' : '+x (Right)',
      vySign: rawSin > 0 ? '+y (Up)' : '-y (Down)',
    };
  }, [theta, rawSin]);

  // Telemetry callback
  useEffect(() => {
    if (onTelemetry) {
      onTelemetry({
        rpm,
        magneticFieldB,
        coilTurnsN,
        peakEmf,
        frequencyHz,
        activeEmf,
        commutatorType,
        thetaDegrees,
      });
    }
  }, [rpm, magneticFieldB, coilTurnsN, peakEmf, frequencyHz, activeEmf, commutatorType, thetaDegrees, onTelemetry]);

  // Handle Preset View Camera
  const applyCameraPreset = (key) => {
    setCameraPreset(key);
    if (CAMERA_PRESETS[key]) {
      setYaw(CAMERA_PRESETS[key].yaw);
      setPitch(CAMERA_PRESETS[key].pitch);
    }
  };

  // Reset Function
  const handleReset = () => {
    setCommutatorType(DEFAULT_CONFIG.commutatorType);
    setRpm(DEFAULT_CONFIG.rpm);
    setMagneticFieldB(DEFAULT_CONFIG.magneticFieldB);
    setCoilTurnsN(DEFAULT_CONFIG.coilTurnsN);
    setTheta(0);
    thetaRef.current = 0;
    setIsPlaying(true);
    setPlaybackSpeed(1.0);
    applyCameraPreset('isometric');
    setUserAnswer('');
    setPracticeStatus(null);
    setShowSolution(false);
  };

  // Step Angle Controls
  const stepAngle = (degDelta) => {
    setIsPlaying(false);
    setTheta((prev) => {
      const next = prev + (degDelta * Math.PI) / 180;
      thetaRef.current = next;
      return next;
    });
  };

  const snapToAngle = (targetDeg) => {
    setIsPlaying(false);
    const rad = (targetDeg * Math.PI) / 180;
    setTheta(rad);
    thetaRef.current = rad;
  };

  // ==========================================
  // MAIN ANIMATION LOOP
  // ==========================================
  useEffect(() => {
    let animId;

    const loop = (timestamp) => {
      const dt = (timestamp - lastTimeRef.current) / 1000;
      lastTimeRef.current = timestamp;

      if (isPlaying) {
        // dTheta = omega * dt * playbackSpeed
        const dTheta = omegaRadPerSec * dt * playbackSpeed;
        thetaRef.current = (thetaRef.current + dTheta) % (2 * Math.PI);
        setTheta(thetaRef.current);
      }

      renderCanvas();
      animId = requestAnimationFrame(loop);
    };

    lastTimeRef.current = performance.now();
    animId = requestAnimationFrame(loop);

    return () => {
      if (animId) cancelAnimationFrame(animId);
    };
  }, [isPlaying, omegaRadPerSec, playbackSpeed, commutatorType, magneticFieldB, coilTurnsN, showFieldLines, showVelocityVectors, showCurrentArrows, showElectrons, yaw, pitch]);

  // ==========================================
  // 3D CANVAS RENDERING
  // ==========================================
  const renderCanvas = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Handle high-DPI scaling
    const dpr = window.devicePixelRatio || 1;
    const width = canvas.clientWidth;
    const height = canvas.clientHeight;
    if (canvas.width !== width * dpr || canvas.height !== height * dpr) {
      canvas.width = width * dpr;
      canvas.height = height * dpr;
    }

    ctx.save();
    ctx.scale(dpr, dpr);
    ctx.clearRect(0, 0, width, height);

    // Background Gradient (Dark Slate Lab Aesthetic)
    const bgGrad = ctx.createRadialGradient(
      width / 2,
      height * 0.45,
      40,
      width / 2,
      height * 0.5,
      width * 0.75
    );
    bgGrad.addColorStop(0, '#0f172a');
    bgGrad.addColorStop(0.7, '#090d16');
    bgGrad.addColorStop(1, '#030712');
    ctx.fillStyle = bgGrad;
    ctx.fillRect(0, 0, width, height);

    // Center of 3D projection (slightly above vertical center to allow room for circuit)
    const cx = width / 2;
    const cy = height * 0.44;
    const currentTheta = thetaRef.current;
    const sinT = Math.sin(currentTheta);
    const cosT = Math.cos(currentTheta);

    // Helper: draw arrow in 2D between projected 3D points
    const drawArrow = (p1, p2, color, lineWidth = 2, arrowSize = 6) => {
      const dx = p2.x - p1.x;
      const dy = p2.y - p1.y;
      const angle = Math.atan2(dy, dx);
      ctx.save();
      ctx.strokeStyle = color;
      ctx.fillStyle = color;
      ctx.lineWidth = lineWidth;
      ctx.beginPath();
      ctx.moveTo(p1.x, p1.y);
      ctx.lineTo(p2.x, p2.y);
      ctx.stroke();

      ctx.beginPath();
      ctx.moveTo(p2.x, p2.y);
      ctx.lineTo(
        p2.x - arrowSize * Math.cos(angle - Math.PI / 6),
        p2.y - arrowSize * Math.sin(angle - Math.PI / 6)
      );
      ctx.lineTo(
        p2.x - arrowSize * Math.cos(angle + Math.PI / 6),
        p2.y - arrowSize * Math.sin(angle + Math.PI / 6)
      );
      ctx.closePath();
      ctx.fill();
      ctx.restore();
    };

    // 1. Draw Lab Bench Grid Surface
    const benchY = -120;
    ctx.save();
    ctx.strokeStyle = 'rgba(30, 41, 59, 0.45)';
    ctx.lineWidth = 1;
    for (let gx = -240; gx <= 240; gx += 48) {
      const pStart = project3D(gx, benchY, -160, cx, cy, yaw, pitch);
      const pEnd = project3D(gx, benchY, 200, cx, cy, yaw, pitch);
      ctx.beginPath();
      ctx.moveTo(pStart.x, pStart.y);
      ctx.lineTo(pEnd.x, pEnd.y);
      ctx.stroke();
    }
    for (let gz = -160; gz <= 200; gz += 48) {
      const pStart = project3D(-240, benchY, gz, cx, cy, yaw, pitch);
      const pEnd = project3D(240, benchY, gz, cx, cy, yaw, pitch);
      ctx.beginPath();
      ctx.moveTo(pStart.x, pStart.y);
      ctx.lineTo(pEnd.x, pEnd.y);
      ctx.stroke();
    }
    ctx.restore();

    // 2. Magnetic Field Lines (Left North Pole to Right South Pole)
    if (showFieldLines) {
      ctx.save();
      ctx.lineWidth = 1.2;
      const numLines = 9;
      const animDash = (Date.now() / 30) % 24;

      for (let i = 0; i < numLines; i++) {
        const fy = -55 + (i % 3) * 55;
        const fz = -60 + Math.floor(i / 3) * 60;
        const p1 = project3D(-130, fy, fz, cx, cy, yaw, pitch);
        const p2 = project3D(130, fy, fz, cx, cy, yaw, pitch);

        ctx.strokeStyle = 'rgba(6, 182, 212, 0.28)';
        ctx.setLineDash([6, 8]);
        ctx.lineDashOffset = -animDash;
        ctx.beginPath();
        ctx.moveTo(p1.x, p1.y);
        ctx.lineTo(p2.x, p2.y);
        ctx.stroke();

        // Subtle midpoint arrowhead
        const pMid1 = project3D(-5, fy, fz, cx, cy, yaw, pitch);
        const pMid2 = project3D(15, fy, fz, cx, cy, yaw, pitch);
        drawArrow(pMid1, pMid2, 'rgba(6, 182, 212, 0.45)', 1.5, 4);
      }
      ctx.restore();
    }

    // 3. Draw Permanent Magnet Pole Pieces (North on Left, South on Right)
    // Left North Pole Block (Red / Crimson)
    const drawPoleBlock = (xBase, widthX, label, mainColor, faceColor, isNorth) => {
      const yMin = -75;
      const yMax = 75;
      const zMin = -80;
      const zMax = 80;

      // 8 Vertices of the 3D magnet block
      const v0 = project3D(xBase, yMin, zMin, cx, cy, yaw, pitch);
      const v1 = project3D(xBase + widthX, yMin, zMin, cx, cy, yaw, pitch);
      const v2 = project3D(xBase + widthX, yMax, zMin, cx, cy, yaw, pitch);
      const v3 = project3D(xBase, yMax, zMin, cx, cy, yaw, pitch);
      const v4 = project3D(xBase, yMin, zMax, cx, cy, yaw, pitch);
      const v5 = project3D(xBase + widthX, yMin, zMax, cx, cy, yaw, pitch);
      const v6 = project3D(xBase + widthX, yMax, zMax, cx, cy, yaw, pitch);
      const v7 = project3D(xBase, yMax, zMax, cx, cy, yaw, pitch);

      ctx.save();
      // Top Face
      ctx.fillStyle = faceColor;
      ctx.beginPath();
      ctx.moveTo(v3.x, v3.y);
      ctx.lineTo(v2.x, v2.y);
      ctx.lineTo(v6.x, v6.y);
      ctx.lineTo(v7.x, v7.y);
      ctx.closePath();
      ctx.fill();
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)';
      ctx.stroke();

      // Front Face
      ctx.fillStyle = mainColor;
      ctx.beginPath();
      ctx.moveTo(v4.x, v4.y);
      ctx.lineTo(v5.x, v5.y);
      ctx.lineTo(v6.x, v6.y);
      ctx.lineTo(v7.x, v7.y);
      ctx.closePath();
      ctx.fill();
      ctx.stroke();

      // Inner Pole Face (facing armature coil)
      const pFace = isNorth
        ? [v1, v2, v6, v5] // North inner face (+X)
        : [v0, v3, v7, v4]; // South inner face (-X)

      const innerGrad = ctx.createLinearGradient(
        pFace[0].x,
        pFace[0].y,
        pFace[2].x,
        pFace[2].y
      );
      innerGrad.addColorStop(0, mainColor);
      innerGrad.addColorStop(1, '#0f172a');
      ctx.fillStyle = innerGrad;
      ctx.beginPath();
      ctx.moveTo(pFace[0].x, pFace[0].y);
      ctx.lineTo(pFace[1].x, pFace[1].y);
      ctx.lineTo(pFace[2].x, pFace[2].y);
      ctx.lineTo(pFace[3].x, pFace[3].y);
      ctx.closePath();
      ctx.fill();
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.3)';
      ctx.stroke();

      // Large Pole Letter (N or S)
      const pCenter = isNorth
        ? project3D(xBase + widthX, 0, 0, cx, cy, yaw, pitch)
        : project3D(xBase, 0, 0, cx, cy, yaw, pitch);

      ctx.font = 'bold 26px system-ui, sans-serif';
      ctx.fillStyle = '#ffffff';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.shadowColor = isNorth ? '#ef4444' : '#0284c7';
      ctx.shadowBlur = 12;
      ctx.fillText(label, pCenter.x, pCenter.y);
      ctx.restore();
    };

    // Left North Pole (x = -200 to -135)
    drawPoleBlock(-200, 65, 'N', '#b91c1c', '#dc2626', true);
    // Right South Pole (x = 135 to 200)
    drawPoleBlock(135, 65, 'S', '#0369a1', '#0284c7', false);

    // 4. Central Rotating Axle / Shaft (Metallic Steel Rod along Z axis)
    const shaftZBack = -110;
    const shaftZFront = 175;
    const pShaftBack = project3D(0, 0, shaftZBack, cx, cy, yaw, pitch);
    const pShaftFront = project3D(0, 0, shaftZFront, cx, cy, yaw, pitch);

    ctx.save();
    ctx.strokeStyle = '#64748b';
    ctx.lineWidth = 7;
    ctx.lineCap = 'round';
    ctx.beginPath();
    ctx.moveTo(pShaftBack.x, pShaftBack.y);
    ctx.lineTo(pShaftFront.x, pShaftFront.y);
    ctx.stroke();

    ctx.strokeStyle = '#cbd5e1';
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.moveTo(pShaftBack.x, pShaftBack.y);
    ctx.lineTo(pShaftFront.x, pShaftFront.y);
    ctx.stroke();
    ctx.restore();

    // 5. Rectangular Armature Coil ABCD Coordinates
    // Radius r = 68, Coil Length L = 120 (from z = -60 to +60)
    const r = 68;
    const halfL = 60;

    // Corner Coordinates:
    // A: (r*sinT, r*cosT, +halfL)
    // B: (r*sinT, r*cosT, -halfL)
    // C: (-r*sinT, -r*cosT, -halfL)
    // D: (-r*sinT, -r*cosT, +halfL)
    const ptA = project3D(r * sinT, r * cosT, halfL, cx, cy, yaw, pitch);
    const ptB = project3D(r * sinT, r * cosT, -halfL, cx, cy, yaw, pitch);
    const ptC = project3D(-r * sinT, -r * cosT, -halfL, cx, cy, yaw, pitch);
    const ptD = project3D(-r * sinT, -r * cosT, halfL, cx, cy, yaw, pitch);

    // Coil Center Midpoints of arms for vector arrows
    const midAB = project3D(r * sinT, r * cosT, 0, cx, cy, yaw, pitch);
    const midCD = project3D(-r * sinT, -r * cosT, 0, cx, cy, yaw, pitch);

    // Dynamic Glow intensity based on instantaneous induced EMF
    const emfRatio = Math.abs(sinT);
    const glowBlur = 4 + emfRatio * 16;

    // 5a. Render Armature Core Shading (Subtle translucent winding loop interior)
    ctx.save();
    ctx.fillStyle = 'rgba(245, 158, 11, 0.05)';
    ctx.beginPath();
    ctx.moveTo(ptA.x, ptA.y);
    ctx.lineTo(ptB.x, ptB.y);
    ctx.lineTo(ptC.x, ptC.y);
    ctx.lineTo(ptD.x, ptD.y);
    ctx.closePath();
    ctx.fill();
    ctx.restore();

    // 5b. Render Connecting Arm BC (Back)
    ctx.save();
    ctx.strokeStyle = '#94a3b8';
    ctx.lineWidth = 3.5;
    ctx.lineJoin = 'round';
    ctx.beginPath();
    ctx.moveTo(ptB.x, ptB.y);
    ctx.lineTo(ptC.x, ptC.y);
    ctx.stroke();
    ctx.restore();

    // 5c. Render Arm CD (Teal Arm)
    ctx.save();
    ctx.strokeStyle = '#06b6d4';
    ctx.lineWidth = 4.2;
    ctx.shadowColor = '#06b6d4';
    ctx.shadowBlur = glowBlur;
    ctx.beginPath();
    ctx.moveTo(ptC.x, ptC.y);
    ctx.lineTo(ptD.x, ptD.y);
    ctx.stroke();
    ctx.restore();

    // 5d. Render Arm AB (Gold Arm)
    ctx.save();
    ctx.strokeStyle = '#f59e0b';
    ctx.lineWidth = 4.2;
    ctx.shadowColor = '#f59e0b';
    ctx.shadowBlur = glowBlur;
    ctx.beginPath();
    ctx.moveTo(ptA.x, ptA.y);
    ctx.lineTo(ptB.x, ptB.y);
    ctx.stroke();
    ctx.restore();

    // 5e. Render Connecting Front Arm DA and Leads to Commutator
    ctx.save();
    ctx.strokeStyle = '#94a3b8';
    ctx.lineWidth = 3.5;
    ctx.lineJoin = 'round';
    ctx.beginPath();
    ctx.moveTo(ptD.x, ptD.y);
    ctx.lineTo(ptA.x, ptA.y);
    ctx.stroke();
    ctx.restore();

    // 6. Velocity Vectors (v) at Arm AB and Arm CD (Lime Green)
    if (showVelocityVectors && omegaRadPerSec > 0) {
      // Tangential velocity:
      // AB: dx = cosT * vMag, dy = -sinT * vMag
      const vMag = 38;
      const vAB_end = project3D(
        r * sinT + cosT * vMag,
        r * cosT - sinT * vMag,
        0,
        cx,
        cy,
        yaw,
        pitch
      );
      drawArrow(midAB, vAB_end, '#22c55e', 2.8, 7);

      // CD: opposite tangential velocity
      const vCD_end = project3D(
        -r * sinT - cosT * vMag,
        -r * cosT + sinT * vMag,
        0,
        cx,
        cy,
        yaw,
        pitch
      );
      drawArrow(midCD, vCD_end, '#22c55e', 2.8, 7);

      // Label for Velocity
      ctx.save();
      ctx.font = 'bold 12px monospace';
      ctx.fillStyle = '#4ade80';
      ctx.fillText('v (motion)', vAB_end.x + 4, vAB_end.y - 4);
      ctx.fillText('v (motion)', vCD_end.x + 4, vCD_end.y - 4);
      ctx.restore();
    }

    // 7. Induced Current Flow Arrows on Arms (by Fleming RHR)
    if (showCurrentArrows && Math.abs(activeEmf) > 0.4) {
      // When sinT > 0: Current in AB is B -> A (forward, +z). Current in CD is D -> C (backward, -z).
      // When sinT < 0: Current in AB is A -> B (backward, -z). Current in CD is C -> D (forward, +z).
      const currentForwardAB = sinT > 0;
      const currentStartAB = currentForwardAB ? ptB : ptA;
      const currentEndAB = currentForwardAB ? ptA : ptB;

      const currentStartCD = currentForwardAB ? ptD : ptC;
      const currentEndCD = currentForwardAB ? ptC : ptD;

      const arrowScale = Math.min(1.0, Math.abs(sinT) * 1.2);
      if (arrowScale > 0.25) {
        drawArrow(currentStartAB, currentEndAB, '#facc15', 3.0, 8);
        drawArrow(currentStartCD, currentEndCD, '#38bdf8', 3.0, 8);
      }
    }

    // 8. ABCD Corner Labels Badges
    const drawCornerLabel = (pt, label, bg, border) => {
      ctx.save();
      ctx.fillStyle = bg;
      ctx.strokeStyle = border;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.arc(pt.x, pt.y, 9, 0, 2 * Math.PI);
      ctx.fill();
      ctx.stroke();

      ctx.font = 'bold 11px system-ui, sans-serif';
      ctx.fillStyle = '#ffffff';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(label, pt.x, pt.y);
      ctx.restore();
    };

    drawCornerLabel(ptA, 'A', '#d97706', '#fef08a');
    drawCornerLabel(ptB, 'B', '#b45309', '#fef08a');
    drawCornerLabel(ptC, 'C', '#0e7490', '#a5f3fc');
    drawCornerLabel(ptD, 'D', '#0891b2', '#a5f3fc');

    // 9. COMMUTATOR MECHANISM RENDERING (Front of Shaft)
    // Shaft position for rings: z = 95 to 145
    const zCommutator1 = 100;
    const zCommutator2 = 135;

    // External brush wire endpoints for later circuit connection
    let brush1WirePt = { x: cx, y: cy };
    let brush2WirePt = { x: cx, y: cy };

    if (commutatorType === 'slip_rings') {
      // SLIP RINGS (Two continuous brass rings + carbon brushes)
      // Ring 1 (connected to Arm A)
      const pR1_Center = project3D(0, 0, zCommutator1, cx, cy, yaw, pitch);
      const pR1_Top = project3D(0, 16, zCommutator1, cx, cy, yaw, pitch);
      const pR1_Bottom = project3D(0, -16, zCommutator1, cx, cy, yaw, pitch);

      ctx.save();
      ctx.fillStyle = '#d97706';
      ctx.strokeStyle = '#fef08a';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.ellipse(pR1_Center.x, pR1_Center.y, 16 * pR1_Center.depth, 16 * pR1_Center.depth, 0, 0, 2 * Math.PI);
      ctx.fill();
      ctx.stroke();

      // Carbon Brush 1 (pressing on top of Ring 1)
      const pB1 = project3D(0, 22, zCommutator1, cx, cy, yaw, pitch);
      ctx.fillStyle = '#1e293b';
      ctx.strokeStyle = '#94a3b8';
      ctx.lineWidth = 1.5;
      ctx.fillRect(pB1.x - 7, pB1.y - 7, 14, 10);
      ctx.strokeRect(pB1.x - 7, pB1.y - 7, 14, 10);
      brush1WirePt = { x: pB1.x, y: pB1.y - 7 };

      // Lead Wire from Arm A to Ring 1
      ctx.strokeStyle = '#f59e0b';
      ctx.lineWidth = 2.5;
      ctx.beginPath();
      ctx.moveTo(ptA.x, ptA.y);
      ctx.lineTo(pR1_Top.x, pR1_Top.y);
      ctx.stroke();

      // Ring 2 (connected to Arm D through central axle)
      const pR2_Center = project3D(0, 0, zCommutator2, cx, cy, yaw, pitch);
      const pR2_Bottom = project3D(0, -16, zCommutator2, cx, cy, yaw, pitch);

      ctx.fillStyle = '#0891b2';
      ctx.strokeStyle = '#a5f3fc';
      ctx.beginPath();
      ctx.ellipse(pR2_Center.x, pR2_Center.y, 16 * pR2_Center.depth, 16 * pR2_Center.depth, 0, 0, 2 * Math.PI);
      ctx.fill();
      ctx.stroke();

      // Carbon Brush 2 (pressing on bottom of Ring 2)
      const pB2 = project3D(0, -22, zCommutator2, cx, cy, yaw, pitch);
      ctx.fillStyle = '#1e293b';
      ctx.strokeStyle = '#94a3b8';
      ctx.fillRect(pB2.x - 7, pB2.y - 3, 14, 10);
      ctx.strokeRect(pB2.x - 7, pB2.y - 3, 14, 10);
      brush2WirePt = { x: pB2.x, y: pB2.y + 7 };

      // Lead Wire from Arm D to Ring 2
      ctx.strokeStyle = '#06b6d4';
      ctx.lineWidth = 2.5;
      ctx.beginPath();
      ctx.moveTo(ptD.x, ptD.y);
      ctx.lineTo(pR2_Bottom.x, pR2_Bottom.y);
      ctx.stroke();

      // Labeling for Slip Rings
      ctx.font = '10px monospace';
      ctx.fillStyle = '#fde047';
      ctx.fillText('Slip Ring 1 (A)', pR1_Center.x + 20, pR1_Center.y - 12);
      ctx.fillStyle = '#67e8f9';
      ctx.fillText('Slip Ring 2 (D)', pR2_Center.x + 20, pR2_Center.y + 16);
      ctx.restore();
    } else {
      // SPLIT-RING COMMUTATOR (Single cylinder split into 2 semi-rings + mica insulation gap)
      const zComm = 115;
      const pC_Center = project3D(0, 0, zComm, cx, cy, yaw, pitch);
      const ringRadius = 18 * pC_Center.depth;

      ctx.save();
      // Draw Split Segments (rotating with theta)
      // Half-segment 1 (Gold, connected to Arm A)
      ctx.fillStyle = '#d97706';
      ctx.strokeStyle = '#fef08a';
      ctx.lineWidth = 2.5;
      ctx.beginPath();
      ctx.arc(pC_Center.x, pC_Center.y, ringRadius, currentTheta, currentTheta + Math.PI);
      ctx.stroke();

      // Half-segment 2 (Teal, connected to Arm D)
      ctx.strokeStyle = '#06b6d4';
      ctx.beginPath();
      ctx.arc(pC_Center.x, pC_Center.y, ringRadius, currentTheta + Math.PI, currentTheta + 2 * Math.PI);
      ctx.stroke();

      // Insulating Mica Gaps (black lines rotating with theta)
      const gap1 = {
        x: pC_Center.x + ringRadius * Math.cos(currentTheta),
        y: pC_Center.y + ringRadius * Math.sin(currentTheta),
      };
      const gap2 = {
        x: pC_Center.x - ringRadius * Math.cos(currentTheta),
        y: pC_Center.y - ringRadius * Math.sin(currentTheta),
      };
      ctx.strokeStyle = '#020617';
      ctx.lineWidth = 3.5;
      ctx.beginPath();
      ctx.moveTo(gap1.x, gap1.y);
      ctx.lineTo(pC_Center.x, pC_Center.y);
      ctx.lineTo(gap2.x, gap2.y);
      ctx.stroke();

      // Stationary Brushes at Top and Bottom
      const pB1 = { x: pC_Center.x, y: pC_Center.y - ringRadius - 6 };
      const pB2 = { x: pC_Center.x, y: pC_Center.y + ringRadius + 6 };

      ctx.fillStyle = '#1e293b';
      ctx.strokeStyle = '#94a3b8';
      ctx.lineWidth = 1.5;
      ctx.fillRect(pB1.x - 8, pB1.y - 6, 16, 10);
      ctx.strokeRect(pB1.x - 8, pB1.y - 6, 16, 10);
      ctx.fillRect(pB2.x - 8, pB2.y - 4, 16, 10);
      ctx.strokeRect(pB2.x - 8, pB2.y - 4, 16, 10);

      brush1WirePt = { x: pB1.x, y: pB1.y - 6 };
      brush2WirePt = { x: pB2.x, y: pB2.y + 6 };

      // Leads to segments
      ctx.strokeStyle = '#f59e0b';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(ptA.x, ptA.y);
      ctx.lineTo(pC_Center.x, pC_Center.y);
      ctx.stroke();

      ctx.font = '10px monospace';
      ctx.fillStyle = '#fde047';
      ctx.fillText('Split-Ring Commutator', pC_Center.x + 24, pC_Center.y - 12);
      ctx.fillStyle = '#94a3b8';
      ctx.fillText('Mica Split Gaps', pC_Center.x + 24, pC_Center.y + 8);
      ctx.restore();
    }

    // 10. EXTERNAL LOAD CIRCUIT (Incandescent Lamp + Galvanometer + Current Flow)
    // Draw external wires from brushes down to the bottom console area
    const loadBoxY = height - 76;
    const bulbX = cx - 70;
    const meterX = cx + 70;

    ctx.save();
    // Wire 1 (from Brush 1 to Lamp/Meter)
    ctx.strokeStyle = '#e2e8f0';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(brush1WirePt.x, brush1WirePt.y);
    ctx.lineTo(brush1WirePt.x - 90, brush1WirePt.y - 20);
    ctx.lineTo(brush1WirePt.x - 90, loadBoxY);
    ctx.lineTo(bulbX, loadBoxY);
    ctx.stroke();

    // Wire 2 (from Brush 2 to Lamp/Meter return)
    ctx.beginPath();
    ctx.moveTo(brush2WirePt.x, brush2WirePt.y);
    ctx.lineTo(brush2WirePt.x + 90, brush2WirePt.y + 20);
    ctx.lineTo(brush2WirePt.x + 90, loadBoxY);
    ctx.lineTo(meterX, loadBoxY);
    ctx.stroke();

    // Bridge wire between Bulb and Meter
    ctx.beginPath();
    ctx.moveTo(bulbX + 24, loadBoxY);
    ctx.lineTo(meterX - 24, loadBoxY);
    ctx.stroke();

    // Dynamic Electron Drift Flow along External Circuit
    if (showElectrons && Math.abs(activeEmf) > 0.5) {
      const electronCount = 12;
      const speedFactor = (activeEmf / (peakEmf || 1)) * 0.08;
      const tAnim = (Date.now() * speedFactor) % 1000;

      ctx.fillStyle = '#38bdf8';
      ctx.shadowColor = '#0284c7';
      ctx.shadowBlur = 6;
      for (let i = 0; i < electronCount; i++) {
        const progress = ((tAnim / 1000 + i / electronCount) % 1 + 1) % 1;
        // Position along the horizontal bridge
        const eX = bulbX + 24 + progress * (meterX - 24 - (bulbX + 24));
        ctx.beginPath();
        ctx.arc(eX, loadBoxY, 2.5, 0, 2 * Math.PI);
        ctx.fill();
      }
    }
    ctx.restore();

    // 11. RENDER INCANDESCENT LOAD BULB
    ctx.save();
    const bulbGlowRatio = Math.min(1.0, instantaneousPower / (maxPower || 1));

    // Outer Radiant Glow Halo
    if (bulbGlowRatio > 0.05) {
      const haloRadius = 16 + bulbGlowRatio * 32;
      const glowGrad = ctx.createRadialGradient(
        bulbX,
        loadBoxY,
        4,
        bulbX,
        loadBoxY,
        haloRadius
      );
      glowGrad.addColorStop(0, `rgba(254, 240, 138, ${0.85 * bulbGlowRatio})`);
      glowGrad.addColorStop(0.5, `rgba(245, 158, 11, ${0.45 * bulbGlowRatio})`);
      glowGrad.addColorStop(1, 'transparent');
      ctx.fillStyle = glowGrad;
      ctx.beginPath();
      ctx.arc(bulbX, loadBoxY, haloRadius, 0, 2 * Math.PI);
      ctx.fill();
    }

    // Glass Bulb Outline
    ctx.fillStyle = 'rgba(255, 255, 255, 0.08)';
    ctx.strokeStyle = '#94a3b8';
    ctx.lineWidth = 1.8;
    ctx.beginPath();
    ctx.arc(bulbX, loadBoxY, 15, 0, 2 * Math.PI);
    ctx.fill();
    ctx.stroke();

    // Metal Base
    ctx.fillStyle = '#64748b';
    ctx.fillRect(bulbX - 6, loadBoxY + 12, 12, 6);

    // Tungsten Filament Coil
    ctx.strokeStyle = bulbGlowRatio > 0.1 ? '#fef08a' : '#475569';
    ctx.lineWidth = 2.2;
    ctx.shadowColor = '#facc15';
    ctx.shadowBlur = bulbGlowRatio > 0.1 ? 12 * bulbGlowRatio : 0;
    ctx.beginPath();
    ctx.moveTo(bulbX - 5, loadBoxY + 8);
    ctx.lineTo(bulbX - 3, loadBoxY - 4);
    ctx.lineTo(bulbX, loadBoxY - 7);
    ctx.lineTo(bulbX + 3, loadBoxY - 4);
    ctx.lineTo(bulbX + 5, loadBoxY + 8);
    ctx.stroke();

    // Bulb Label & Wattage
    ctx.font = '10px monospace';
    ctx.fillStyle = '#cbd5e1';
    ctx.textAlign = 'center';
    ctx.fillText('Lamp Load', bulbX, loadBoxY + 28);
    ctx.fillStyle = '#fde047';
    ctx.fillText(`${instantaneousPower.toFixed(1)} W`, bulbX, loadBoxY + 40);
    ctx.restore();

    // 12. RENDER CENTER-ZERO ANALOG GALVANOMETER
    ctx.save();
    // Meter Circular Face
    const meterRadius = 24;
    ctx.fillStyle = '#0f172a';
    ctx.strokeStyle = '#475569';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(meterX, loadBoxY, meterRadius, 0, 2 * Math.PI);
    ctx.fill();
    ctx.stroke();

    // Scale Arc & Zero Mark
    ctx.strokeStyle = '#94a3b8';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.arc(meterX, loadBoxY, 18, Math.PI * 1.15, Math.PI * 1.85);
    ctx.stroke();

    // Tick at Center (0)
    ctx.beginPath();
    ctx.moveTo(meterX, loadBoxY - 18);
    ctx.lineTo(meterX, loadBoxY - 13);
    ctx.stroke();

    // Deflecting Needle
    // In AC: swings from -1 to +1 (-Vpeak to +Vpeak)
    // In DC: deflects only in positive half from 0 to +1
    let needleNormalized = 0;
    if (peakEmf > 0) {
      if (commutatorType === 'slip_rings') {
        needleNormalized = activeEmf / peakEmf; // -1 to +1
      } else {
        needleNormalized = activeEmf / peakEmf; // 0 to +1
      }
    }

    const needleAngle = -Math.PI / 2 + needleNormalized * 0.95;
    const needleLen = 17;
    const needleEnd = {
      x: meterX + needleLen * Math.cos(needleAngle),
      y: loadBoxY + needleLen * Math.sin(needleAngle),
    };

    ctx.strokeStyle = '#ef4444';
    ctx.lineWidth = 2;
    ctx.shadowColor = '#ef4444';
    ctx.shadowBlur = 4;
    ctx.beginPath();
    ctx.moveTo(meterX, loadBoxY);
    ctx.lineTo(needleEnd.x, needleEnd.y);
    ctx.stroke();

    // Center Pivot Dot
    ctx.fillStyle = '#cbd5e1';
    ctx.beginPath();
    ctx.arc(meterX, loadBoxY, 2.5, 0, 2 * Math.PI);
    ctx.fill();

    // Galvanometer Readout Text
    ctx.font = '10px monospace';
    ctx.fillStyle = '#cbd5e1';
    ctx.textAlign = 'center';
    ctx.fillText('Galvanometer', meterX, loadBoxY + 28);
    ctx.fillStyle = activeEmf >= 0 ? '#4ade80' : '#f87171';
    ctx.fillText(`${activeEmf >= 0 ? '+' : ''}${activeEmf.toFixed(1)} V`, meterX, loadBoxY + 40);
    ctx.restore();

    ctx.restore();
  }, [commutatorType, showFieldLines, showVelocityVectors, showCurrentArrows, showElectrons, yaw, pitch, activeEmf, peakEmf, instantaneousPower, maxPower, omegaRadPerSec]);

  // ==========================================
  // OSCILLOSCOPE WAVEFORM CANVAS COMPONENT
  // ==========================================
  const renderOscilloscope = useCallback(
    (canvas) => {
      if (!canvas) return;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      const dpr = window.devicePixelRatio || 1;
      const width = canvas.clientWidth;
      const height = canvas.clientHeight;
      if (canvas.width !== width * dpr || canvas.height !== height * dpr) {
        canvas.width = width * dpr;
        canvas.height = height * dpr;
      }

      ctx.save();
      ctx.scale(dpr, dpr);
      ctx.clearRect(0, 0, width, height);

      // CRT Background
      ctx.fillStyle = '#020617';
      ctx.fillRect(0, 0, width, height);

      // Oscilloscope Grid Lines (Phosphor Slate Grid)
      ctx.strokeStyle = 'rgba(30, 41, 59, 0.6)';
      ctx.lineWidth = 1;
      const numCols = 8;
      const numRows = 4;

      for (let c = 0; c <= numCols; c++) {
        const x = (c / numCols) * width;
        ctx.beginPath();
        ctx.moveTo(x, 0);
        ctx.lineTo(x, height);
        ctx.stroke();
      }
      for (let r = 0; r <= numRows; r++) {
        const y = (r / numRows) * height;
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(width, y);
        ctx.stroke();
      }

      // Midline (0 V Zero Reference)
      const midY = height / 2;
      ctx.strokeStyle = 'rgba(71, 85, 105, 0.9)';
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(0, midY);
      ctx.lineTo(width, midY);
      ctx.stroke();

      // Peak +V and -V Dotted Lines
      const waveAmplitude = height * 0.38;
      ctx.strokeStyle = 'rgba(148, 163, 184, 0.3)';
      ctx.setLineDash([4, 4]);
      ctx.beginPath();
      ctx.moveTo(0, midY - waveAmplitude);
      ctx.lineTo(width, midY - waveAmplitude);
      ctx.moveTo(0, midY + waveAmplitude);
      ctx.lineTo(width, midY + waveAmplitude);
      ctx.stroke();
      ctx.setLineDash([]);

      // Axis Labels
      ctx.font = '10px monospace';
      ctx.fillStyle = '#64748b';
      ctx.fillText('+V₀', 6, midY - waveAmplitude + 10);
      ctx.fillText('0 V', 6, midY - 3);
      if (commutatorType === 'slip_rings') {
        ctx.fillText('-V₀', 6, midY + waveAmplitude - 4);
      }

      // Angle Reference Grid Labels (0°, 90°, 180°, 270°, 360°, 540°, 720°)
      // We show 2 full cycles (720 degrees)
      const angleLabels = [
        { deg: 0, label: '0°' },
        { deg: 90, label: '90°' },
        { deg: 180, label: '180°' },
        { deg: 270, label: '270°' },
        { deg: 360, label: '360°' },
        { deg: 540, label: '540°' },
        { deg: 720, label: '720°' },
      ];
      ctx.textAlign = 'center';
      angleLabels.forEach((al) => {
        const xPos = (al.deg / 720) * width;
        ctx.fillText(al.label, xPos, height - 6);
      });

      // Plot Theoretical Full 2-Cycle Reference Curve
      ctx.save();
      ctx.lineWidth = 2.2;
      ctx.strokeStyle = commutatorType === 'slip_rings' ? 'rgba(34, 197, 94, 0.35)' : 'rgba(245, 158, 11, 0.35)';
      ctx.beginPath();
      const samples = 200;
      for (let s = 0; s <= samples; s++) {
        const frac = s / samples;
        const ang = frac * 4 * Math.PI; // 0 to 720 deg
        const raw = Math.sin(ang);
        const yVal =
          commutatorType === 'slip_rings'
            ? midY - raw * waveAmplitude
            : midY - Math.abs(raw) * waveAmplitude;
        const xPos = frac * width;
        if (s === 0) ctx.moveTo(xPos, yVal);
        else ctx.lineTo(xPos, yVal);
      }
      ctx.stroke();
      ctx.restore();

      // Plot Active Scanning Phosphor Trace up to Current Theta (modulo 720 deg)
      const currentDeg = ((thetaDegrees % 360) + 360) % 360;
      const progressFrac = currentDeg / 720;
      const traceSamples = Math.floor(progressFrac * samples);

      ctx.save();
      ctx.lineWidth = 3.2;
      ctx.strokeStyle = commutatorType === 'slip_rings' ? '#22c55e' : '#f59e0b';
      ctx.shadowColor = commutatorType === 'slip_rings' ? '#4ade80' : '#facc15';
      ctx.shadowBlur = 10;
      ctx.beginPath();
      for (let s = 0; s <= traceSamples; s++) {
        const frac = s / samples;
        const ang = frac * 4 * Math.PI;
        const raw = Math.sin(ang);
        const yVal =
          commutatorType === 'slip_rings'
            ? midY - raw * waveAmplitude
            : midY - Math.abs(raw) * waveAmplitude;
        const xPos = frac * width;
        if (s === 0) ctx.moveTo(xPos, yVal);
        else ctx.lineTo(xPos, yVal);
      }
      ctx.stroke();

      // Glowing Scanning Dot on Oscilloscope
      const currentX = progressFrac * width;
      const currentY =
        commutatorType === 'slip_rings'
          ? midY - rawSin * waveAmplitude
          : midY - Math.abs(rawSin) * waveAmplitude;

      ctx.fillStyle = '#ffffff';
      ctx.shadowColor = commutatorType === 'slip_rings' ? '#22c55e' : '#f59e0b';
      ctx.shadowBlur = 14;
      ctx.beginPath();
      ctx.arc(currentX, currentY, 5, 0, 2 * Math.PI);
      ctx.fill();
      ctx.restore();

      ctx.restore();
    },
    [commutatorType, thetaDegrees, rawSin]
  );

  // Oscilloscope Canvas Ref & Effect
  const oscCanvasRef = useRef(null);
  useEffect(() => {
    renderOscilloscope(oscCanvasRef.current);
  }, [renderOscilloscope, thetaDegrees, commutatorType]);

  // ==========================================
  // MOUSE & TOUCH 3D ROTATION HANDLERS
  // ==========================================
  const handleMouseDown = (e) => {
    isDraggingRef.current = true;
    lastMousePosRef.current = { x: e.clientX, y: e.clientY };
  };

  const handleMouseMove = (e) => {
    if (!isDraggingRef.current) return;
    const dx = e.clientX - lastMousePosRef.current.x;
    const dy = e.clientY - lastMousePosRef.current.y;
    lastMousePosRef.current = { x: e.clientX, y: e.clientY };

    setYaw((prev) => prev - dx * 0.007);
    setPitch((prev) => Math.max(-1.4, Math.min(1.4, prev + dy * 0.007)));
    setCameraPreset('custom');
  };

  const handleMouseUp = () => {
    isDraggingRef.current = false;
  };

  const handleTouchStart = (e) => {
    if (e.touches.length === 1) {
      isDraggingRef.current = true;
      lastMousePosRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
    }
  };

  const handleTouchMove = (e) => {
    if (!isDraggingRef.current || e.touches.length !== 1) return;
    const dx = e.touches[0].clientX - lastMousePosRef.current.x;
    const dy = e.touches[0].clientY - lastMousePosRef.current.y;
    lastMousePosRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };

    setYaw((prev) => prev - dx * 0.007);
    setPitch((prev) => Math.max(-1.4, Math.min(1.4, prev + dy * 0.007)));
    setCameraPreset('custom');
  };

  const handleTouchEnd = () => {
    isDraggingRef.current = false;
  };

  // KCSE Practice Answer Check
  const handleCheckAnswer = () => {
    const prob = KCSE_PROBLEMS[activeProblemIdx];
    const parsed = parseFloat(userAnswer);
    if (isNaN(parsed)) {
      setPracticeStatus('incorrect');
      return;
    }
    const diff = Math.abs(parsed - prob.target);
    if (diff <= prob.tolerance) {
      setPracticeStatus('correct');
    } else {
      setPracticeStatus('incorrect');
    }
  };

  return (
    <div className="w-full bg-slate-950 text-slate-100 rounded-3xl p-4 sm:p-6 md:p-8 space-y-6 font-sans border border-slate-800 shadow-2xl">
      {/* 1. HEADER WITH TOPIC BADGE, TITLE, AND GLOBAL ACTIONS */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-6">
        <div className="space-y-1">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-cyan-500/10 text-cyan-400 border border-cyan-500/30">
              <Radio className="w-3.5 h-3.5" /> Form 4 Physics • Topic 5: Electromagnetic Induction
            </span>
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/30">
              <Zap className="w-3.5 h-3.5" /> Faraday’s Law & Fleming Dynamo Rule
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-extrabold tracking-tight bg-gradient-to-r from-cyan-400 via-amber-300 to-emerald-400 bg-clip-text text-transparent">
            AC Generator & Alternating Current Dynamo
          </h2>
          <p className="text-sm text-slate-400 max-w-3xl leading-relaxed">
            Investigate how mechanical rotational energy converts into electrical energy:{' '}
            <span className="text-amber-300 font-mono font-semibold">ε(t) = B·A·ω·N·sin(ωt)</span>. Compare continuous{' '}
            <span className="text-emerald-400 font-semibold">Slip Rings (AC)</span> with a{' '}
            <span className="text-cyan-400 font-semibold">Split-Ring Commutator (Pulsating DC)</span>, Fleming's Right-Hand Rule, and dynamic oscilloscope traces.
          </p>
        </div>

        <div className="flex items-center gap-2.5 flex-wrap">
          <button
            onClick={() => setActiveTab('fleming')}
            className={`px-3.5 py-2 rounded-xl text-xs font-medium border transition-all flex items-center gap-1.5 ${
              activeTab === 'fleming'
                ? 'bg-amber-500/20 text-amber-300 border-amber-500/40 shadow-lg shadow-amber-500/10'
                : 'bg-slate-900 hover:bg-slate-800 text-slate-300 border-slate-700'
            }`}
          >
            <Compass className="w-3.5 h-3.5 text-amber-400" />
            Fleming RHR Guide
          </button>

          <button
            onClick={handleReset}
            className="px-3.5 py-2 rounded-xl text-xs font-medium bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-700 transition-colors flex items-center gap-1.5"
            title="Reset simulation to default state"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            Reset
          </button>
        </div>
      </div>

      {/* 2. NAVIGATION TABS */}
      <div className="flex items-center gap-2 border-b border-slate-800 pb-3 overflow-x-auto no-scrollbar">
        {[
          { id: 'lab', label: '3D Generator Lab', icon: Zap },
          { id: 'fleming', label: 'Fleming’s Right-Hand Rule', icon: Compass },
          { id: 'waveform', label: 'Oscilloscope Waveforms', icon: Activity },
          { id: 'theory', label: 'Curriculum Theory & Formulas', icon: BookOpen },
          { id: 'kcse', label: 'KCSE Exam Challenges', icon: Sparkles },
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                isActive
                  ? 'bg-gradient-to-r from-cyan-500/20 to-amber-500/20 text-cyan-300 border border-cyan-500/40 shadow-md shadow-cyan-500/10'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900/60 border border-transparent'
              }`}
            >
              <Icon className={`w-4 h-4 ${isActive ? 'text-cyan-400' : 'text-slate-500'}`} />
              {tab.label}
            </button>
          );
        })}
      </div>

      {/* 3. TAB CONTENT PANELS */}
      {/* TAB 1: 3D GENERATOR LAB */}
      {activeTab === 'lab' && (
        <div className="space-y-6">
          {/* Main Stage Grid: 3D Canvas (Left/Top) + Live Telemetry / Fast Controls (Right) */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* 3D Visual Stage (8 cols) */}
            <div className="lg:col-span-8 flex flex-col space-y-3">
              <div className="relative rounded-2xl overflow-hidden bg-slate-900/90 border border-slate-800 shadow-inner">
                {/* View Camera Presets Bar */}
                <div className="absolute top-3 left-3 z-10 flex items-center gap-1.5 bg-slate-950/85 backdrop-blur-md p-1.5 rounded-xl border border-slate-800 shadow-lg">
                  <span className="text-[11px] font-semibold text-slate-400 px-2 flex items-center gap-1">
                    <Eye className="w-3 h-3 text-cyan-400" /> View:
                  </span>
                  {Object.entries(CAMERA_PRESETS).map(([key, preset]) => (
                    <button
                      key={key}
                      onClick={() => applyCameraPreset(key)}
                      className={`px-2.5 py-1 text-[11px] font-medium rounded-lg transition-all ${
                        cameraPreset === key
                          ? 'bg-cyan-500 text-slate-950 font-bold shadow-md shadow-cyan-500/20'
                          : 'text-slate-300 hover:text-white hover:bg-slate-800/80'
                      }`}
                    >
                      {preset.label}
                    </button>
                  ))}
                </div>

                {/* Commutator Type Pill Badge */}
                <div className="absolute top-3 right-3 z-10 bg-slate-950/85 backdrop-blur-md px-3 py-1.5 rounded-xl border border-slate-800 flex items-center gap-2 shadow-lg">
                  <span className="w-2 h-2 rounded-full animate-pulse bg-amber-400" />
                  <span className="text-xs font-semibold text-slate-200">
                    Mode: {commutatorType === 'slip_rings' ? 'AC (Slip Rings)' : 'DC (Split-Ring Commutator)'}
                  </span>
                </div>

                {/* Instantaneous Angle & Voltage Inset Badge */}
                <div className="absolute bottom-3 left-3 z-10 bg-slate-950/90 backdrop-blur-md p-2.5 rounded-xl border border-slate-800 text-xs space-y-1 shadow-lg pointer-events-none">
                  <div className="flex items-center gap-3">
                    <span className="text-slate-400">Coil Angle θ:</span>
                    <span className="font-mono font-bold text-amber-300 text-sm">
                      {thetaDegrees.toFixed(1)}°
                    </span>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-slate-400">Induced E.M.F.:</span>
                    <span
                      className={`font-mono font-bold text-sm ${
                        activeEmf >= 0 ? 'text-emerald-400' : 'text-rose-400'
                      }`}
                    >
                      {activeEmf >= 0 ? '+' : ''}
                      {activeEmf.toFixed(2)} V
                    </span>
                  </div>
                  <div className="text-[10px] text-slate-400">
                    {thetaDegrees < 10 || (thetaDegrees > 170 && thetaDegrees < 190) || thetaDegrees > 350
                      ? 'Coil Vertical: Arms move ∥ B-field (EMF ≈ 0)'
                      : (thetaDegrees > 80 && thetaDegrees < 100) || (thetaDegrees > 260 && thetaDegrees < 280)
                      ? 'Coil Horizontal: Arms move ⊥ B-field (Max Cutting Rate)'
                      : 'Cutting field lines at intermediate angle'}
                  </div>
                </div>

                {/* HTML5 3D Canvas */}
                <canvas
                  ref={canvasRef}
                  onMouseDown={handleMouseDown}
                  onMouseMove={handleMouseMove}
                  onMouseUp={handleMouseUp}
                  onMouseLeave={handleMouseUp}
                  onTouchStart={handleTouchStart}
                  onTouchMove={handleTouchMove}
                  onTouchEnd={handleTouchEnd}
                  className="w-full h-[420px] sm:h-[480px] cursor-grab active:cursor-grabbing block"
                />
              </div>

              {/* Playback Controls & Quick Angle Jumps */}
              <div className="flex flex-wrap items-center justify-between gap-3 bg-slate-900/80 p-3 rounded-2xl border border-slate-800">
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setIsPlaying(!isPlaying)}
                    className={`p-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
                      isPlaying
                        ? 'bg-amber-500 hover:bg-amber-400 text-slate-950 shadow-md shadow-amber-500/20'
                        : 'bg-emerald-500 hover:bg-emerald-400 text-slate-950 shadow-md shadow-emerald-500/20'
                    }`}
                  >
                    {isPlaying ? <Pause className="w-4 h-4 fill-current" /> : <Play className="w-4 h-4 fill-current" />}
                    <span>{isPlaying ? 'Pause' : 'Rotate Coil'}</span>
                  </button>

                  <button
                    onClick={() => stepAngle(-15)}
                    className="p-2.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl transition-colors"
                    title="Step -15°"
                  >
                    <SkipBack className="w-4 h-4" />
                  </button>

                  <button
                    onClick={() => stepAngle(15)}
                    className="p-2.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl transition-colors"
                    title="Step +15°"
                  >
                    <SkipForward className="w-4 h-4" />
                  </button>
                </div>

                {/* Quick Angle Snap Buttons */}
                <div className="flex items-center gap-1.5 flex-wrap">
                  <span className="text-[11px] font-semibold text-slate-400 mr-1">Snap Angle:</span>
                  {[0, 90, 180, 270].map((ang) => (
                    <button
                      key={ang}
                      onClick={() => snapToAngle(ang)}
                      className={`px-2.5 py-1 text-xs font-mono font-medium rounded-lg border transition-all ${
                        Math.abs(thetaDegrees - ang) < 3
                          ? 'bg-amber-500/20 text-amber-300 border-amber-500/50'
                          : 'bg-slate-950 text-slate-400 border-slate-800 hover:text-slate-200'
                      }`}
                    >
                      {ang}°
                    </button>
                  ))}
                </div>

                {/* Playback Speed Multiplier */}
                <div className="flex items-center gap-1 bg-slate-950 px-2 py-1 rounded-xl border border-slate-800">
                  <span className="text-[10px] text-slate-400 font-semibold px-1">Speed:</span>
                  {[0.5, 1.0, 2.0].map((s) => (
                    <button
                      key={s}
                      onClick={() => setPlaybackSpeed(s)}
                      className={`px-1.5 py-0.5 text-[11px] font-semibold rounded ${
                        playbackSpeed === s
                          ? 'bg-cyan-500 text-slate-950'
                          : 'text-slate-400 hover:text-white'
                      }`}
                    >
                      {s}x
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Right Telemetry & Live Engineering Readout (4 cols) */}
            <div className="lg:col-span-4 flex flex-col space-y-4">
              {/* Primary Commutator Selection Card */}
              <div className="bg-slate-900/90 rounded-2xl p-4 border border-slate-800 space-y-3 shadow-lg">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                    <Sliders className="w-3.5 h-3.5 text-cyan-400" /> Commutator Selection
                  </h3>
                  <span className="text-[10px] bg-slate-800 px-2 py-0.5 rounded text-slate-300 font-mono">
                    KCSE Core
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={() => setCommutatorType('slip_rings')}
                    className={`p-3 rounded-xl border text-left transition-all ${
                      commutatorType === 'slip_rings'
                        ? 'bg-emerald-500/15 border-emerald-500/50 text-emerald-300 shadow-md shadow-emerald-500/10'
                        : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
                    }`}
                  >
                    <div className="text-xs font-bold text-white mb-1">Slip Rings</div>
                    <div className="text-[10px] leading-tight text-slate-400">
                      Two continuous brass rings. Reversing polarity every 180° ➔ Alternating Current (A.C.).
                    </div>
                  </button>

                  <button
                    onClick={() => setCommutatorType('split_ring')}
                    className={`p-3 rounded-xl border text-left transition-all ${
                      commutatorType === 'split_ring'
                        ? 'bg-cyan-500/15 border-cyan-500/50 text-cyan-300 shadow-md shadow-cyan-500/10'
                        : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
                    }`}
                  >
                    <div className="text-xs font-bold text-white mb-1">Split-Ring</div>
                    <div className="text-[10px] leading-tight text-slate-400">
                      Commutator splits contacts every 180° ➔ Unidirectional Pulsating Direct Current (D.C.).
                    </div>
                  </button>
                </div>
              </div>

              {/* Quantitative Metrics Card */}
              <div className="bg-slate-900/90 rounded-2xl p-4 border border-slate-800 space-y-3 shadow-lg">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                  <Gauge className="w-3.5 h-3.5 text-amber-400" /> Real-Time Telemetry
                </h3>

                <div className="grid grid-cols-2 gap-2.5">
                  <div className="bg-slate-950/70 p-2.5 rounded-xl border border-slate-800/80">
                    <div className="text-[10px] text-slate-400">Peak E.M.F. (ε₀)</div>
                    <div className="text-lg font-extrabold font-mono text-cyan-400">
                      {peakEmf.toFixed(2)} <span className="text-xs text-slate-400">V</span>
                    </div>
                    <div className="text-[9px] text-slate-500">ε₀ = N·B·A·ω</div>
                  </div>

                  <div className="bg-slate-950/70 p-2.5 rounded-xl border border-slate-800/80">
                    <div className="text-[10px] text-slate-400">R.M.S. Voltage</div>
                    <div className="text-lg font-extrabold font-mono text-emerald-400">
                      {rmsVoltage.toFixed(2)} <span className="text-xs text-slate-400">V</span>
                    </div>
                    <div className="text-[9px] text-slate-500">V_rms = ε₀ / √2</div>
                  </div>

                  <div className="bg-slate-950/70 p-2.5 rounded-xl border border-slate-800/80">
                    <div className="text-[10px] text-slate-400">AC Frequency (f)</div>
                    <div className="text-lg font-extrabold font-mono text-amber-400">
                      {frequencyHz.toFixed(2)} <span className="text-xs text-slate-400">Hz</span>
                    </div>
                    <div className="text-[9px] text-slate-500">f = RPM / 60</div>
                  </div>

                  <div className="bg-slate-950/70 p-2.5 rounded-xl border border-slate-800/80">
                    <div className="text-[10px] text-slate-400">Period (T)</div>
                    <div className="text-lg font-extrabold font-mono text-purple-400">
                      {periodSec.toFixed(2)} <span className="text-xs text-slate-400">s</span>
                    </div>
                    <div className="text-[9px] text-slate-500">T = 1 / f</div>
                  </div>
                </div>

                {/* Instantaneous Load Power */}
                <div className="bg-slate-950/70 p-2.5 rounded-xl border border-slate-800/80 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Lightbulb className="w-4 h-4 text-amber-400" />
                    <div>
                      <div className="text-[10px] text-slate-400">Bulb Power P(t)</div>
                      <div className="text-xs font-mono font-bold text-slate-200">
                        {instantaneousPower.toFixed(2)} W / {maxPower.toFixed(1)} W peak
                      </div>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-[10px] text-slate-400">Magnetic Flux Φ</div>
                    <div className="text-xs font-mono font-bold text-cyan-300">
                      {(magneticFlux * 1000).toFixed(1)} mWb
                    </div>
                  </div>
                </div>
              </div>

              {/* Visual Layer Toggles */}
              <div className="bg-slate-900/90 rounded-2xl p-4 border border-slate-800 space-y-2.5 shadow-lg">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                  <Layers className="w-3.5 h-3.5 text-indigo-400" /> Vector & Particle Overlays
                </h3>

                <div className="grid grid-cols-2 gap-2 text-xs">
                  <label className="flex items-center gap-2 p-2 rounded-xl bg-slate-950/60 border border-slate-800/80 cursor-pointer hover:bg-slate-800/40">
                    <input
                      type="checkbox"
                      checked={showFieldLines}
                      onChange={(e) => setShowFieldLines(e.target.checked)}
                      className="rounded accent-cyan-500"
                    />
                    <span className="text-slate-300 text-[11px]">B-Field Flux Lines</span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-xl bg-slate-950/60 border border-slate-800/80 cursor-pointer hover:bg-slate-800/40">
                    <input
                      type="checkbox"
                      checked={showVelocityVectors}
                      onChange={(e) => setShowVelocityVectors(e.target.checked)}
                      className="rounded accent-emerald-500"
                    />
                    <span className="text-slate-300 text-[11px]">Velocity (v) Vector</span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-xl bg-slate-950/60 border border-slate-800/80 cursor-pointer hover:bg-slate-800/40">
                    <input
                      type="checkbox"
                      checked={showCurrentArrows}
                      onChange={(e) => setShowCurrentArrows(e.target.checked)}
                      className="rounded accent-amber-500"
                    />
                    <span className="text-slate-300 text-[11px]">Arm Current (I)</span>
                  </label>

                  <label className="flex items-center gap-2 p-2 rounded-xl bg-slate-950/60 border border-slate-800/80 cursor-pointer hover:bg-slate-800/40">
                    <input
                      type="checkbox"
                      checked={showElectrons}
                      onChange={(e) => setShowElectrons(e.target.checked)}
                      className="rounded accent-sky-500"
                    />
                    <span className="text-slate-300 text-[11px]">Drift Electrons</span>
                  </label>
                </div>
              </div>
            </div>
          </div>

          {/* Sliders Console Panel */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 bg-slate-900/80 p-5 rounded-2xl border border-slate-800">
            {/* Slider 1: RPM */}
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs">
                <span className="font-semibold text-slate-300 flex items-center gap-1.5">
                  <Activity className="w-3.5 h-3.5 text-cyan-400" /> Armature Speed (RPM)
                </span>
                <span className="font-mono font-bold text-cyan-400">{rpm} RPM</span>
              </div>
              <input
                type="range"
                min="10"
                max="120"
                step="5"
                value={rpm}
                onChange={(e) => setRpm(Number(e.target.value))}
                className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-cyan-500"
              />
              <div className="flex justify-between text-[10px] text-slate-500 font-mono">
                <span>10 RPM</span>
                <span>60 RPM (1 Hz)</span>
                <span>120 RPM</span>
              </div>
            </div>

            {/* Slider 2: Magnetic Field B */}
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs">
                <span className="font-semibold text-slate-300 flex items-center gap-1.5">
                  <Compass className="w-3.5 h-3.5 text-amber-400" /> Magnetic Flux Density (B)
                </span>
                <span className="font-mono font-bold text-amber-400">{magneticFieldB.toFixed(2)} T</span>
              </div>
              <input
                type="range"
                min="0.2"
                max="1.2"
                step="0.05"
                value={magneticFieldB}
                onChange={(e) => setMagneticFieldB(Number(e.target.value))}
                className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-amber-500"
              />
              <div className="flex justify-between text-[10px] text-slate-500 font-mono">
                <span>0.20 T</span>
                <span>0.60 T</span>
                <span>1.20 T</span>
              </div>
            </div>

            {/* Slider 3: Coil Turns N */}
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs">
                <span className="font-semibold text-slate-300 flex items-center gap-1.5">
                  <Zap className="w-3.5 h-3.5 text-emerald-400" /> Coil Windings (N)
                </span>
                <span className="font-mono font-bold text-emerald-400">{coilTurnsN} turns</span>
              </div>
              <input
                type="range"
                min="20"
                max="120"
                step="5"
                value={coilTurnsN}
                onChange={(e) => setCoilTurnsN(Number(e.target.value))}
                className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-emerald-500"
              />
              <div className="flex justify-between text-[10px] text-slate-500 font-mono">
                <span>20 turns</span>
                <span>50 turns</span>
                <span>120 turns</span>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: FLEMING'S RIGHT-HAND RULE (DYNAMO RULE) DEEP DIVE */}
      {activeTab === 'fleming' && (
        <div className="space-y-6">
          <div className="bg-slate-900/90 rounded-2xl p-6 border border-slate-800 space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
              <div>
                <h3 className="text-xl font-bold text-slate-100 flex items-center gap-2">
                  <Compass className="w-5 h-5 text-amber-400" />
                  Fleming’s Right-Hand Rule (The Dynamo Rule)
                </h3>
                <p className="text-xs text-slate-400 mt-1">
                  Predicts the direction of induced current when a conductor moves across a magnetic field.
                </p>
              </div>

              {/* Arm Selector */}
              <div className="flex items-center gap-2 bg-slate-950 p-1.5 rounded-xl border border-slate-800">
                <span className="text-xs font-semibold text-slate-400 px-2">Inspect Arm:</span>
                <button
                  onClick={() => setSelectedArm('AB')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    selectedArm === 'AB'
                      ? 'bg-amber-500 text-slate-950 shadow-md shadow-amber-500/20'
                      : 'text-slate-400 hover:text-white'
                  }`}
                >
                  Arm AB (Gold Lead)
                </button>
                <button
                  onClick={() => setSelectedArm('CD')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    selectedArm === 'CD'
                      ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/20'
                      : 'text-slate-400 hover:text-white'
                  }`}
                >
                  Arm CD (Teal Lead)
                </button>
              </div>
            </div>

            {/* Three Mutually Perpendicular Fingers Visual Diagram */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Thumb */}
              <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-2xl p-4 space-y-2">
                <div className="flex items-center gap-2 text-emerald-400 font-bold text-sm">
                  <ArrowUp className="w-4 h-4" /> 1. Thumb: Motion (v)
                </div>
                <div className="text-xs text-slate-300">
                  Points in the direction of conductor motion relative to the magnetic field.
                </div>
                <div className="bg-slate-950/80 p-2 rounded-lg border border-emerald-500/20 text-xs font-mono text-emerald-300">
                  {selectedArm === 'AB' ? armABData.motionDescription : armCDData.motionDescription}
                </div>
              </div>

              {/* Forefinger */}
              <div className="bg-cyan-500/10 border border-cyan-500/30 rounded-2xl p-4 space-y-2">
                <div className="flex items-center gap-2 text-cyan-400 font-bold text-sm">
                  <ArrowRight className="w-4 h-4" /> 2. Forefinger: Field (B)
                </div>
                <div className="text-xs text-slate-300">
                  Points along the magnetic field lines from North Pole (N) to South Pole (S).
                </div>
                <div className="bg-slate-950/80 p-2 rounded-lg border border-cyan-500/20 text-xs font-mono text-cyan-300">
                  Directed horizontally: Left (N) ➔ Right (S) [B = {magneticFieldB.toFixed(2)} T]
                </div>
              </div>

              {/* Center Finger */}
              <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl p-4 space-y-2">
                <div className="flex items-center gap-2 text-amber-400 font-bold text-sm">
                  <Zap className="w-4 h-4" /> 3. Center Finger: Current (I)
                </div>
                <div className="text-xs text-slate-300">
                  Reveals the direction of conventional induced current flowing through the arm.
                </div>
                <div className="bg-slate-950/80 p-2 rounded-lg border border-amber-500/20 text-xs font-mono text-amber-300">
                  {selectedArm === 'AB' ? armABData.currentDir : armCDData.currentDir}
                </div>
              </div>
            </div>

            {/* Dynamic Arm Analysis at Current Angle */}
            <div className="bg-slate-950/80 rounded-2xl p-4 border border-slate-800 space-y-3">
              <h4 className="text-sm font-bold text-slate-200 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-cyan-400" />
                Live Analysis at Current Position (θ = {thetaDegrees.toFixed(1)}°)
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                <div className="space-y-1.5">
                  <div className="text-slate-400 font-semibold">Conductor Arm Under Examination:</div>
                  <div className="font-bold text-amber-300 text-sm">
                    {selectedArm === 'AB' ? armABData.name : armCDData.name}
                  </div>
                  <p className="text-slate-400 leading-relaxed">
                    At θ = {thetaDegrees.toFixed(1)}°, the tangential velocity vector is directed at{' '}
                    <span className="font-mono text-emerald-400">
                      {selectedArm === 'AB' ? armABData.vySign : armCDData.vySign}
                    </span>. Since the magnetic field is horizontal (+x), the magnetic Lorentz force on free electrons is{' '}
                    <span className="font-mono text-cyan-300">F = -e(v × B)</span>.
                  </p>
                </div>

                <div className="space-y-2 bg-slate-900/60 p-3 rounded-xl border border-slate-800">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Arm Motion:</span>
                    <span className="font-mono text-emerald-400 font-bold">
                      {selectedArm === 'AB' ? armABData.motionDescription : armCDData.motionDescription}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Induced Current:</span>
                    <span className="font-mono text-amber-300 font-bold">
                      {selectedArm === 'AB' ? armABData.currentDir : armCDData.currentDir}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Contact Terminal Polarity:</span>
                    <span className="font-mono text-cyan-300 font-bold">
                      {selectedArm === 'AB' ? armABData.brushPolarity : armCDData.brushPolarity}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Why Slip Rings produce AC vs Split-Ring produces DC */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
              <div className="bg-emerald-950/20 border border-emerald-500/30 rounded-2xl p-4 space-y-2">
                <h4 className="text-sm font-bold text-emerald-300">Slip Rings Action (Continuous A.C.)</h4>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Slip ring 1 is permanently soldered to arm AB, and slip ring 2 is permanently connected to arm CD.
                  As arm AB completes its top-to-bottom half of the rotation, current flows out of brush 1 (+).
                  When arm AB moves upwards on the opposite side, current in AB reverses, causing brush 1 to become
                  negative (-). The output voltage alternates continuously!
                </p>
              </div>

              <div className="bg-cyan-950/20 border border-cyan-500/30 rounded-2xl p-4 space-y-2">
                <h4 className="text-sm font-bold text-cyan-300">Split-Ring Action (Mechanical Rectification)</h4>
                <p className="text-xs text-slate-400 leading-relaxed">
                  A split-ring commutator has two isolated half-cylinders with gaps. Exactly when the coil passes the
                  vertical neutral plane (where induced EMF drops to zero), the segments switch contact from one carbon
                  brush to the other. Consequently, brush 1 always connects to whichever arm is moving downwards,
                  keeping external current strictly unidirectional!
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 3: OSCILLOSCOPE WAVEFORM DISPLAY */}
      {activeTab === 'waveform' && (
        <div className="space-y-6">
          <div className="bg-slate-900/90 rounded-2xl p-6 border border-slate-800 space-y-5">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
              <div>
                <h3 className="text-xl font-bold text-slate-100 flex items-center gap-2">
                  <Activity className="w-5 h-5 text-emerald-400" />
                  Dual-Cycle Oscilloscope Waveform Display
                </h3>
                <p className="text-xs text-slate-400 mt-1">
                  Voltage versus coil orientation angle θ over two full mechanical cycles (0° to 720°).
                </p>
              </div>

              {/* Commutator Toggle inside Oscilloscope */}
              <div className="flex items-center gap-2 bg-slate-950 p-1.5 rounded-xl border border-slate-800">
                <button
                  onClick={() => setCommutatorType('slip_rings')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    commutatorType === 'slip_rings'
                      ? 'bg-emerald-500 text-slate-950 shadow-md shadow-emerald-500/20'
                      : 'text-slate-400 hover:text-white'
                  }`}
                >
                  AC Waveform (Slip Rings)
                </button>
                <button
                  onClick={() => setCommutatorType('split_ring')}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                    commutatorType === 'split_ring'
                      ? 'bg-amber-500 text-slate-950 shadow-md shadow-amber-500/20'
                      : 'text-slate-400 hover:text-white'
                  }`}
                >
                  DC Waveform (Split-Ring)
                </button>
              </div>
            </div>

            {/* Canvas Oscilloscope */}
            <div className="relative rounded-2xl overflow-hidden border border-slate-800 shadow-2xl">
              <canvas
                ref={oscCanvasRef}
                className="w-full h-64 sm:h-72 block bg-slate-950"
              />
            </div>

            {/* Five Key Orientation Points Matrix */}
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 pt-2">
              {[
                {
                  angle: '0°',
                  state: 'Vertical Plane',
                  emf: '0 V',
                  desc: 'Coil ⊥ B; arms move ∥ B (no cutting)',
                  color: 'text-slate-400',
                },
                {
                  angle: '90°',
                  state: 'Horizontal Plane',
                  emf: `+${peakEmf.toFixed(1)} V`,
                  desc: 'Coil ∥ B; arms cut lines at 90° (v ⊥ B)',
                  color: 'text-emerald-400',
                },
                {
                  angle: '180°',
                  state: 'Vertical Inverted',
                  emf: '0 V',
                  desc: 'Commutation plane; zero flux cutting',
                  color: 'text-slate-400',
                },
                {
                  angle: '270°',
                  state: 'Horizontal Inverted',
                  emf: commutatorType === 'slip_rings' ? `-${peakEmf.toFixed(1)} V` : `+${peakEmf.toFixed(1)} V`,
                  desc: commutatorType === 'slip_rings' ? 'Reversed polarity crest (-V_peak)' : 'Commutator rectifies to (+V_peak)',
                  color: commutatorType === 'slip_rings' ? 'text-rose-400' : 'text-amber-400',
                },
                {
                  angle: '360°',
                  state: '1 Full Turn',
                  emf: '0 V',
                  desc: 'Cycle complete, returns to start',
                  color: 'text-slate-400',
                },
              ].map((pt, idx) => (
                <div
                  key={idx}
                  className={`bg-slate-950/80 p-3 rounded-xl border ${
                    Math.abs(thetaDegrees - parseInt(pt.angle)) < 15
                      ? 'border-cyan-500/60 shadow-lg shadow-cyan-500/10'
                      : 'border-slate-800'
                  } space-y-1`}
                >
                  <div className="flex justify-between items-center">
                    <span className="text-xs font-bold text-amber-300 font-mono">{pt.angle}</span>
                    <span className={`text-xs font-extrabold font-mono ${pt.color}`}>{pt.emf}</span>
                  </div>
                  <div className="text-[11px] font-semibold text-slate-200">{pt.state}</div>
                  <div className="text-[10px] text-slate-500 leading-tight">{pt.desc}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* TAB 4: CURRICULUM THEORY & FORMULAS */}
      {activeTab === 'theory' && (
        <div className="space-y-6">
          <div className="bg-slate-900/90 rounded-2xl p-6 border border-slate-800 space-y-6">
            <div className="border-b border-slate-800/80 pb-4">
              <h3 className="text-xl font-bold text-slate-100 flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-cyan-400" />
                KCSE Physics Syllabus: Electromagnetic Induction (Form 4 Topic 5)
              </h3>
              <p className="text-xs text-slate-400 mt-1">
                Mathematical formulations, physical principles, and device comparison.
              </p>
            </div>

            {/* Core Equations Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-slate-950/70 p-4 rounded-xl border border-slate-800 space-y-2">
                <div className="text-xs font-bold text-cyan-400 uppercase tracking-wider">
                  1. Magnetic Flux Linked with Coil Loop
                </div>
                <div className="font-mono text-base font-extrabold text-white bg-slate-900 p-2.5 rounded-lg border border-slate-800">
                  Φ(t) = B · A · cos(ωt) = B · A · cos(θ)
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Where <span className="text-slate-200">B</span> is flux density (Tesla),{' '}
                  <span className="text-slate-200">A</span> is coil cross-sectional area (m²), and{' '}
                  <span className="text-slate-200">θ = ωt</span> is the orientation angle of the coil normal relative
                  to field lines.
                </p>
              </div>

              <div className="bg-slate-950/70 p-4 rounded-xl border border-slate-800 space-y-2">
                <div className="text-xs font-bold text-amber-400 uppercase tracking-wider">
                  2. Faraday’s Law of Electromagnetic Induction
                </div>
                <div className="font-mono text-base font-extrabold text-white bg-slate-900 p-2.5 rounded-lg border border-slate-800">
                  ε(t) = -N · (dΦ / dt) = N · B · A · ω · sin(ωt)
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">
                  The induced electromotive force equals the negative time rate of change of magnetic flux linkages.{' '}
                  <span className="text-amber-300 font-semibold">Peak E.M.F. ε₀ = N·B·A·ω</span>.
                </p>
              </div>

              <div className="bg-slate-950/70 p-4 rounded-xl border border-slate-800 space-y-2">
                <div className="text-xs font-bold text-emerald-400 uppercase tracking-wider">
                  3. Angular Velocity & Frequency
                </div>
                <div className="font-mono text-base font-extrabold text-white bg-slate-900 p-2.5 rounded-lg border border-slate-800">
                  ω = 2π·f = 2π · (RPM / 60) [rad/s]
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">
                  Doubling rotational speed (RPM) doubles both the frequency <span className="text-slate-200">f</span>{' '}
                  and the peak output voltage <span className="text-emerald-300 font-semibold">ε₀</span>!
                </p>
              </div>

              <div className="bg-slate-950/70 p-4 rounded-xl border border-slate-800 space-y-2">
                <div className="text-xs font-bold text-purple-400 uppercase tracking-wider">
                  4. Root-Mean-Square (R.M.S.) Voltage & Power
                </div>
                <div className="font-mono text-base font-extrabold text-white bg-slate-900 p-2.5 rounded-lg border border-slate-800">
                  V_rms = ε₀ / √2 ≈ 0.7071 · ε₀ , P_avg = V_rms² / R
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">
                  The steady direct current voltage that delivers the equivalent heating power to a resistive load as
                  the alternating current.
                </p>
              </div>
            </div>

            {/* Comparison Table: AC Generator vs DC Dynamo vs DC Motor */}
            <div className="space-y-3 pt-2">
              <h4 className="text-sm font-bold text-slate-200">
                Comparative Summary: AC Generator vs DC Dynamo vs DC Motor
              </h4>
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs border border-slate-800 rounded-xl overflow-hidden">
                  <thead className="bg-slate-950 text-slate-400 border-b border-slate-800">
                    <tr>
                      <th className="p-3">Feature</th>
                      <th className="p-3">A.C. Generator (Alternator)</th>
                      <th className="p-3">D.C. Generator (Dynamo)</th>
                      <th className="p-3">D.C. Electric Motor</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800 bg-slate-900/50">
                    <tr>
                      <td className="p-3 font-semibold text-slate-300">Energy Conversion</td>
                      <td className="p-3 text-cyan-300">Mechanical ➔ Electrical (AC)</td>
                      <td className="p-3 text-amber-300">Mechanical ➔ Electrical (DC)</td>
                      <td className="p-3 text-emerald-300">Electrical ➔ Mechanical</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-semibold text-slate-300">Commutator Hardware</td>
                      <td className="p-3">Two continuous slip rings</td>
                      <td className="p-3">Split-ring commutator</td>
                      <td className="p-3">Split-ring commutator</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-semibold text-slate-300">Governing Rule</td>
                      <td className="p-3">Fleming’s Right-Hand Rule</td>
                      <td className="p-3">Fleming’s Right-Hand Rule</td>
                      <td className="p-3">Fleming’s Left-Hand Rule</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-semibold text-slate-300">Output Waveform</td>
                      <td className="p-3 text-cyan-300">Smooth Sinusoid (ε₀ sin ωt)</td>
                      <td className="p-3 text-amber-300">Pulsating Half-Sines (|ε₀ sin ωt|)</td>
                      <td className="p-3 text-emerald-300">Mechanical Torque (τ = N·B·I·A)</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-semibold text-slate-300">Real-World Examples</td>
                      <td className="p-3">Hydroelectric turbines (KenGen)</td>
                      <td className="p-3">Bicycle dynamos, car alternators</td>
                      <td className="p-3">Electric trains, starter motors</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 5: KCSE EXAM CHALLENGES */}
      {activeTab === 'kcse' && (
        <div className="space-y-6">
          <div className="bg-slate-900/90 rounded-2xl p-6 border border-slate-800 space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
              <div>
                <h3 className="text-xl font-bold text-slate-100 flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-amber-400" />
                  KCSE Physics Exam Practice Questions
                </h3>
                <p className="text-xs text-slate-400 mt-1">
                  Test your mastery of AC/DC generator mathematics and physical mechanics.
                </p>
              </div>

              {/* Problem Selector Pills */}
              <div className="flex items-center gap-2">
                {KCSE_PROBLEMS.map((prob, idx) => (
                  <button
                    key={prob.id}
                    onClick={() => {
                      setActiveProblemIdx(idx);
                      setUserAnswer('');
                      setPracticeStatus(null);
                      setShowSolution(false);
                    }}
                    className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                      activeProblemIdx === idx
                        ? 'bg-amber-500 text-slate-950 shadow-md shadow-amber-500/20'
                        : 'bg-slate-950 text-slate-400 hover:text-white border border-slate-800'
                    }`}
                  >
                    Question {idx + 1}
                  </button>
                ))}
              </div>
            </div>

            {/* Current Problem Card */}
            {(() => {
              const currentProb = KCSE_PROBLEMS[activeProblemIdx];
              return (
                <div className="space-y-5">
                  <div className="bg-slate-950/80 p-5 rounded-2xl border border-slate-800 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-amber-400 uppercase tracking-wider">
                        {currentProb.title}
                      </span>
                      <span className="text-[10px] bg-slate-800 text-slate-300 px-2 py-0.5 rounded font-mono">
                        KCSE Standard
                      </span>
                    </div>

                    <p className="text-sm text-slate-200 leading-relaxed">{currentProb.question}</p>

                    <div className="flex items-center gap-2 pt-2">
                      <button
                        onClick={() => setShowSolution(!showSolution)}
                        className="text-xs text-cyan-400 hover:text-cyan-300 flex items-center gap-1 font-medium transition-colors"
                      >
                        <HelpCircle className="w-3.5 h-3.5" />
                        {showSolution ? 'Hide Hint & Solution' : 'Show Hint & Solution'}
                      </button>
                    </div>

                    {showSolution && (
                      <div className="mt-3 p-4 rounded-xl bg-cyan-950/20 border border-cyan-500/30 text-xs space-y-2">
                        <div className="font-semibold text-cyan-300">Exam Hint:</div>
                        <p className="text-slate-300">{currentProb.hint}</p>
                        <div className="font-semibold text-cyan-300 pt-1">Step-by-Step Marking Scheme:</div>
                        <ol className="list-decimal list-inside space-y-1 text-slate-400 font-mono text-[11px]">
                          {currentProb.solutionSteps.map((step, sIdx) => (
                            <li key={sIdx}>{step}</li>
                          ))}
                        </ol>
                      </div>
                    )}
                  </div>

                  {/* Answer Input Section */}
                  <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
                    <div className="relative flex-1 max-w-xs">
                      <input
                        type="number"
                        step="any"
                        placeholder={`Enter value in ${currentProb.unit}`}
                        value={userAnswer}
                        onChange={(e) => {
                          setUserAnswer(e.target.value);
                          setPracticeStatus(null);
                        }}
                        className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-slate-100 placeholder-slate-500 text-sm focus:outline-none focus:border-cyan-500 font-mono"
                      />
                      <span className="absolute right-3 top-2.5 text-xs text-slate-500 font-mono pointer-events-none">
                        {currentProb.unit}
                      </span>
                    </div>

                    <button
                      onClick={handleCheckAnswer}
                      className="px-5 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs transition-all shadow-md shadow-cyan-500/20 flex items-center gap-2"
                    >
                      Verify Answer
                    </button>
                  </div>

                  {/* Feedback Banner */}
                  {practiceStatus === 'correct' && (
                    <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 flex items-center gap-3 text-emerald-300 text-xs">
                      <CheckCircle2 className="w-5 h-5 flex-shrink-0 text-emerald-400" />
                      <div>
                        <div className="font-bold text-emerald-200">Excellent! Correct Answer.</div>
                        <div>
                          Your answer matches the theoretical calculation ({currentProb.target} {currentProb.unit}).
                        </div>
                      </div>
                    </div>
                  )}

                  {practiceStatus === 'incorrect' && (
                    <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/30 flex items-center gap-3 text-rose-300 text-xs">
                      <XCircle className="w-5 h-5 flex-shrink-0 text-rose-400" />
                      <div>
                        <div className="font-bold text-rose-200">Not Quite Correct</div>
                        <div>
                          Check your unit conversions or formula substitutions. Click "Show Hint & Solution" for help.
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              );
            })()}
          </div>
        </div>
      )}
    </div>
  );
}
