import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import {
  Eye,
  Sliders,
  RotateCcw,
  Sparkles,
  CheckCircle2,
  XCircle,
  HelpCircle,
  Info,
  Maximize2,
  Play,
  Pause,
  Award,
  BookOpen,
  ArrowRight,
  Glasses,
  Zap,
  Layers,
  ChevronRight,
  Compass
} from 'lucide-react';

// Anatomical Hotspots on Sagittal Cross Section of Human Eye
const ANATOMY_PINS = [
  {
    id: 'cornea',
    name: 'Cornea',
    x: 120,
    y: 200,
    shortDesc: 'Transparent front dome',
    fullDesc:
      'Refracts approximately 70-80% of incident light into the eye. Avascular, bathed in aqueous humour and tear film.'
  },
  {
    id: 'ciliary_body',
    name: 'Ciliary Body & Muscle',
    x: 235,
    y: 110,
    shortDesc: 'Smooth muscle ring',
    fullDesc:
      'Alters lens curvature during accommodation. Contracts for near vision (relaxing zonules) and relaxes for distant vision.'
  },
  {
    id: 'suspensory_ligaments',
    name: 'Suspensory Ligaments (Zonules)',
    x: 235,
    y: 155,
    shortDesc: 'Zonular tension fibers',
    fullDesc:
      'Connect ciliary body to lens capsule. Tightened when ciliary muscle relaxes, pulling the elastic crystalline lens flat.'
  },
  {
    id: 'crystalline_lens',
    name: 'Crystalline Lens',
    x: 240,
    y: 200,
    shortDesc: 'Biconvex flexible lens',
    fullDesc:
      'Elastic, transparent protein structure providing fine optical focusing (accommodation) to form inverted images on retina.'
  },
  {
    id: 'iris_pupil',
    name: 'Iris & Pupil',
    x: 215,
    y: 165,
    shortDesc: 'Aperture diaphragm',
    fullDesc:
      'Pigmented circular and radial smooth muscles regulating the diameter of the central opening (pupil) to control light flux.'
  },
  {
    id: 'retina',
    name: 'Retina',
    x: 520,
    y: 130,
    shortDesc: 'Photoreceptive inner coat',
    fullDesc:
      'Sensory layer composed of rod cells (scotopic, peripheral, black/white) and cone cells (photopic, acute, trichromatic colour).'
  },
  {
    id: 'fovea_centralis',
    name: 'Fovea Centralis (Yellow Spot)',
    x: 550,
    y: 200,
    shortDesc: 'Highest visual acuity',
    fullDesc:
      'Shallow retinal depression packed exclusively with cones (1:1 ganglion wiring) where visual details are resolved with peak sharpness.'
  },
  {
    id: 'blind_spot',
    name: 'Blind Spot (Optic Disc)',
    x: 535,
    y: 265,
    shortDesc: 'No photoreceptor cells',
    fullDesc:
      'Area where axons of ganglion cells coalesce to form the optic nerve. No rods or cones; insensitive to incident rays.'
  },
  {
    id: 'optic_nerve',
    name: 'Optic Nerve (Cranial II)',
    x: 620,
    y: 280,
    shortDesc: 'Neural transmission cable',
    fullDesc:
      'Transmits sensory electrical impulses generated by photoreceptors directly to the visual cortex of the occipital cerebral lobe.'
  }
];

// KCSE Exam Form 4 Practice Questions
const KCSE_QUIZ_QUESTIONS = [
  {
    id: 'q1',
    question:
      'When a student shifts gaze from reading a textbook (25 cm) to a distant tree on the horizon (>6 m), what muscular and ligamentous changes occur in the eye?',
    options: [
      { text: 'Ciliary muscles contract, suspensory ligaments tighten, lens bulges', correct: false },
      { text: 'Ciliary muscles relax, suspensory ligaments tighten, lens becomes thinner', correct: true },
      { text: 'Ciliary muscles contract, suspensory ligaments slacken, lens flattens', correct: false },
      { text: 'Ciliary muscles relax, suspensory ligaments slacken, lens thickens', correct: false }
    ],
    explanation:
      'For distant vision, ciliary muscles relax, expanding the ring diameter. This increases tension on suspensory ligaments, stretching the crystalline lens thinner/flatter.'
  },
  {
    id: 'q2',
    question:
      'In Myopia (short-sightedness), light rays from a distant object focus in front of the retina. Which anatomical cause and corrective lens are correct?',
    options: [
      { text: 'Eyeball too short; corrected using convex (converging) lens', correct: false },
      { text: 'Eyeball too long or lens too convex; corrected using concave (diverging) lens', correct: true },
      { text: 'Loss of lens elasticity; corrected using cylindrical lens', correct: false },
      { text: 'Corneal irregularity; corrected using bifocal lens', correct: false }
    ],
    explanation:
      'Myopia occurs due to an elongated eyeball or excessive lens refractive power. Rays converge before reaching the retina; a concave (diverging) lens spreads rays before entering.'
  },
  {
    id: 'q3',
    question:
      'Why does an image falling upon the optic disc (blind spot) produce no sensory perception?',
    options: [
      { text: 'Aqueous humour cannot reach this zone', correct: false },
      { text: 'There are no rod or cone photoreceptor cells present at the nerve exit', correct: true },
      { text: 'Choroid layer absorbs all light before reaching it', correct: false },
      { text: 'It contains only inhibitory neurotransmitters', correct: false }
    ],
    explanation:
      'The optic disc is the anatomical point of exit for optic nerve fibres and retinal blood vessels. It lacks both rods and cones, making it totally insensitive to light.'
  },
  {
    id: 'q4',
    question:
      'Presbyopia is a common condition among elderly individuals. What is the physiological basis of this defect?',
    options: [
      { text: 'Gradual loss of crystalline lens elasticity and ciliary muscle weakening', correct: true },
      { text: 'Accumulation of opaque calcium salts in the aqueous humor', correct: false },
      { text: 'Uneven curvature of the corneal surface in perpendicular meridians', correct: false },
      { text: 'Elongation of the anteroposterior diameter of the eyeball', correct: false }
    ],
    explanation:
      'Presbyopia results from age-related sclerosis and hardening of the lens alongside reduced ciliary muscle tone, impeding near-accommodation (corrected by convex reading lenses).'
  }
];

export default function HumanEyeAccommodationDefectsSim({ config = {}, onTelemetry }) {
  // Mode selection: 'accommodation' | 'defects' | 'interactive_pins'
  const [activeTab, setActiveTab] = useState('accommodation');

  // Accommodation states
  const [objectDistance, setObjectDistance] = useState(6.0); // metres (0.25m to 10m)
  const [isAccommodatingAuto, setIsAccommodatingAuto] = useState(false);

  // Vision defects states
  const [selectedDefect, setSelectedDefect] = useState('emmetropia'); // 'emmetropia' | 'myopia' | 'hypermetropia' | 'astigmatism' | 'presbyopia'
  const [isCorrectionApplied, setIsCorrectionApplied] = useState(false);
  const [eyeballElongation, setEyeballElongation] = useState(0); // -40 to +40 px

  // Anatomical Pin inspection
  const [activePinId, setActivePinId] = useState(null);

  // KCSE Quiz State
  const [quizIndex, setQuizIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState(null);
  const [quizScore, setQuizScore] = useState(0);
  const [quizSubmitted, setQuizSubmitted] = useState(false);
  const [quizComplete, setQuizComplete] = useState(false);

  // Canvas refs
  const canvasRef = useRef(null);

  // Auto-accommodation animation loop
  useEffect(() => {
    let animId;
    if (isAccommodatingAuto) {
      let forward = false;
      const step = () => {
        setObjectDistance((prev) => {
          if (prev <= 0.3) forward = true;
          if (prev >= 7.5) forward = false;
          return forward ? prev + 0.06 : prev - 0.06;
        });
        animId = requestAnimationFrame(step);
      };
      animId = requestAnimationFrame(step);
    }
    return () => {
      if (animId) cancelAnimationFrame(animId);
    };
  }, [isAccommodatingAuto]);

  // Sync defect default eyeball elongation
  useEffect(() => {
    if (selectedDefect === 'myopia') {
      setEyeballElongation(35);
    } else if (selectedDefect === 'hypermetropia') {
      setEyeballElongation(-30);
    } else {
      setEyeballElongation(0);
    }
    setIsCorrectionApplied(false);
  }, [selectedDefect]);

  // Accommodation calculated factors
  // Far object (>= 6m): distance=6 -> ciliary muscle relaxed (0%), zonules taut (100%), lens thin (width: 16px)
  // Near object (0.25m): distance=0.25 -> ciliary muscle contracted (100%), zonules slack (0%), lens bulging (width: 32px)
  const accommodationFactor = useMemo(() => {
    // 0 is near (0.25m), 1 is far (6m+)
    const clamped = Math.max(0.25, Math.min(6.0, objectDistance));
    return (clamped - 0.25) / (6.0 - 0.25);
  }, [objectDistance]);

  const ciliaryMuscleTone = (1 - accommodationFactor) * 100; // % contracted
  const zonuleTension = accommodationFactor * 100; // % taut
  const lensThicknessMm = 3.6 + (1 - accommodationFactor) * 1.2; // 3.6mm (thin) to 4.8mm (thick)
  const focalPowerDiopters = 58.0 + (1 - accommodationFactor) * 12.0; // 58 D to 70 D

  // Main Drawing Effect
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    const width = canvas.width;
    const height = canvas.height;

    ctx.clearRect(0, 0, width, height);

    // Coordinate Anchors
    const eyeCenter = { x: 380, y: 220 };
    const radiusXBase = 160;
    const radiusYBase = 150;
    const elongation = activeTab === 'defects' ? eyeballElongation : 0;
    const radiusX = radiusXBase + elongation;
    const radiusY = radiusYBase;

    // Outer Glow / Dark Background Grid
    ctx.save();
    ctx.strokeStyle = 'rgba(51, 65, 85, 0.3)';
    ctx.lineWidth = 1;
    for (let x = 0; x < width; x += 40) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, height);
      ctx.stroke();
    }
    for (let y = 0; y < height; y += 40) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
      ctx.stroke();
    }
    ctx.restore();

    // 1. Sclera (Outer tough fibrous white protective coat)
    ctx.save();
    ctx.beginPath();
    ctx.ellipse(eyeCenter.x, eyeCenter.y, radiusX, radiusY, 0, 0, Math.PI * 2);
    ctx.fillStyle = '#1e293b';
    ctx.shadowColor = '#38bdf8';
    ctx.shadowBlur = 12;
    ctx.fill();
    ctx.lineWidth = 6;
    ctx.strokeStyle = '#94a3b8'; // Sclera silvery white
    ctx.stroke();
    ctx.restore();

    // 2. Choroid (Middle vascular pigmented layer)
    ctx.save();
    ctx.beginPath();
    ctx.ellipse(eyeCenter.x, eyeCenter.y, radiusX - 6, radiusY - 6, 0, 0, Math.PI * 2);
    ctx.lineWidth = 4;
    ctx.strokeStyle = '#7c2d12'; // Dark melanin-pigmented vascular choroid
    ctx.stroke();
    ctx.restore();

    // 3. Retina (Inner photoreceptive sensory layer)
    ctx.save();
    ctx.beginPath();
    // Arc across back 70% of eyeball
    ctx.arc(eyeCenter.x, eyeCenter.y, radiusX - 11, -Math.PI * 0.65, Math.PI * 0.65, false);
    ctx.lineWidth = 5;
    ctx.strokeStyle = '#f59e0b'; // Amber retinal neural network
    ctx.stroke();
    ctx.restore();

    // Fovea Centralis Pit on back wall
    const foveaX = eyeCenter.x + radiusX - 12;
    const foveaY = eyeCenter.y;
    ctx.save();
    ctx.beginPath();
    ctx.arc(foveaX, foveaY, 7, 0, Math.PI * 2);
    ctx.fillStyle = '#fbbf24';
    ctx.shadowColor = '#f59e0b';
    ctx.shadowBlur = 10;
    ctx.fill();
    ctx.restore();

    // Blind Spot (Optic Disc) gap slightly below fovea
    const blindSpotY = eyeCenter.y + 60;
    const blindSpotX = eyeCenter.x + Math.sqrt(Math.max(0, radiusX * radiusX * (1 - (60 * 60) / (radiusY * radiusY)))) - 12;
    ctx.save();
    ctx.beginPath();
    ctx.ellipse(blindSpotX, blindSpotY, 10, 16, 0.2, 0, Math.PI * 2);
    ctx.fillStyle = '#0f172a'; // Gap in retina
    ctx.fill();
    ctx.restore();

    // Optic Nerve Trunk radiating outwards
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(blindSpotX, blindSpotY - 14);
    ctx.bezierCurveTo(blindSpotX + 40, blindSpotY - 10, blindSpotX + 60, blindSpotY + 5, blindSpotX + 110, blindSpotY + 15);
    ctx.lineTo(blindSpotX + 105, blindSpotY + 38);
    ctx.bezierCurveTo(blindSpotX + 55, blindSpotY + 28, blindSpotX + 35, blindSpotY + 18, blindSpotX, blindSpotY + 14);
    ctx.closePath();
    ctx.fillStyle = '#d97706';
    ctx.fill();
    ctx.strokeStyle = '#b45309';
    ctx.lineWidth = 2;
    ctx.stroke();
    ctx.restore();

    // 4. Cornea (Anterior transparent bulging curve)
    const corneaFrontX = eyeCenter.x - radiusX - 15;
    const corneaTopY = eyeCenter.y - 85;
    const corneaBottomY = eyeCenter.y + 85;

    ctx.save();
    ctx.beginPath();
    ctx.moveTo(eyeCenter.x - radiusX + 8, corneaTopY);
    ctx.bezierCurveTo(corneaFrontX - 35, corneaTopY + 30, corneaFrontX - 35, corneaBottomY - 30, eyeCenter.x - radiusX + 8, corneaBottomY);
    ctx.lineWidth = 5;
    ctx.strokeStyle = '#38bdf8'; // Sky blue transparent cornea
    ctx.shadowColor = '#0284c7';
    ctx.shadowBlur = 8;
    ctx.stroke();
    ctx.restore();

    // Anterior Chamber with Aqueous Humour
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(eyeCenter.x - radiusX + 8, corneaTopY);
    ctx.bezierCurveTo(corneaFrontX - 35, corneaTopY + 30, corneaFrontX - 35, corneaBottomY - 30, eyeCenter.x - radiusX + 8, corneaBottomY);
    ctx.lineTo(eyeCenter.x - 110, eyeCenter.y + 70);
    ctx.lineTo(eyeCenter.x - 110, eyeCenter.y - 70);
    ctx.closePath();
    ctx.fillStyle = 'rgba(56, 189, 248, 0.08)';
    ctx.fill();
    ctx.restore();

    // 5. Ciliary Body and Muscle Rings (Upper and Lower)
    const ciliaryBulge = activeTab === 'accommodation' ? (1 - accommodationFactor) * 8 : 4;
    const ciliaryUpperX = eyeCenter.x - 115;
    const ciliaryUpperY = eyeCenter.y - 92;
    const ciliaryLowerX = eyeCenter.x - 115;
    const ciliaryLowerY = eyeCenter.y + 92;

    ctx.save();
    ctx.fillStyle = '#dc2626'; // Reddish vascular muscular tissue
    // Upper ciliary body
    ctx.beginPath();
    ctx.ellipse(ciliaryUpperX, ciliaryUpperY + ciliaryBulge, 18 + ciliaryBulge * 0.5, 14 + ciliaryBulge, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = '#991b1b';
    ctx.lineWidth = 2;
    ctx.stroke();

    // Lower ciliary body
    ctx.beginPath();
    ctx.ellipse(ciliaryLowerX, ciliaryLowerY - ciliaryBulge, 18 + ciliaryBulge * 0.5, 14 + ciliaryBulge, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = '#991b1b';
    ctx.stroke();
    ctx.restore();

    // 6. Iris (Pigmented aperture blades)
    ctx.save();
    ctx.fillStyle = '#0284c7'; // Blue/hazel iris
    ctx.strokeStyle = '#0369a1';
    ctx.lineWidth = 2;
    // Top iris blade
    ctx.beginPath();
    ctx.moveTo(ciliaryUpperX - 4, ciliaryUpperY + 12 + ciliaryBulge);
    ctx.lineTo(eyeCenter.x - 128, eyeCenter.y - 32);
    ctx.lineTo(eyeCenter.x - 122, eyeCenter.y - 32);
    ctx.lineTo(ciliaryUpperX + 8, ciliaryUpperY + 10 + ciliaryBulge);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();

    // Bottom iris blade
    ctx.beginPath();
    ctx.moveTo(ciliaryLowerX - 4, ciliaryLowerY - 12 - ciliaryBulge);
    ctx.lineTo(eyeCenter.x - 128, eyeCenter.y + 32);
    ctx.lineTo(eyeCenter.x - 122, eyeCenter.y + 32);
    ctx.lineTo(ciliaryLowerX + 8, ciliaryLowerY - 10 - ciliaryBulge);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    ctx.restore();

    // 7. Crystalline Lens (Dynamic biconvex model)
    const lensCenter = { x: eyeCenter.x - 105, y: eyeCenter.y };
    const lensHalfHeight = 65;
    // When accommodating near: lensBulge goes up (12 -> 24)
    const lensThickness =
      activeTab === 'accommodation' ? 12 + (1 - accommodationFactor) * 16 : selectedDefect === 'myopia' ? 22 : 14;

    ctx.save();
    ctx.beginPath();
    // Front curve
    ctx.moveTo(lensCenter.x, lensCenter.y - lensHalfHeight);
    ctx.quadraticCurveTo(lensCenter.x - lensThickness, lensCenter.y, lensCenter.x, lensCenter.y + lensHalfHeight);
    // Back curve
    ctx.quadraticCurveTo(lensCenter.x + lensThickness * 1.15, lensCenter.y, lensCenter.x, lensCenter.y - lensHalfHeight);
    ctx.fillStyle = 'rgba(224, 242, 254, 0.45)';
    ctx.shadowColor = '#38bdf8';
    ctx.shadowBlur = 10;
    ctx.fill();
    ctx.strokeStyle = '#7dd3fc';
    ctx.lineWidth = 2.5;
    ctx.stroke();
    ctx.restore();

    // 8. Suspensory Ligaments (Zonules of Zinn)
    // When accommodation is high, zonules slacken (dashed or wavy)
    const isSlack = activeTab === 'accommodation' && accommodationFactor < 0.35;
    ctx.save();
    ctx.strokeStyle = isSlack ? '#94a3b8' : '#e2e8f0';
    ctx.lineWidth = isSlack ? 1.5 : 2.5;
    if (isSlack) ctx.setLineDash([4, 3]);

    // Upper zonules (3 strand fan)
    for (let i = -1; i <= 1; i++) {
      ctx.beginPath();
      ctx.moveTo(ciliaryUpperX + i * 5, ciliaryUpperY + 12 + ciliaryBulge);
      ctx.lineTo(lensCenter.x + i * 4, lensCenter.y - lensHalfHeight + 4);
      ctx.stroke();
    }
    // Lower zonules
    for (let i = -1; i <= 1; i++) {
      ctx.beginPath();
      ctx.moveTo(ciliaryLowerX + i * 5, ciliaryLowerY - 12 - ciliaryBulge);
      ctx.lineTo(lensCenter.x + i * 4, lensCenter.y + lensHalfHeight - 4);
      ctx.stroke();
    }
    ctx.restore();

    // 9. Vitreous Humour Chamber Indicator
    ctx.save();
    ctx.font = '11px sans-serif';
    ctx.fillStyle = 'rgba(148, 163, 184, 0.35)';
    ctx.fillText('Vitreous Body (Gelatinous)', eyeCenter.x + 30, eyeCenter.y - 60);
    ctx.fillText('Maintains Globular Shape', eyeCenter.x + 30, eyeCenter.y - 44);
    ctx.restore();

    // ==========================================
    // 10. LIGHT RAY TRACING ENGINE
    // ==========================================
    const objectOriginX = activeTab === 'accommodation' ? Math.max(20, 260 - (objectDistance / 6.0) * 230) : 40;
    const objectHeight = 65;
    const topObjY = eyeCenter.y - objectHeight;
    const btmObjY = eyeCenter.y + objectHeight;

    // Object Arrow on the left
    ctx.save();
    ctx.strokeStyle = '#22c55e'; // Green object arrow
    ctx.lineWidth = 4;
    ctx.beginPath();
    ctx.moveTo(objectOriginX, btmObjY);
    ctx.lineTo(objectOriginX, topObjY);
    ctx.stroke();
    // Arrow head
    ctx.beginPath();
    ctx.moveTo(objectOriginX - 7, topObjY + 12);
    ctx.lineTo(objectOriginX, topObjY);
    ctx.lineTo(objectOriginX + 7, topObjY + 12);
    ctx.fillStyle = '#22c55e';
    ctx.fill();
    ctx.font = 'bold 12px monospace';
    ctx.fillText(`Object (${activeTab === 'accommodation' ? `${objectDistance.toFixed(1)}m` : 'Target'})`, objectOriginX - 10, topObjY - 10);
    ctx.restore();

    // Corrective Glass Lens (if in defects tab and enabled)
    const glassLensX = eyeCenter.x - radiusX - 45;
    if (activeTab === 'defects' && isCorrectionApplied && selectedDefect !== 'emmetropia') {
      ctx.save();
      ctx.fillStyle = 'rgba(167, 139, 250, 0.25)';
      ctx.strokeStyle = '#a78bfa';
      ctx.lineWidth = 2.5;
      if (selectedDefect === 'myopia') {
        // Concave diverging spectacle lens
        ctx.beginPath();
        ctx.moveTo(glassLensX - 8, eyeCenter.y - 75);
        ctx.quadraticCurveTo(glassLensX + 4, eyeCenter.y, glassLensX - 8, eyeCenter.y + 75);
        ctx.lineTo(glassLensX + 8, eyeCenter.y + 75);
        ctx.quadraticCurveTo(glassLensX - 4, eyeCenter.y, glassLensX + 8, eyeCenter.y - 75);
        ctx.closePath();
        ctx.fill();
        ctx.stroke();
        ctx.fillStyle = '#c4b5fd';
        ctx.font = '10px sans-serif';
        ctx.fillText('Concave Spec', glassLensX - 32, eyeCenter.y - 82);
      } else if (selectedDefect === 'hypermetropia' || selectedDefect === 'presbyopia') {
        // Convex converging spectacle lens
        ctx.beginPath();
        ctx.ellipse(glassLensX, eyeCenter.y, 8, 75, 0, 0, Math.PI * 2);
        ctx.fill();
        ctx.stroke();
        ctx.fillStyle = '#c4b5fd';
        ctx.font = '10px sans-serif';
        ctx.fillText('Convex Spec', glassLensX - 30, eyeCenter.y - 82);
      } else if (selectedDefect === 'astigmatism') {
        // Cylindrical lens
        ctx.beginPath();
        ctx.roundRect(glassLensX - 7, eyeCenter.y - 75, 14, 150, [4]);
        ctx.fill();
        ctx.stroke();
        ctx.fillStyle = '#c4b5fd';
        ctx.font = '10px sans-serif';
        ctx.fillText('Cylindrical Spec', glassLensX - 36, eyeCenter.y - 82);
      }
      ctx.restore();
    }

    // Determine Focal Point X
    let focusX = foveaX; // Default exact fovea hit
    if (activeTab === 'accommodation') {
      // In accommodation mode, focus hits retina unless distance < 0.25 (near point blur)
      if (objectDistance < 0.25) {
        focusX = foveaX + 25; // under-accommodated blur behind retina
      } else {
        focusX = foveaX;
      }
    } else if (activeTab === 'defects') {
      if (selectedDefect === 'emmetropia') {
        focusX = foveaX;
      } else if (selectedDefect === 'myopia') {
        // Focuses in front of retina
        focusX = isCorrectionApplied ? foveaX : foveaX - 55;
      } else if (selectedDefect === 'hypermetropia') {
        // Focuses behind retina
        focusX = isCorrectionApplied ? foveaX : foveaX + 48;
      } else if (selectedDefect === 'presbyopia') {
        focusX = isCorrectionApplied ? foveaX : foveaX + 42;
      } else if (selectedDefect === 'astigmatism') {
        // Astigmatism has split focal lines
        focusX = isCorrectionApplied ? foveaX : foveaX - 25;
      }
    }

    // Trace Ray Bundles (Top object point, Center optical axis, Bottom object point)
    ctx.save();
    ctx.lineWidth = 2;

    const renderRayBundle = (color, startY, pupilEntryY) => {
      ctx.strokeStyle = color;
      ctx.beginPath();
      ctx.moveTo(objectOriginX, startY);

      // If corrective spectacle lens exists, refract slightly first
      if (activeTab === 'defects' && isCorrectionApplied && selectedDefect !== 'emmetropia') {
        const specBend = selectedDefect === 'myopia' ? (startY < eyeCenter.y ? -8 : 8) : startY < eyeCenter.y ? 8 : -8;
        ctx.lineTo(glassLensX, startY + specBend * 0.3);
        ctx.lineTo(lensCenter.x - 10, pupilEntryY);
      } else {
        ctx.lineTo(lensCenter.x - 10, pupilEntryY);
      }

      // Through crystalline lens
      ctx.lineTo(lensCenter.x + 10, pupilEntryY);

      // Converging onto focusX
      ctx.lineTo(focusX, eyeCenter.y);

      // If focus is before retina (myopia uncorrected), continue past focal point to strike retina blurred
      if (focusX < foveaX) {
        const overshotSlope = (eyeCenter.y - pupilEntryY) / (focusX - (lensCenter.x + 10));
        const retinaHitY = eyeCenter.y + overshotSlope * (foveaX - focusX);
        ctx.lineTo(foveaX, retinaHitY);
      }
      ctx.stroke();
    };

    // Parallel and oblique rays from top and bottom
    renderRayBundle('rgba(239, 68, 68, 0.85)', topObjY, eyeCenter.y - 25);
    renderRayBundle('rgba(59, 130, 246, 0.85)', eyeCenter.y, eyeCenter.y);
    renderRayBundle('rgba(234, 179, 8, 0.85)', btmObjY, eyeCenter.y + 25);

    // Focal Point Marker
    ctx.beginPath();
    ctx.arc(focusX, eyeCenter.y, 5, 0, Math.PI * 2);
    ctx.fillStyle = focusX === foveaX ? '#22c55e' : '#ef4444';
    ctx.fill();
    ctx.shadowColor = focusX === foveaX ? '#22c55e' : '#ef4444';
    ctx.shadowBlur = 8;
    ctx.stroke();

    // Text status on retina focal sharpness
    ctx.font = 'bold 11px sans-serif';
    if (Math.abs(focusX - foveaX) < 4) {
      ctx.fillStyle = '#22c55e';
      ctx.fillText('Sharp Image (On Fovea)', foveaX - 55, eyeCenter.y + 24);
    } else if (focusX < foveaX) {
      ctx.fillStyle = '#ef4444';
      ctx.fillText('Focused In Front (Blurred on Retina)', focusX - 70, eyeCenter.y - 15);
    } else {
      ctx.fillStyle = '#ef4444';
      ctx.fillText('Virtual Focus Behind Retina', focusX - 50, eyeCenter.y - 15);
    }
    ctx.restore();

    // Inverted Real Image on Retina representation
    if (Math.abs(focusX - foveaX) < 4) {
      ctx.save();
      ctx.strokeStyle = '#22c55e';
      ctx.lineWidth = 3;
      ctx.beginPath();
      // Inverted smaller image
      const imgHeight = 28;
      ctx.moveTo(foveaX, eyeCenter.y - imgHeight);
      ctx.lineTo(foveaX, eyeCenter.y + imgHeight);
      ctx.stroke();
      // Arrow head pointing DOWN (Inverted!)
      ctx.beginPath();
      ctx.moveTo(foveaX - 5, eyeCenter.y + imgHeight - 8);
      ctx.lineTo(foveaX, eyeCenter.y + imgHeight);
      ctx.lineTo(foveaX + 5, eyeCenter.y + imgHeight - 8);
      ctx.fillStyle = '#22c55e';
      ctx.fill();
      ctx.font = '10px monospace';
      ctx.fillText('Real & Inverted', foveaX - 42, eyeCenter.y + imgHeight + 14);
      ctx.restore();
    }

    // Astigmatism split focal plane hint
    if (activeTab === 'defects' && selectedDefect === 'astigmatism' && !isCorrectionApplied) {
      ctx.save();
      ctx.strokeStyle = 'rgba(244, 63, 94, 0.7)';
      ctx.setLineDash([3, 3]);
      ctx.beginPath();
      ctx.moveTo(lensCenter.x + 10, eyeCenter.y - 25);
      ctx.lineTo(foveaX + 25, eyeCenter.y);
      ctx.stroke();
      ctx.font = '10px sans-serif';
      ctx.fillStyle = '#f43f5e';
      ctx.fillText('Vertical Meridian Focus', foveaX - 50, eyeCenter.y + 42);
      ctx.restore();
    }

    // 11. Render Anatomical Interactive Pins (if in anatomical tab)
    if (activeTab === 'interactive_pins') {
      ANATOMY_PINS.forEach((pin) => {
        const isSelected = activePinId === pin.id;
        ctx.save();
        ctx.beginPath();
        ctx.arc(pin.x, pin.y, isSelected ? 9 : 6, 0, Math.PI * 2);
        ctx.fillStyle = isSelected ? '#38bdf8' : '#e0e7ff';
        ctx.shadowColor = isSelected ? '#0284c7' : '#6366f1';
        ctx.shadowBlur = isSelected ? 14 : 6;
        ctx.fill();
        ctx.strokeStyle = '#0f172a';
        ctx.lineWidth = 2;
        ctx.stroke();

        // Pin Label
        ctx.font = isSelected ? 'bold 12px sans-serif' : '10px sans-serif';
        ctx.fillStyle = isSelected ? '#38bdf8' : '#cbd5e1';
        ctx.fillText(pin.name, pin.x + 10, pin.y + 3);
        ctx.restore();
      });
    }
  }, [
    activeTab,
    objectDistance,
    selectedDefect,
    isCorrectionApplied,
    eyeballElongation,
    activePinId,
    accommodationFactor
  ]);

  // Handle Canvas Click to select Anatomical Pin
  const handleCanvasClick = (e) => {
    if (activeTab !== 'interactive_pins') return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const rect = canvas.getBoundingClientRect();
    const scaleX = canvas.width / rect.width;
    const scaleY = canvas.height / rect.height;
    const clickX = (e.clientX - rect.left) * scaleX;
    const clickY = (e.clientY - rect.top) * scaleY;

    // Find closest pin within 25px
    let found = null;
    let minDist = 30;
    ANATOMY_PINS.forEach((pin) => {
      const dist = Math.hypot(pin.x - clickX, pin.y - clickY);
      if (dist < minDist) {
        minDist = dist;
        found = pin.id;
      }
    });

    if (found) {
      setActivePinId(found);
      if (onTelemetry) {
        onTelemetry('eye_pin_inspected', { pinId: found });
      }
    }
  };

  // 1-Click Presets
  const applyPreset = (presetKey) => {
    setIsAccommodatingAuto(false);
    if (presetKey === 'far_vision') {
      setActiveTab('accommodation');
      setObjectDistance(8.0);
    } else if (presetKey === 'near_vision') {
      setActiveTab('accommodation');
      setObjectDistance(0.25);
    } else if (presetKey === 'myopia_uncorrected') {
      setActiveTab('defects');
      setSelectedDefect('myopia');
      setIsCorrectionApplied(false);
    } else if (presetKey === 'myopia_corrected') {
      setActiveTab('defects');
      setSelectedDefect('myopia');
      setIsCorrectionApplied(true);
    } else if (presetKey === 'hypermetropia_corrected') {
      setActiveTab('defects');
      setSelectedDefect('hypermetropia');
      setIsCorrectionApplied(true);
    }
    if (onTelemetry) {
      onTelemetry('eye_preset_loaded', { preset: presetKey });
    }
  };

  // KCSE Quiz Submission
  const handleQuizAnswer = (index) => {
    if (quizSubmitted) return;
    setSelectedOption(index);
  };

  const submitQuizAnswer = () => {
    if (selectedOption === null) return;
    const currentQ = KCSE_QUIZ_QUESTIONS[quizIndex];
    const isCorrect = currentQ.options[selectedOption].correct;
    if (isCorrect) {
      setQuizScore((prev) => prev + 1);
    }
    setQuizSubmitted(true);
    if (onTelemetry) {
      onTelemetry('eye_kcse_quiz_question_answered', {
        questionId: currentQ.id,
        isCorrect
      });
    }
  };

  const nextQuizQuestion = () => {
    if (quizIndex < KCSE_QUIZ_QUESTIONS.length - 1) {
      setQuizIndex((prev) => prev + 1);
      setSelectedOption(null);
      setQuizSubmitted(false);
    } else {
      setQuizComplete(true);
      if (onTelemetry) {
        onTelemetry('SIMULATION_CHALLENGE_COMPLETED', {
          topic: 'human_eye_kcse_challenge',
          finalScore: quizScore + (KCSE_QUIZ_QUESTIONS[quizIndex].options[selectedOption]?.correct ? 1 : 0),
          totalQuestions: KCSE_QUIZ_QUESTIONS.length
        });
      }
    }
  };

  const restartQuiz = () => {
    setQuizIndex(0);
    setSelectedOption(null);
    setQuizScore(0);
    setQuizSubmitted(false);
    setQuizComplete(false);
  };

  return (
    <div className="w-full min-h-screen bg-slate-950 text-slate-100 p-4 md:p-6 font-sans">
      {/* Top Header Banner */}
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-5 mb-6">
        <div>
          <div className="flex items-center gap-3">
            <span className="p-2.5 bg-blue-600/20 text-blue-400 rounded-xl border border-blue-500/30">
              <Eye className="w-6 h-6" />
            </span>
            <div>
              <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
                Human Eye: Accommodation & Vision Defects
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-500/10 text-blue-400 border border-blue-500/20">
                  KCSE Biology Form 4
                </span>
              </h1>
              <p className="text-sm text-slate-400 mt-0.5">
                Topic 3: Reception, Response and Coordination in Animals • Photoreception & Ray Optics
              </p>
            </div>
          </div>
        </div>

        {/* 1-Click Auto Presets */}
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider mr-1">
            1-Click Presets:
          </span>
          <button
            onClick={() => applyPreset('far_vision')}
            className="px-3 py-1.5 text-xs font-medium bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg border border-slate-700 transition"
          >
            Distant (Flat Lens)
          </button>
          <button
            onClick={() => applyPreset('near_vision')}
            className="px-3 py-1.5 text-xs font-medium bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg border border-slate-700 transition"
          >
            Near (Bulging Lens)
          </button>
          <button
            onClick={() => applyPreset('myopia_uncorrected')}
            className="px-3 py-1.5 text-xs font-medium bg-red-950/40 hover:bg-red-900/50 text-red-300 rounded-lg border border-red-800/40 transition"
          >
            Myopia Blur
          </button>
          <button
            onClick={() => applyPreset('myopia_corrected')}
            className="px-3 py-1.5 text-xs font-medium bg-emerald-950/40 hover:bg-emerald-900/50 text-emerald-300 rounded-lg border border-emerald-800/40 transition"
          >
            Concave Fix
          </button>
          <button
            onClick={() => applyPreset('hypermetropia_corrected')}
            className="px-3 py-1.5 text-xs font-medium bg-purple-950/40 hover:bg-purple-900/50 text-purple-300 rounded-lg border border-purple-800/40 transition"
          >
            Convex Fix
          </button>
        </div>
      </div>

      <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Visual Canvas & Mode Switcher (8 cols) */}
        <div className="lg:col-span-8 flex flex-col gap-4">
          {/* Tab Navigation */}
          <div className="flex items-center gap-2 bg-slate-900/80 p-1.5 rounded-xl border border-slate-800">
            <button
              onClick={() => {
                setActiveTab('accommodation');
                setIsAccommodatingAuto(false);
              }}
              className={`flex-1 py-2 px-3 text-sm font-semibold rounded-lg flex items-center justify-center gap-2 transition ${
                activeTab === 'accommodation'
                  ? 'bg-blue-600 text-white shadow-lg shadow-blue-600/30'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'
              }`}
            >
              <Compass className="w-4 h-4" />
              1. Accommodation Engine
            </button>
            <button
              onClick={() => {
                setActiveTab('defects');
                setIsAccommodatingAuto(false);
              }}
              className={`flex-1 py-2 px-3 text-sm font-semibold rounded-lg flex items-center justify-center gap-2 transition ${
                activeTab === 'defects'
                  ? 'bg-blue-600 text-white shadow-lg shadow-blue-600/30'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'
              }`}
            >
              <Glasses className="w-4 h-4" />
              2. Defects & Ray Tracing
            </button>
            <button
              onClick={() => {
                setActiveTab('interactive_pins');
                setIsAccommodatingAuto(false);
              }}
              className={`flex-1 py-2 px-3 text-sm font-semibold rounded-lg flex items-center justify-center gap-2 transition ${
                activeTab === 'interactive_pins'
                  ? 'bg-blue-600 text-white shadow-lg shadow-blue-600/30'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'
              }`}
            >
              <Layers className="w-4 h-4" />
              3. Anatomy Pin Explorer
            </button>
          </div>

          {/* Interactive Sagittal Viewport */}
          <div className="relative bg-slate-900 rounded-2xl border border-slate-800 overflow-hidden shadow-2xl p-2">
            <canvas
              ref={canvasRef}
              width={760}
              height={440}
              onClick={handleCanvasClick}
              className="w-full h-auto cursor-crosshair rounded-xl bg-slate-950"
            />

            {/* Quick Status Pill Overlay */}
            <div className="absolute top-4 left-4 bg-slate-900/90 backdrop-blur-md px-3 py-1.5 rounded-lg border border-slate-700/60 text-xs flex items-center gap-2">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
              <span className="font-mono text-slate-300">
                {activeTab === 'accommodation' &&
                  `Object Distance: ${objectDistance.toFixed(2)}m • Lens: ${
                    accommodationFactor > 0.65 ? 'Thin / Low Power' : 'Bulging / High Power'
                  }`}
                {activeTab === 'defects' &&
                  `Defect: ${selectedDefect.toUpperCase()} • Correction: ${
                    isCorrectionApplied ? 'ON' : 'OFF'
                  }`}
                {activeTab === 'interactive_pins' && 'Click any circular pin to view anatomy & KCSE functions'}
              </span>
            </div>

            {/* In-Canvas Dynamic Telemetry HUD */}
            <div className="absolute bottom-4 right-4 bg-slate-900/90 backdrop-blur-md p-3 rounded-xl border border-slate-700/80 text-xs font-mono space-y-1 text-slate-300">
              <div className="flex justify-between gap-4">
                <span className="text-slate-400">Ciliary Muscle Tone:</span>
                <span className="text-amber-400 font-bold">{ciliaryMuscleTone.toFixed(0)}%</span>
              </div>
              <div className="flex justify-between gap-4">
                <span className="text-slate-400">Suspensory Zonule Tension:</span>
                <span className="text-cyan-400 font-bold">{zonuleTension.toFixed(0)}%</span>
              </div>
              <div className="flex justify-between gap-4">
                <span className="text-slate-400">Lens Curvature / Thickness:</span>
                <span className="text-emerald-400 font-bold">{lensThicknessMm.toFixed(2)} mm</span>
              </div>
              <div className="flex justify-between gap-4">
                <span className="text-slate-400">Total Refractive Power:</span>
                <span className="text-purple-400 font-bold">{focalPowerDiopters.toFixed(1)} D</span>
              </div>
            </div>
          </div>

          {/* Interactive Biological Controls Bar */}
          <div className="bg-slate-900 p-4 rounded-xl border border-slate-800">
            {activeTab === 'accommodation' && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-semibold text-slate-200 flex items-center gap-2">
                    <Sliders className="w-4 h-4 text-blue-400" />
                    Object Distance (Accommodation Stimulus): {objectDistance.toFixed(2)} metres
                  </span>
                  <button
                    onClick={() => setIsAccommodatingAuto((p) => !p)}
                    className="flex items-center gap-1.5 px-3 py-1 bg-blue-600/30 hover:bg-blue-600/50 text-blue-300 text-xs font-semibold rounded-lg border border-blue-500/40 transition"
                  >
                    {isAccommodatingAuto ? (
                      <>
                        <Pause className="w-3.5 h-3.5" /> Pause Auto-Cycle
                      </>
                    ) : (
                      <>
                        <Play className="w-3.5 h-3.5" /> Auto Accommodate (Near ⇄ Far)
                      </>
                    )}
                  </button>
                </div>

                <div className="flex items-center gap-4">
                  <span className="text-xs font-mono text-slate-400">Near Point (0.25m)</span>
                  <input
                    type="range"
                    min="0.25"
                    max="8.0"
                    step="0.05"
                    value={objectDistance}
                    onChange={(e) => {
                      setIsAccommodatingAuto(false);
                      setObjectDistance(parseFloat(e.target.value));
                    }}
                    className="flex-1 accent-blue-500 h-2 bg-slate-700 rounded-lg cursor-pointer"
                  />
                  <span className="text-xs font-mono text-slate-400">Infinity (&gt;6m)</span>
                </div>

                {/* Biological Explanation Cards */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2 text-xs">
                  <div className="p-3 bg-slate-800/60 rounded-lg border border-slate-700/60">
                    <span className="font-bold text-emerald-400 block mb-1">
                      Near Vision (&le; 25 cm):
                    </span>
                    <ul className="list-disc list-inside space-y-0.5 text-slate-300">
                      <li>Ciliary muscles contract (ring narrows).</li>
                      <li>Suspensory ligaments slacken (tension falls).</li>
                      <li>Lens bulges thicker due to inherent elasticity.</li>
                      <li>Increases converging power to focus diverging rays.</li>
                    </ul>
                  </div>

                  <div className="p-3 bg-slate-800/60 rounded-lg border border-slate-700/60">
                    <span className="font-bold text-sky-400 block mb-1">
                      Distant Vision (&ge; 6 metres):
                    </span>
                    <ul className="list-disc list-inside space-y-0.5 text-slate-300">
                      <li>Ciliary muscles relax (ring diameter widens).</li>
                      <li>Suspensory ligaments pulled taut (high tension).</li>
                      <li>Elastic lens is stretched thin / flattened.</li>
                      <li>Decreases focal power for nearly parallel rays.</li>
                    </ul>
                  </div>
                </div>
              </div>
            )}

            {activeTab === 'defects' && (
              <div className="space-y-4">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <span className="text-sm font-semibold text-slate-200">Select Vision Condition:</span>
                  <div className="flex flex-wrap gap-2">
                    {[
                      { id: 'emmetropia', label: 'Emmetropia (Normal)' },
                      { id: 'myopia', label: 'Myopia (Short Sight)' },
                      { id: 'hypermetropia', label: 'Hypermetropia (Long Sight)' },
                      { id: 'presbyopia', label: 'Presbyopia (Aging Lens)' },
                      { id: 'astigmatism', label: 'Astigmatism (Uneven Cornea)' }
                    ].map((d) => (
                      <button
                        key={d.id}
                        onClick={() => setSelectedDefect(d.id)}
                        className={`px-3 py-1.5 text-xs font-semibold rounded-lg border transition ${
                          selectedDefect === d.id
                            ? 'bg-blue-600 text-white border-blue-400 shadow-md'
                            : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'
                        }`}
                      >
                        {d.label}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex items-center justify-between p-3 bg-slate-800/70 rounded-lg border border-slate-700">
                  <div>
                    <span className="text-xs font-bold text-slate-300 block">
                      Corrective Spectacle Lens:
                    </span>
                    <span className="text-xs text-slate-400">
                      {selectedDefect === 'emmetropia' && 'No corrective lens required.'}
                      {selectedDefect === 'myopia' && 'Concave (Diverging) Lens — spreads rays before cornea.'}
                      {selectedDefect === 'hypermetropia' && 'Convex (Converging) Lens — adds refractive power.'}
                      {selectedDefect === 'presbyopia' && 'Convex Reading Addition Lens.'}
                      {selectedDefect === 'astigmatism' && 'Cylindrical Lens — compensates for unequal corneal meridians.'}
                    </span>
                  </div>

                  {selectedDefect !== 'emmetropia' && (
                    <button
                      onClick={() => setIsCorrectionApplied((prev) => !prev)}
                      className={`px-4 py-2 text-xs font-bold rounded-lg border transition ${
                        isCorrectionApplied
                          ? 'bg-emerald-600 hover:bg-emerald-500 text-white border-emerald-400 shadow-lg shadow-emerald-600/30'
                          : 'bg-slate-700 hover:bg-slate-600 text-slate-200 border-slate-600'
                      }`}
                    >
                      {isCorrectionApplied ? '✓ Spectacle Applied' : '+ Put on Spectacles'}
                    </button>
                  )}
                </div>

                {/* Eyeball Axial Length Slider (Simulate anatomical cause) */}
                <div className="flex items-center gap-4 text-xs">
                  <span className="text-slate-400 font-medium">Eyeball Anteroposterior Axis:</span>
                  <input
                    type="range"
                    min="-40"
                    max="45"
                    value={eyeballElongation}
                    onChange={(e) => setEyeballElongation(parseInt(e.target.value))}
                    className="flex-1 accent-purple-500 h-2 bg-slate-700 rounded-lg cursor-pointer"
                  />
                  <span className="font-mono text-purple-300">
                    {eyeballElongation > 0
                      ? `+${eyeballElongation}px (Elongated)`
                      : eyeballElongation < 0
                      ? `${eyeballElongation}px (Shortened)`
                      : 'Normal Axis'}
                  </span>
                </div>
              </div>
            )}

            {activeTab === 'interactive_pins' && (
              <div>
                <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-2">
                  Select or Click Pin on Diagram:
                </span>
                <div className="flex flex-wrap gap-2">
                  {ANATOMY_PINS.map((p) => (
                    <button
                      key={p.id}
                      onClick={() => setActivePinId(p.id)}
                      className={`px-3 py-1.5 text-xs font-semibold rounded-lg border transition ${
                        activePinId === p.id
                          ? 'bg-blue-600 text-white border-blue-400'
                          : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'
                      }`}
                    >
                      {p.name}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right Column: KCSE Exam Practice & Anatomical Inspector (4 cols) */}
        <div className="lg:col-span-4 flex flex-col gap-4">
          {/* Anatomical Inspector Card */}
          {activeTab === 'interactive_pins' && activePinId ? (
            <div className="bg-slate-900 p-5 rounded-2xl border border-blue-500/40 shadow-xl">
              {(() => {
                const pin = ANATOMY_PINS.find((p) => p.id === activePinId);
                if (!pin) return null;
                return (
                  <div>
                    <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                      <h3 className="text-lg font-bold text-blue-400">{pin.name}</h3>
                      <span className="text-xs px-2 py-0.5 rounded bg-blue-500/20 text-blue-300 border border-blue-500/30">
                        {pin.shortDesc}
                      </span>
                    </div>
                    <p className="text-sm text-slate-300 mt-3 leading-relaxed">{pin.fullDesc}</p>
                    <div className="mt-4 p-3 bg-slate-800/80 rounded-xl border border-slate-700 text-xs text-slate-400">
                      <span className="font-bold text-amber-400 block mb-1">
                        KCSE Marking Scheme Tip:
                      </span>
                      Always specify both structure and physiological mechanism (e.g. state both
                      ciliary muscle state AND suspensory ligament tension in accommodation
                      questions).
                    </div>
                  </div>
                );
              })()}
            </div>
          ) : (
            <div className="bg-slate-900 p-4 rounded-2xl border border-slate-800 text-xs text-slate-400">
              <span className="font-bold text-slate-200 block mb-1">
                Form 4 Biology Syllabus Objective:
              </span>
              Explain the structure and functioning of the mammalian eye with specific reference to
              accommodation, pupil reflex, rods/cones distribution, and correction of visual defects.
            </div>
          )}

          {/* Interactive KCSE Exam Challenge Card */}
          <div className="bg-slate-900 p-5 rounded-2xl border border-slate-800 shadow-xl flex-1 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                <span className="flex items-center gap-2 text-sm font-bold text-slate-200">
                  <Award className="w-4 h-4 text-amber-400" />
                  KCSE Biology Exam Challenge
                </span>
                <span className="text-xs font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700">
                  Q{quizIndex + 1} of {KCSE_QUIZ_QUESTIONS.length}
                </span>
              </div>

              {!quizComplete ? (
                <div className="mt-4 space-y-3">
                  <p className="text-sm font-medium text-slate-200 leading-snug">
                    {KCSE_QUIZ_QUESTIONS[quizIndex].question}
                  </p>

                  <div className="space-y-2 mt-3">
                    {KCSE_QUIZ_QUESTIONS[quizIndex].options.map((opt, idx) => {
                      const isChosen = selectedOption === idx;
                      let btnStyle = 'bg-slate-800/70 border-slate-700 text-slate-300 hover:bg-slate-800';
                      if (quizSubmitted) {
                        if (opt.correct) {
                          btnStyle = 'bg-emerald-950/60 border-emerald-500 text-emerald-300';
                        } else if (isChosen && !opt.correct) {
                          btnStyle = 'bg-red-950/60 border-red-500 text-red-300';
                        }
                      } else if (isChosen) {
                        btnStyle = 'bg-blue-600/30 border-blue-400 text-blue-200';
                      }

                      return (
                        <button
                          key={idx}
                          onClick={() => handleQuizAnswer(idx)}
                          disabled={quizSubmitted}
                          className={`w-full text-left p-3 text-xs font-medium rounded-xl border transition flex items-start gap-2 ${btnStyle}`}
                        >
                          <span className="font-mono text-slate-400 mt-0.5">
                            {String.fromCharCode(65 + idx)}.
                          </span>
                          <span className="flex-1">{opt.text}</span>
                        </button>
                      );
                    })}
                  </div>

                  {quizSubmitted && (
                    <div className="p-3 bg-slate-800/90 rounded-xl border border-slate-700 text-xs text-slate-300 mt-3 animate-fadeIn">
                      <span className="font-bold text-emerald-400 block mb-1">
                        Examiner Note:
                      </span>
                      {KCSE_QUIZ_QUESTIONS[quizIndex].explanation}
                    </div>
                  )}
                </div>
              ) : (
                <div className="mt-6 text-center space-y-4 py-4">
                  <div className="inline-flex p-4 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
                    <CheckCircle2 className="w-10 h-10" />
                  </div>
                  <div>
                    <h4 className="text-lg font-bold text-white">Challenge Completed!</h4>
                    <p className="text-sm text-slate-400 mt-1">
                      You scored {quizScore} out of {KCSE_QUIZ_QUESTIONS.length} on Form 4 Eye
                      Optics.
                    </p>
                  </div>
                  <button
                    onClick={restartQuiz}
                    className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded-xl transition"
                  >
                    Try Again
                  </button>
                </div>
              )}
            </div>

            {!quizComplete && (
              <div className="pt-4 border-t border-slate-800 mt-4 flex justify-between items-center">
                <span className="text-xs text-slate-400 font-mono">Score: {quizScore} pts</span>
                {!quizSubmitted ? (
                  <button
                    onClick={submitQuizAnswer}
                    disabled={selectedOption === null}
                    className="px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 text-white text-xs font-bold rounded-xl transition"
                  >
                    Submit Answer
                  </button>
                ) : (
                  <button
                    onClick={nextQuizQuestion}
                    className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl transition flex items-center gap-1.5"
                  >
                    {quizIndex < KCSE_QUIZ_QUESTIONS.length - 1 ? (
                      <>
                        Next Question <ChevronRight className="w-3.5 h-3.5" />
                      </>
                    ) : (
                      'Finish Challenge'
                    )}
                  </button>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
