import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import {
  Wind,
  Droplets,
  Gauge,
  Play,
  Pause,
  RotateCcw,
  HelpCircle,
  BookOpen,
  CheckCircle2,
  XCircle,
  Award,
  Eye,
  ArrowUp,
  ArrowRight,
  Sun,
  Info,
  Sliders,
  Table,
  Sparkles,
  Activity,
  ShieldCheck,
  Microscope,
  RefreshCw,
  Layers,
  ChevronRight,
  AlertTriangle,
  Beaker
} from 'lucide-react';

// ============================================================================
// KCSE & GRADE 10 BIOLOGY EXAM QUESTIONS
// ============================================================================
const KCSE_QUESTIONS = [
  {
    id: 'q1',
    title: 'Question 1: Wind Speed and the Boundary Layer',
    prompt:
      'Why does increasing wind speed from calm air to high wind accelerate the rate of transpiration in a leafy shoot?',
    options: [
      {
        id: 'A',
        text: 'Moving air sweeps away the humid boundary layer of water vapor around the leaf, steepening the diffusion gradient between the interior and exterior.',
        correct: true,
      },
      {
        id: 'B',
        text: 'Wind exerts mechanical suction directly on the cuticle, physically pulling liquid water out of epidermal cells.',
        correct: false,
      },
      {
        id: 'C',
        text: 'Wind increases the temperature of leaf mesophyll cells, causing water to boil inside xylem vessels.',
        correct: false,
      },
      {
        id: 'D',
        text: 'Wind forces guard cells to remain permanently open by increasing atmospheric pressure on the leaf.',
        correct: false,
      },
    ],
    explanation:
      'In still air, water evaporating through open stomata creates a saturated, stagnant humid boundary layer just outside the leaf. This reduces the water potential and vapor pressure gradient. Wind sweeps this layer away, replacing it with drier bulk air, thereby steepening the water vapor concentration gradient (dC/dx) and accelerating diffusion.',
  },
  {
    id: 'q2',
    title: 'Question 2: Potometer Working Principle',
    prompt:
      'In a Ganong’s potometer, what does the rate of movement of the air bubble along the calibrated capillary tube directly measure?',
    options: [
      {
        id: 'A',
        text: 'The exact amount of glucose synthesized during light-dependent photosynthesis.',
        correct: false,
      },
      {
        id: 'B',
        text: 'The rate of water uptake by the leafy shoot, which closely approximates the rate of transpiration under steady state.',
        correct: true,
      },
      {
        id: 'C',
        text: 'The pressure generated by anaerobic respiration in the stem pith.',
        correct: false,
      },
      {
        id: 'D',
        text: 'The absolute rate of mineral ion absorption by active transport.',
        correct: false,
      },
    ],
    explanation:
      'A potometer measures the rate of water absorption. Because more than 98% of the water absorbed by a leafy shoot is lost through transpiration (with only ~1-2% utilized in photosynthesis and maintaining cell turgor), the rate of bubble movement along the graduated capillary tube is an accurate practical proxy for the transpiration rate.',
  },
  {
    id: 'q3',
    title: 'Question 3: Potometer Setup Precautions',
    prompt:
      'Why is it vital to cut the shoot under water and assemble the potometer apparatus completely immersed before sealing with petroleum jelly?',
    options: [
      {
        id: 'A',
        text: 'To prevent air bubbles from entering xylem vessels, which would break the continuous cohesive water column (air embolism/cavitation).',
        correct: true,
      },
      {
        id: 'B',
        text: 'To prevent chlorophyll from dissolving into the laboratory air.',
        correct: false,
      },
      {
        id: 'C',
        text: 'To sterilize the cut stem against fungal spores before insertion into the rubber bung.',
        correct: false,
      },
      {
        id: 'D',
        text: 'To ensure the leaves are completely waterlogged so stomata permanently open.',
        correct: false,
      },
    ],
    explanation:
      'According to the Cohesion-Tension Theory, water travels up xylem under negative pressure (tension). If the stem is cut in air, air is sucked into the cut xylem lumens, causing an air lock (embolism/cavitation) that breaks hydrogen bonding cohesion between water molecules, preventing water uptake.',
  },
  {
    id: 'q4',
    title: 'Question 4: Petroleum Jelly (Vaseline) Stomatal Practical',
    prompt:
      'In a classic Grade 10 practical on a typical dicotyledonous shoot, coating the lower leaf epidermis with petroleum jelly results in a much greater reduction in transpiration than coating the upper epidermis. What does this deduce?',
    options: [
      {
        id: 'A',
        text: 'The lower epidermis has a significantly higher stomatal density than the upper epidermis.',
        correct: true,
      },
      {
        id: 'B',
        text: 'The lower epidermis lacks a waxy cuticle while the upper epidermis has no stomata at all.',
        correct: false,
      },
      {
        id: 'C',
        text: 'Petroleum jelly chemically dissolves chloroplasts inside the spongy mesophyll cells.',
        correct: false,
      },
      {
        id: 'D',
        text: 'The upper epidermis transpires primarily through lenticels rather than stomatal pores.',
        correct: false,
      },
    ],
    explanation:
      'In dorsiventral dicot leaves, the majority of stomata (~80-90%) are located on the lower epidermis to minimize direct solar heating and evaporation. Smearing petroleum jelly over the lower surface physically blocks the stomatal pores, dramatically slashing water loss compared to coating the upper surface.',
  },
];

// Preset experimental conditions
const WIND_PRESETS = [
  { id: 'calm', name: 'Still Air (Calm)', speed: 0, description: '0 m/s • Saturated boundary layer trapped' },
  { id: 'breeze', name: 'Gentle Breeze', speed: 2.5, description: '2.5 m/s • Boundary layer partly thinned' },
  { id: 'moderate', name: 'Moderate Wind', speed: 5.5, description: '5.5 m/s • Boundary layer rapidly swept' },
  { id: 'gale', name: 'High Wind / Gale', speed: 9.0, description: '9.0 m/s • Maximum diffusion gradient' },
];

const LEAF_TREATMENTS = [
  { id: 'none', label: 'Untreated (Both Open)', factor: 1.0, desc: 'Normal stomatal distribution on both surfaces' },
  { id: 'upper', label: 'Vaseline on Upper Epidermis', factor: 0.88, desc: 'Coats upper cuticle (~12% stomata blocked)' },
  { id: 'lower', label: 'Vaseline on Lower Epidermis', factor: 0.20, desc: 'Coats lower surface (~88% stomata blocked!)' },
  { id: 'both', label: 'Vaseline on Both Surfaces', factor: 0.05, desc: 'All stomata blocked (cuticular loss only)' },
];

export default function PlantTranspirationRateSim({ config = {}, onTelemetry }) {
  // --------------------------------------------------------------------------
  // PRIMARY SIMULATION PARAMETERS
  // --------------------------------------------------------------------------
  // 1 Primary Variable: Wind Speed (0 to 10 m/s)
  const [windSpeed, setWindSpeed] = useState(0); // 0 = Still Air / Calm, 10 = High Wind
  const [leafTreatment, setLeafTreatment] = useState('none'); // 'none' | 'upper' | 'lower' | 'both'
  const [ambientHumidity, setAmbientHumidity] = useState(50); // 20% to 90%
  const [lightState, setLightState] = useState('bright'); // 'bright' | 'dim' | 'dark'
  const [isPlaying, setIsPlaying] = useState(true);

  // Active view: 'potometer' (macro whole-plant apparatus) | 'micro_stoma' (cellular boundary layer) | 'data_lab' (graph & records)
  const [activeView, setActiveView] = useState('potometer');
  const [activeTab, setActiveTab] = useState('experiment'); // 'experiment' | 'analysis' | 'theory' | 'quiz'

  // Potometer capillary bubble state
  const [bubblePos, setBubblePos] = useState(10); // mm along capillary scale (0 to 100 mm)
  const [isRefillingTap, setIsRefillingTap] = useState(false);
  const [tapAngle, setTapAngle] = useState(0); // degrees for tap turning animation
  const [elapsedTimeSec, setElapsedTimeSec] = useState(0);

  // Data recording
  const [dataLog, setDataLog] = useState([
    {
      id: 1,
      windSpeed: 0,
      condition: 'Still Air / Calm',
      bubbleSpeed: '0.68 mm/min',
      rate: '4.2 ml/h',
      boundaryLayer: '3.8 mm',
      gradient: 'Gentle (Flat)',
    },
  ]);

  // Telemetry checkpoints state
  const [checkpoints, setCheckpoints] = useState({
    calm_observed: false,
    wind_tested: false,
    bubble_reset_used: false,
    vaseline_tested: false,
    quiz_completed: false,
  });

  // Quiz state
  const [currentQuestionIdx, setCurrentQuestionIdx] = useState(0);
  const [userAnswers, setUserAnswers] = useState({});
  const [showExplanation, setShowExplanation] = useState(false);
  const [quizScore, setQuizScore] = useState(null);

  // Canvas refs and animation
  const potometerCanvasRef = useRef(null);
  const microCanvasRef = useRef(null);
  const fanAngleRef = useRef(0);
  const particlesRef = useRef([]);
  const microParticlesRef = useRef([]);
  const animFrameIdRef = useRef(null);

  // --------------------------------------------------------------------------
  // BIOLOGICAL MODEL CALCULATIONS
  // --------------------------------------------------------------------------
  const bioMetrics = useMemo(() => {
    // 1. Boundary Layer Thickness (delta in mm)
    // In still air (v=0), boundary layer is thick (~3.8 mm) due to stagnant water vapor.
    // In wind, boundary layer thins rapidly following fluid dynamics boundary layer thinning:
    const boundaryLayerMm = Number((0.4 + 3.4 / (1 + 0.7 * windSpeed)).toFixed(2));

    // 2. Light / Stomatal Aperture factor
    const stomaFactor = lightState === 'bright' ? 1.0 : lightState === 'dim' ? 0.45 : 0.08;

    // 3. Leaf surface treatment factor (Vaseline experiment)
    const treatmentObj = LEAF_TREATMENTS.find((t) => t.id === leafTreatment) || LEAF_TREATMENTS[0];
    const treatmentFactor = treatmentObj.factor;

    // 4. Vapor Pressure / Humidity Gradient (ΔC)
    // Internal leaf sub-stomatal cavity is 100% saturated with water vapor.
    // External air is ambientHumidity %.
    const humidityGradient = Math.max(0.1, (100 - ambientHumidity) / 100);

    // 5. Transpiration Rate Calculation (ml/h)
    // Base rate in calm still air: ~4.0 ml/h
    // Wind factor steepens the gradient by sweeping away humid boundary layer:
    const windEnhancement = 1 + 4.8 * (1 - Math.exp(-0.45 * windSpeed));
    let rawRate = 4.2 * windEnhancement * stomaFactor * treatmentFactor * (humidityGradient / 0.5);

    // Physiological feedback: at extreme wind (> 8.5 m/s) with bright sun,
    // guard cells start losing turgor, causing slight protective stomatal closure
    if (windSpeed > 8.5 && lightState === 'bright') {
      const throttling = 1 - (windSpeed - 8.5) * 0.08;
      rawRate *= Math.max(0.75, throttling);
    }

    const transpirationRate = Number(Math.max(0.3, rawRate).toFixed(1));

    // 6. Potometer Bubble Speed (mm/min along capillary tube)
    // Direct proportion to transpiration rate (1 ml/h ≈ 0.16 mm/min on standard 0.8mm bore capillary)
    const bubbleSpeedMmMin = Number((transpirationRate * 0.165).toFixed(2));

    // 7. Diffusion Gradient Status description
    let gradientDesc = 'Gentle (Gentle slope, slow loss)';
    let gradientBadgeColor = 'bg-blue-500/20 text-blue-300 border-blue-500/30';
    if (windSpeed >= 6) {
      gradientDesc = 'Steep (Vapor swept away rapidly)';
      gradientBadgeColor = 'bg-rose-500/20 text-rose-300 border-rose-500/30';
    } else if (windSpeed >= 2.5) {
      gradientDesc = 'Moderate (Boundary layer thinned)';
      gradientBadgeColor = 'bg-amber-500/20 text-amber-300 border-amber-500/30';
    }

    // 8. Rate Category
    let rateCategory = 'Low (Calm Baseline)';
    let rateColor = 'text-emerald-400';
    if (transpirationRate > 18) {
      rateCategory = 'Very High (Rapid Uptake)';
      rateColor = 'text-rose-400';
    } else if (transpirationRate > 10) {
      rateCategory = 'Moderate / High';
      rateColor = 'text-amber-400';
    }

    return {
      boundaryLayerMm,
      transpirationRate,
      bubbleSpeedMmMin,
      gradientDesc,
      gradientBadgeColor,
      rateCategory,
      rateColor,
      stomaFactor,
      treatmentFactor,
    };
  }, [windSpeed, leafTreatment, ambientHumidity, lightState]);

  // --------------------------------------------------------------------------
  // TELEMETRY CHECKPOINTS
  // --------------------------------------------------------------------------
  const triggerTelemetry = useCallback(
    (checkpointKey, meta = {}) => {
      if (typeof onTelemetry === 'function') {
        onTelemetry('SIMULATION_CHECKPOINT_VERIFIED', {
          simulation: 'plant_transpiration_rate',
          checkpoint: checkpointKey,
          windSpeed,
          leafTreatment,
          transpirationRate: bioMetrics.transpirationRate,
          boundaryLayerMm: bioMetrics.boundaryLayerMm,
          timestamp: Date.now(),
          ...meta,
        });
      }
    },
    [onTelemetry, windSpeed, leafTreatment, bioMetrics]
  );

  // Checkpoint 1: Calm Baseline verification
  useEffect(() => {
    if (windSpeed === 0 && !checkpoints.calm_observed) {
      const timer = setTimeout(() => {
        setCheckpoints((prev) => ({ ...prev, calm_observed: true }));
        triggerTelemetry('CALM_BASELINE_VERIFIED', {
          description: 'Observed still air humid boundary layer hugging leaf',
        });
      }, 2500);
      return () => clearTimeout(timer);
    }
  }, [windSpeed, checkpoints.calm_observed, triggerTelemetry]);

  // Checkpoint 2: High Wind verification
  useEffect(() => {
    if (windSpeed >= 6 && !checkpoints.wind_tested) {
      setCheckpoints((prev) => ({ ...prev, wind_tested: true }));
      triggerTelemetry('HIGH_WIND_BOUNDARY_LAYER_SWEPT', {
        windSpeed,
        description: 'Observed air movement sweeping away boundary layer and accelerating transpiration',
      });
    }
  }, [windSpeed, checkpoints.wind_tested, triggerTelemetry]);

  // Checkpoint 3: Vaseline treatment test
  useEffect(() => {
    if (leafTreatment === 'lower' && !checkpoints.vaseline_tested) {
      setCheckpoints((prev) => ({ ...prev, vaseline_tested: true }));
      triggerTelemetry('VASELINE_LOWER_EPIDERMIS_TESTED', {
        treatment: 'lower',
        description: 'Demonstrated that lower epidermis has majority of stomatal pores',
      });
    }
  }, [leafTreatment, checkpoints.vaseline_tested, triggerTelemetry]);

  // --------------------------------------------------------------------------
  // POTOMETER BUBBLE ADVANCEMENT & TIMER
  // --------------------------------------------------------------------------
  useEffect(() => {
    if (!isPlaying) return;

    const interval = setInterval(() => {
      setElapsedTimeSec((prev) => prev + 1);

      // Advance bubble: bubbleSpeed is in mm/min. In 1 second, it moves bubbleSpeed / 60 mm.
      // We scale slightly (e.g. 2.2x) so student can visually observe bubble moving smoothly without waiting minutes
      const deltaMm = (bioMetrics.bubbleSpeedMmMin / 60) * 2.2;

      setBubblePos((prev) => {
        const nextPos = prev + deltaMm;
        if (nextPos >= 96) {
          // Bubble reached capillary end! Wrap or prompt reset
          return 96;
        }
        return nextPos;
      });
    }, 1000);

    return () => clearInterval(interval);
  }, [isPlaying, bioMetrics.bubbleSpeedMmMin]);

  // Reservoir Tap Reset Handler
  const handleResetBubble = () => {
    setIsRefillingTap(true);
    setTapAngle(90); // rotate tap 90 degrees

    if (!checkpoints.bubble_reset_used) {
      setCheckpoints((prev) => ({ ...prev, bubble_reset_used: true }));
      triggerTelemetry('POTOMETER_RESERVOIR_TAP_RESET', {
        description: 'Used reservoir stopcock to introduce water and reset capillary air bubble',
      });
    }

    setTimeout(() => {
      setBubblePos(5); // reset back to 5 mm marking
      setTapAngle(0);
      setIsRefillingTap(false);
    }, 600);
  };

  // Full Baseline Reset
  const handleFullReset = () => {
    setWindSpeed(0);
    setLeafTreatment('none');
    setAmbientHumidity(50);
    setLightState('bright');
    setBubblePos(8);
    setElapsedTimeSec(0);
    setIsPlaying(true);
  };

  // Record Data Point
  const handleRecordData = () => {
    const newEntry = {
      id: dataLog.length + 1,
      windSpeed,
      condition:
        windSpeed === 0
          ? 'Still Air / Calm'
          : windSpeed < 4
          ? 'Gentle Breeze'
          : windSpeed < 8
          ? 'Moderate Wind'
          : 'High Wind / Gale',
      bubbleSpeed: `${bioMetrics.bubbleSpeedMmMin} mm/min`,
      rate: `${bioMetrics.transpirationRate} ml/h`,
      boundaryLayer: `${bioMetrics.boundaryLayerMm} mm`,
      gradient: bioMetrics.gradientDesc.split(' ')[0],
    };
    setDataLog((prev) => [newEntry, ...prev]);

    if (dataLog.length >= 2) {
      triggerTelemetry('POTOMETER_DATA_LOGGED', {
        trialsCount: dataLog.length + 1,
        latestRate: bioMetrics.transpirationRate,
      });
    }
  };

  // --------------------------------------------------------------------------
  // CANVAS ANIMATION: WHOLE-PLANT POTOMETER SETUP
  // --------------------------------------------------------------------------
  useEffect(() => {
    const canvas = potometerCanvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    let width = (canvas.width = 800);
    let height = (canvas.height = 460);

    // Initialize vapor particles if empty
    if (particlesRef.current.length === 0) {
      for (let i = 0; i < 40; i++) {
        particlesRef.current.push({
          x: 470 + Math.random() * 110,
          y: 110 + Math.random() * 110,
          vx: (Math.random() - 0.5) * 0.4,
          vy: -0.3 - Math.random() * 0.5,
          alpha: 0.2 + Math.random() * 0.6,
          radius: 2 + Math.random() * 2.5,
          leafOriginX: 470 + Math.random() * 110,
          leafOriginY: 110 + Math.random() * 110,
        });
      }
    }

    let isRunning = true;

    const render = () => {
      if (!isRunning) return;

      // Clear Canvas
      ctx.clearRect(0, 0, width, height);

      // Lab Background Gradient
      const grad = ctx.createLinearGradient(0, 0, 0, height);
      grad.addColorStop(0, '#0a0f1d');
      grad.addColorStop(0.7, '#0f172a');
      grad.addColorStop(1, '#020617');
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, width, height);

      // Lab Bench Surface
      ctx.fillStyle = '#1e293b';
      ctx.fillRect(0, 390, width, 70);
      ctx.fillStyle = '#0f172a';
      ctx.fillRect(0, 390, width, 4);

      // Subtle Lab Grid Lines
      ctx.strokeStyle = 'rgba(51, 65, 85, 0.25)';
      ctx.lineWidth = 1;
      for (let x = 40; x < width; x += 40) {
        ctx.beginPath();
        ctx.moveTo(x, 0);
        ctx.lineTo(x, 390);
        ctx.stroke();
      }
      for (let y = 30; y < 390; y += 40) {
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(width, y);
        ctx.stroke();
      }

      // ======================================================================
      // 1. ELECTRIC LAB FAN (WIND GENERATOR) ON THE LEFT
      // ======================================================================
      const fanBaseX = 140;
      const fanBaseY = 390;
      const fanCenterY = 200;

      // Fan Stand & Neck
      ctx.fillStyle = '#475569';
      ctx.fillRect(fanBaseX - 35, fanBaseY - 12, 70, 12); // Foot
      ctx.fillStyle = '#334155';
      ctx.fillRect(fanBaseX - 5, fanCenterY, 10, fanBaseY - fanCenterY); // Upright pole

      // Fan Motor Housing
      ctx.fillStyle = '#1e293b';
      ctx.beginPath();
      ctx.ellipse(fanBaseX - 10, fanCenterY, 24, 28, 0, 0, Math.PI * 2);
      ctx.fill();
      ctx.strokeStyle = '#64748b';
      ctx.lineWidth = 2;
      ctx.stroke();

      // Fan Outer Circular Grille
      ctx.strokeStyle = '#94a3b8';
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.arc(fanBaseX + 15, fanCenterY, 52, 0, Math.PI * 2);
      ctx.stroke();

      // Grille spokes
      ctx.strokeStyle = 'rgba(148, 163, 184, 0.4)';
      ctx.lineWidth = 1;
      for (let angle = 0; angle < Math.PI * 2; angle += Math.PI / 4) {
        ctx.beginPath();
        ctx.moveTo(fanBaseX + 15, fanCenterY);
        ctx.lineTo(fanBaseX + 15 + Math.cos(angle) * 52, fanCenterY + Math.sin(angle) * 52);
        ctx.stroke();
      }

      // Fan Blades (Spinning if windSpeed > 0 and isPlaying)
      if (isPlaying && windSpeed > 0) {
        fanAngleRef.current += 0.08 + windSpeed * 0.12;
      }
      const bladeAngle = fanAngleRef.current;

      ctx.save();
      ctx.translate(fanBaseX + 15, fanCenterY);
      ctx.rotate(bladeAngle);

      // Draw 3 Curved Aerodynamic Blades
      for (let b = 0; b < 3; b++) {
        ctx.rotate((Math.PI * 2) / 3);
        ctx.fillStyle = windSpeed > 0 ? '#38bdf8' : '#64748b';
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.quadraticCurveTo(18, -12, 42, -4);
        ctx.quadraticCurveTo(34, 18, 0, 0);
        ctx.fill();
      }
      // Center cap
      ctx.fillStyle = '#0284c7';
      ctx.beginPath();
      ctx.arc(0, 0, 10, 0, Math.PI * 2);
      ctx.fill();
      ctx.restore();

      // Fan Status Label
      ctx.fillStyle = windSpeed > 0 ? '#38bdf8' : '#94a3b8';
      ctx.font = 'bold 11px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(`Electric Fan: ${windSpeed} m/s`, fanBaseX, fanBaseY + 22);

      // ======================================================================
      // 2. WIND STREAMLINES (BREEZE ARROWS)
      // ======================================================================
      if (windSpeed > 0 && isPlaying) {
        const time = Date.now() * 0.003;
        ctx.strokeStyle = `rgba(56, 189, 248, ${Math.min(0.85, 0.2 + windSpeed * 0.07)})`;
        ctx.lineWidth = 1.5 + windSpeed * 0.25;

        for (let row = 0; row < 5; row++) {
          const yPos = 120 + row * 38;
          const speedOffset = (time * (80 + windSpeed * 40) + row * 90) % 360;
          const startX = fanBaseX + 70 + speedOffset;

          if (startX < 650) {
            ctx.beginPath();
            ctx.moveTo(startX, yPos);
            ctx.lineTo(startX + 40 + windSpeed * 4, yPos);
            ctx.stroke();

            // Arrowhead
            ctx.beginPath();
            ctx.moveTo(startX + 40 + windSpeed * 4, yPos);
            ctx.lineTo(startX + 32 + windSpeed * 4, yPos - 3);
            ctx.lineTo(startX + 32 + windSpeed * 4, yPos + 3);
            ctx.closePath();
            ctx.fillStyle = `rgba(56, 189, 248, ${Math.min(0.9, 0.3 + windSpeed * 0.07)})`;
            ctx.fill();
          }
        }
      }

      // ======================================================================
      // 3. POTOMETER RETORT STAND & CLAMPS
      // ======================================================================
      const standBaseX = 400;
      const standBaseY = 390;

      // Heavy Iron Base
      ctx.fillStyle = '#334155';
      ctx.fillRect(standBaseX - 30, standBaseY - 14, 180, 14);
      ctx.fillStyle = '#475569';
      ctx.fillRect(standBaseX + 15, 70, 8, standBaseY - 70); // Vertical Rod

      // Clamp Bosshead
      ctx.fillStyle = '#64748b';
      ctx.fillRect(standBaseX + 8, 220, 22, 16);
      ctx.fillRect(standBaseX + 22, 225, 45, 6); // Arm reaching to potometer

      // ======================================================================
      // 4. GANONG'S POTOMETER APPARATUS
      // ======================================================================
      const shootStemX = 520;
      const verticalTubeTopY = 210;
      const horizontalTubeY = 330;

      // Vertical Tube Water Column (Blue tint)
      ctx.fillStyle = 'rgba(14, 165, 233, 0.35)';
      ctx.fillRect(shootStemX - 9, verticalTubeTopY, 18, horizontalTubeY - verticalTubeTopY);

      // Glass Vertical Tube Walls
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.7)';
      ctx.lineWidth = 2.5;
      ctx.strokeRect(shootStemX - 9, verticalTubeTopY, 18, horizontalTubeY - verticalTubeTopY);

      // Rubber Bung (Airtight stopper sealing shoot into tube)
      ctx.fillStyle = '#b45309'; // Rubber brown
      ctx.fillRect(shootStemX - 14, verticalTubeTopY - 18, 28, 18);
      ctx.strokeStyle = '#78350f';
      ctx.lineWidth = 1.5;
      ctx.strokeRect(shootStemX - 14, verticalTubeTopY - 18, 28, 18);

      // Vaseline airtight seal highlight around bung
      ctx.fillStyle = '#fef08a';
      ctx.fillRect(shootStemX - 16, verticalTubeTopY - 3, 32, 5);

      // Reservoir Tube (Behind or above, with stopcock/tap)
      const resX = 440;
      const resY = 170;

      // Water in Reservoir
      ctx.fillStyle = 'rgba(14, 165, 233, 0.4)';
      ctx.fillRect(resX - 12, resY, 24, 120);
      // Reservoir Glass
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.7)';
      ctx.lineWidth = 2;
      ctx.strokeRect(resX - 12, resY, 24, 120);

      // Connecting tube from reservoir to main capillary
      ctx.fillStyle = 'rgba(14, 165, 233, 0.35)';
      ctx.fillRect(resX - 6, resY + 120, 12, horizontalTubeY - (resY + 120));
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.7)';
      ctx.strokeRect(resX - 6, resY + 120, 12, horizontalTubeY - (resY + 120));

      // Reservoir Tap / Stopcock
      const tapY = 260;
      ctx.save();
      ctx.translate(resX, tapY);
      ctx.rotate((tapAngle * Math.PI) / 180);
      ctx.fillStyle = isRefillingTap ? '#ef4444' : '#f59e0b';
      ctx.fillRect(-18, -4, 36, 8); // Tap key
      ctx.beginPath();
      ctx.arc(0, 0, 7, 0, Math.PI * 2);
      ctx.fillStyle = '#d97706';
      ctx.fill();
      ctx.restore();

      // Tap instruction label
      ctx.fillStyle = '#fbbf24';
      ctx.font = '10px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('Water Reservoir Tap', resX, resY - 8);

      // ======================================================================
      // 5. HORIZONTAL CALIBRATED CAPILLARY TUBE WITH MM SCALE
      // ======================================================================
      const capStartX = 511;
      const capEndX = 750;
      const capLength = capEndX - capStartX; // ~239 px represents 0 to 100 mm scale

      // Capillary Tube Interior Water (Blue)
      ctx.fillStyle = 'rgba(56, 189, 248, 0.3)';
      ctx.fillRect(capStartX, horizontalTubeY - 4, capLength, 8);

      // Glass Capillary Walls
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.85)';
      ctx.lineWidth = 2;
      ctx.strokeRect(capStartX, horizontalTubeY - 4, capLength, 8);

      // Graduated Millimeter Scale Board below capillary
      ctx.fillStyle = '#f8fafc';
      ctx.fillRect(capStartX, horizontalTubeY + 8, capLength, 20);
      ctx.strokeStyle = '#475569';
      ctx.lineWidth = 1;
      ctx.strokeRect(capStartX, horizontalTubeY + 8, capLength, 20);

      // Scale Tick Marks (0 to 100 mm)
      ctx.fillStyle = '#0f172a';
      ctx.font = '8px monospace';
      ctx.textAlign = 'center';

      for (let mm = 0; mm <= 100; mm += 5) {
        const xPos = capStartX + (mm / 100) * capLength;
        const isMajor = mm % 20 === 0;
        const tickHeight = isMajor ? 10 : 5;

        ctx.strokeStyle = '#334155';
        ctx.beginPath();
        ctx.moveTo(xPos, horizontalTubeY + 8);
        ctx.lineTo(xPos, horizontalTubeY + 8 + tickHeight);
        ctx.stroke();

        if (isMajor) {
          ctx.fillText(`${mm}`, xPos, horizontalTubeY + 25);
        }
      }

      // Air Bubble in Capillary Tube
      const bubblePixelX = capStartX + (bubblePos / 100) * capLength;
      const bubbleWidth = 14;

      // Bubble Clear Center (Air gap)
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(bubblePixelX - bubbleWidth / 2, horizontalTubeY - 3, bubbleWidth, 6);

      // Bubble Meniscus Curves (Left & Right concave boundaries)
      ctx.strokeStyle = '#ef4444'; // Highlighted red meniscus for crystal clarity
      ctx.lineWidth = 2;
      ctx.beginPath();
      // Left meniscus
      ctx.arc(bubblePixelX - bubbleWidth / 2 + 2, horizontalTubeY, 3, Math.PI * 0.5, Math.PI * 1.5, false);
      ctx.stroke();
      // Right meniscus
      ctx.beginPath();
      ctx.arc(bubblePixelX + bubbleWidth / 2 - 2, horizontalTubeY, 3, Math.PI * 1.5, Math.PI * 0.5, false);
      ctx.stroke();

      // Bubble Pointer / Label
      ctx.fillStyle = '#f87171';
      ctx.beginPath();
      ctx.moveTo(bubblePixelX, horizontalTubeY - 14);
      ctx.lineTo(bubblePixelX - 5, horizontalTubeY - 7);
      ctx.lineTo(bubblePixelX + 5, horizontalTubeY - 7);
      ctx.closePath();
      ctx.fill();

      ctx.fillStyle = '#fca5a5';
      ctx.font = 'bold 10px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(`Air Bubble (${bubblePos.toFixed(1)} mm)`, bubblePixelX, horizontalTubeY - 18);

      // Water Uptake Direction Arrow
      ctx.fillStyle = '#38bdf8';
      ctx.font = '10px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('Transpiration Pull Water Inflow →', capStartX + capLength / 2, horizontalTubeY + 44);

      // Beaker at open end of capillary
      const beakerX = capEndX;
      const beakerY = horizontalTubeY - 10;
      ctx.fillStyle = 'rgba(56, 189, 248, 0.4)';
      ctx.fillRect(beakerX, beakerY + 6, 32, 50);
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.8)';
      ctx.lineWidth = 2;
      ctx.strokeRect(beakerX, beakerY, 32, 56);
      ctx.fillStyle = '#94a3b8';
      ctx.font = '9px sans-serif';
      ctx.fillText('Beaker', beakerX + 16, beakerY + 68);

      // ======================================================================
      // 6. CUT LEAFY SHOOT WITH XYLEM FLOW
      // ======================================================================
      // Stem entering through rubber bung
      ctx.fillStyle = '#15803d'; // Green stem
      ctx.fillRect(shootStemX - 4, 130, 8, verticalTubeTopY - 130);
      ctx.strokeStyle = '#166534';
      ctx.lineWidth = 1;
      ctx.strokeRect(shootStemX - 4, 130, 8, verticalTubeTopY - 130);

      // Xylem Upward Flow Pulsing Arrows inside stem
      if (isPlaying) {
        const flowShift = (Date.now() * (0.02 + bioMetrics.transpirationRate * 0.008)) % 24;
        ctx.fillStyle = '#67e8f9';
        for (let y = verticalTubeTopY - 10; y > 140; y -= 24) {
          const arrowY = y - flowShift;
          if (arrowY > 132 && arrowY < verticalTubeTopY) {
            ctx.beginPath();
            ctx.moveTo(shootStemX, arrowY - 4);
            ctx.lineTo(shootStemX - 3, arrowY + 3);
            ctx.lineTo(shootStemX + 3, arrowY + 3);
            ctx.closePath();
            ctx.fill();
          }
        }
      }

      // Leaves branches
      const leaves = [
        { x: shootStemX, y: 140, angle: -0.65, length: 70, width: 28 },
        { x: shootStemX, y: 125, angle: 0.55, length: 75, width: 30 },
        { x: shootStemX, y: 100, angle: -0.85, length: 65, width: 26 },
        { x: shootStemX, y: 90, angle: 0.75, length: 70, width: 27 },
        { x: shootStemX, y: 70, angle: -0.2, length: 55, width: 22 },
      ];

      leaves.forEach((lf, idx) => {
        ctx.save();
        ctx.translate(lf.x, lf.y);
        ctx.rotate(lf.angle);

        // Leaf Body (Dorsiventral shape)
        ctx.fillStyle = leafTreatment === 'lower' || leafTreatment === 'both' ? '#166534' : '#22c55e';
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.bezierCurveTo(lf.length * 0.3, -lf.width, lf.length * 0.7, -lf.width * 0.8, lf.length, 0);
        ctx.bezierCurveTo(lf.length * 0.7, lf.width * 0.8, lf.length * 0.3, lf.width, 0, 0);
        ctx.fill();

        // Main Leaf Vein (Midrib)
        ctx.strokeStyle = '#86efac';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.lineTo(lf.length * 0.9, 0);
        ctx.stroke();

        // Lateral veins
        ctx.lineWidth = 1;
        ctx.strokeStyle = 'rgba(134, 239, 172, 0.6)';
        for (let v = 15; v < lf.length * 0.8; v += 12) {
          ctx.beginPath();
          ctx.moveTo(v, 0);
          ctx.lineTo(v + 8, -lf.width * 0.45);
          ctx.moveTo(v, 0);
          ctx.lineTo(v + 8, lf.width * 0.45);
          ctx.stroke();
        }

        // Petroleum Jelly Layer Visualization (Yellow gloss on lower/upper epidermis)
        if (leafTreatment === 'lower' || leafTreatment === 'both') {
          ctx.fillStyle = 'rgba(253, 224, 71, 0.45)'; // yellow vaseline coat
          ctx.beginPath();
          ctx.moveTo(0, 0);
          ctx.bezierCurveTo(lf.length * 0.3, lf.width * 0.9, lf.length * 0.7, lf.width * 0.7, lf.length, 0);
          ctx.lineTo(lf.length * 0.7, lf.width * 0.5);
          ctx.bezierCurveTo(lf.length * 0.3, lf.width * 0.6, 0, 0, 0, 0);
          ctx.fill();
        }

        ctx.restore();
      });

      // ======================================================================
      // 7. HUMID BOUNDARY LAYER (BLUE GLOWING HALO AROUND FOLIAGE)
      // ======================================================================
      // Boundary layer thickness shrinks with wind!
      // In still air (v=0): huge glowing blue cloud (3.8mm thick)
      // In high wind: halo is stripped away to a paper-thin sliver!
      const haloRadius = 45 + bioMetrics.boundaryLayerMm * 14;
      const haloAlpha = Math.max(0.08, 0.5 - windSpeed * 0.045);

      const foliageCenterX = shootStemX + 15;
      const foliageCenterY = 110;

      const boundaryGrad = ctx.createRadialGradient(
        foliageCenterX,
        foliageCenterY,
        20,
        foliageCenterX,
        foliageCenterY,
        haloRadius
      );
      boundaryGrad.addColorStop(0, `rgba(56, 189, 248, ${haloAlpha * 1.5})`);
      boundaryGrad.addColorStop(0.6, `rgba(56, 189, 248, ${haloAlpha * 0.8})`);
      boundaryGrad.addColorStop(1, 'rgba(56, 189, 248, 0)');

      ctx.fillStyle = boundaryGrad;
      ctx.beginPath();
      ctx.arc(foliageCenterX, foliageCenterY, haloRadius, 0, Math.PI * 2);
      ctx.fill();

      // Boundary Layer Label Badge
      ctx.fillStyle = windSpeed === 0 ? '#38bdf8' : '#94a3b8';
      ctx.font = 'bold 11px sans-serif';
      ctx.textAlign = 'center';
      const blText =
        windSpeed === 0
          ? `Humid Boundary Layer: Saturated (${bioMetrics.boundaryLayerMm} mm)`
          : `Boundary Layer: Swept & Thin (${bioMetrics.boundaryLayerMm} mm)`;
      ctx.fillText(blText, foliageCenterX + 35, 36);

      // ======================================================================
      // 8. WATER VAPOR PARTICLES ANIMATION
      // ======================================================================
      // Particles emerging from leaves
      particlesRef.current.forEach((p) => {
        if (isPlaying) {
          // In Calm air: slow diffusive drifting upward, lingering near leaves
          // In Wind: strong lateral velocity to the right, swept away instantly
          if (windSpeed === 0) {
            p.x += p.vx + (Math.random() - 0.5) * 0.3;
            p.y += p.vy;
            p.alpha -= 0.006;
          } else {
            p.x += windSpeed * 1.8 + Math.random() * 0.5;
            p.y += (Math.random() - 0.5) * 0.6;
            p.alpha -= 0.015 + windSpeed * 0.003;
          }

          // Reset particle when faded or blown off screen
          if (p.alpha <= 0 || p.x > width || p.y < 20) {
            p.x = foliageCenterX - 20 + Math.random() * 60;
            p.y = foliageCenterY - 40 + Math.random() * 80;
            p.vx = (Math.random() - 0.5) * 0.5;
            p.vy = -0.3 - Math.random() * 0.6;
            p.alpha = 0.3 + Math.random() * 0.5;
          }
        }

        ctx.fillStyle = `rgba(186, 230, 253, ${p.alpha})`;
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
        ctx.fill();
      });

      animFrameIdRef.current = requestAnimationFrame(render);
    };

    animFrameIdRef.current = requestAnimationFrame(render);

    return () => {
      isRunning = false;
      if (animFrameIdRef.current) {
        cancelAnimationFrame(animFrameIdRef.current);
      }
    };
  }, [windSpeed, leafTreatment, isPlaying, bubblePos, tapAngle, isRefillingTap, bioMetrics]);

  // --------------------------------------------------------------------------
  // CANVAS ANIMATION: MICROSCOPIC STOMA & BOUNDARY LAYER VIEW
  // --------------------------------------------------------------------------
  useEffect(() => {
    if (activeView !== 'micro_stoma') return;

    const canvas = microCanvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    let width = (canvas.width = 800);
    let height = (canvas.height = 460);

    // Micro particles (H2O water vapor molecules diffusing through pore)
    if (microParticlesRef.current.length === 0) {
      for (let i = 0; i < 70; i++) {
        microParticlesRef.current.push({
          x: 350 + Math.random() * 100,
          y: 320 + Math.random() * 80,
          vx: (Math.random() - 0.5) * 0.8,
          vy: -0.5 - Math.random() * 1.2,
          alpha: 0.4 + Math.random() * 0.6,
          radius: 3 + Math.random() * 2,
        });
      }
    }

    let isRunning = true;

    const renderMicro = () => {
      if (!isRunning) return;

      ctx.clearRect(0, 0, width, height);

      // Microscopic Background
      const bg = ctx.createLinearGradient(0, 0, 0, height);
      bg.addColorStop(0, '#090d16');
      bg.addColorStop(0.5, '#0e1626');
      bg.addColorStop(1, '#050912');
      ctx.fillStyle = bg;
      ctx.fillRect(0, 0, width, height);

      // Boundary Line between Leaf Interior (Bottom) and Outside Air (Top)
      const stomaY = 240;
      const poreCenterX = 400;
      const poreWidth = lightState === 'bright' ? 36 : lightState === 'dim' ? 16 : 2;

      // ======================================================================
      // 1. LEAF CELLULAR ANATOMY (LOWER EPIDERMIS & MESOPHYLL)
      // ======================================================================
      // Sub-stomatal air cavity background
      ctx.fillStyle = '#064e3b'; // dark green internal leaf cavity
      ctx.fillRect(0, stomaY, width, height - stomaY);

      // Moist Mesophyll Cells with Water Film lining cell walls
      const cells = [
        { x: 120, y: 350, r: 45 },
        { x: 230, y: 380, r: 50 },
        { x: 570, y: 380, r: 52 },
        { x: 680, y: 350, r: 48 },
      ];

      cells.forEach((c) => {
        // Cell Wall
        ctx.fillStyle = '#15803d';
        ctx.beginPath();
        ctx.arc(c.x, c.y, c.r, 0, Math.PI * 2);
        ctx.fill();
        ctx.strokeStyle = '#22c55e';
        ctx.lineWidth = 3;
        ctx.stroke();

        // Water film on mesophyll wall (Evaporation surface!)
        ctx.strokeStyle = '#38bdf8';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.arc(c.x, c.y, c.r + 3, 0, Math.PI * 2);
        ctx.stroke();

        // Chloroplasts inside
        ctx.fillStyle = '#14532d';
        for (let i = 0; i < 6; i++) {
          const ang = (i * Math.PI) / 3;
          ctx.beginPath();
          ctx.ellipse(c.x + Math.cos(ang) * 22, c.y + Math.sin(ang) * 22, 7, 12, ang, 0, Math.PI * 2);
          ctx.fill();
        }
      });

      // Lower Epidermal Cells
      ctx.fillStyle = '#166534';
      ctx.strokeStyle = '#4ade80';
      ctx.lineWidth = 2;

      // Left Epidermis
      ctx.fillRect(0, stomaY - 25, poreCenterX - poreWidth - 45, 25);
      ctx.strokeRect(0, stomaY - 25, poreCenterX - poreWidth - 45, 25);

      // Right Epidermis
      ctx.fillRect(poreCenterX + poreWidth + 45, stomaY - 25, width - (poreCenterX + poreWidth + 45), 25);
      ctx.strokeRect(poreCenterX + poreWidth + 45, stomaY - 25, width - (poreCenterX + poreWidth + 45), 25);

      // ======================================================================
      // 2. PAIR OF GUARD CELLS FRAMING STOMATAL PORE
      // ======================================================================
      // Left Guard Cell
      ctx.fillStyle = '#22c55e';
      ctx.beginPath();
      ctx.ellipse(poreCenterX - poreWidth / 2 - 20, stomaY - 12, 22, 28, -0.15, 0, Math.PI * 2);
      ctx.fill();
      // Inner thick cellulose wall facing pore
      ctx.strokeStyle = '#14532d';
      ctx.lineWidth = 5;
      ctx.stroke();

      // Right Guard Cell
      ctx.fillStyle = '#22c55e';
      ctx.beginPath();
      ctx.ellipse(poreCenterX + poreWidth / 2 + 20, stomaY - 12, 22, 28, 0.15, 0, Math.PI * 2);
      ctx.fill();
      // Inner thick cellulose wall facing pore
      ctx.strokeStyle = '#14532d';
      ctx.lineWidth = 5;
      ctx.stroke();

      // Guard cell chloroplasts
      ctx.fillStyle = '#166534';
      ctx.beginPath();
      ctx.arc(poreCenterX - poreWidth / 2 - 22, stomaY - 18, 4, 0, Math.PI * 2);
      ctx.arc(poreCenterX - poreWidth / 2 - 20, stomaY - 6, 4, 0, Math.PI * 2);
      ctx.arc(poreCenterX + poreWidth / 2 + 22, stomaY - 18, 4, 0, Math.PI * 2);
      ctx.arc(poreCenterX + poreWidth / 2 + 20, stomaY - 6, 4, 0, Math.PI * 2);
      ctx.fill();

      // Stomatal Pore Opening Label
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 11px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(
        lightState === 'bright' ? 'Open Stomatal Pore' : lightState === 'dim' ? 'Partly Closed Pore' : 'Closed Stoma',
        poreCenterX,
        stomaY + 30
      );

      // Sub-stomatal humidity badge
      ctx.fillStyle = '#38bdf8';
      ctx.font = '11px sans-serif';
      ctx.fillText('Sub-Stomatal Cavity (100% Saturated Vapor)', poreCenterX, height - 30);

      // Vaseline Blockade if Lower Coated
      if (leafTreatment === 'lower' || leafTreatment === 'both') {
        ctx.fillStyle = 'rgba(250, 204, 21, 0.85)';
        ctx.fillRect(poreCenterX - 60, stomaY - 32, 120, 10);
        ctx.fillStyle = '#713f12';
        ctx.font = 'bold 9px sans-serif';
        ctx.fillText('VASELINE BARRIER (PORE BLOCKED)', poreCenterX, stomaY - 24);
      }

      // ======================================================================
      // 3. DIFFUSIVE BOUNDARY LAYER GRADIENT (OUTSIDE STOMA)
      // ======================================================================
      // Boundary layer height on screen:
      // In still air (v=0): spans ~140px above stoma (gentle gradient)
      // In high wind (v=9): compressed to ~20px above stoma (steep gradient)
      const blScreenHeight = 20 + bioMetrics.boundaryLayerMm * 30;

      const blGrad = ctx.createLinearGradient(0, stomaY - 25, 0, stomaY - 25 - blScreenHeight);
      blGrad.addColorStop(0, 'rgba(56, 189, 248, 0.55)');
      blGrad.addColorStop(0.5, 'rgba(56, 189, 248, 0.25)');
      blGrad.addColorStop(1, 'rgba(56, 189, 248, 0.02)');

      ctx.fillStyle = blGrad;
      ctx.fillRect(0, stomaY - 25 - blScreenHeight, width, blScreenHeight);

      // Boundary Layer Border Line
      ctx.strokeStyle = '#38bdf8';
      ctx.setLineDash([6, 6]);
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(0, stomaY - 25 - blScreenHeight);
      ctx.lineTo(width, stomaY - 25 - blScreenHeight);
      ctx.stroke();
      ctx.setLineDash([]);

      // Boundary Layer Annotation
      ctx.fillStyle = '#38bdf8';
      ctx.font = 'bold 11px sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(
        `← Diffusive Boundary Layer Boundary (δ ≈ ${bioMetrics.boundaryLayerMm} mm)`,
        20,
        stomaY - 30 - blScreenHeight
      );

      // Bulk Atmosphere Label above
      ctx.fillStyle = '#94a3b8';
      ctx.fillText(
        `Bulk Atmosphere: ${ambientHumidity}% RH • Wind Speed: ${windSpeed} m/s`,
        20,
        Math.max(25, stomaY - 50 - blScreenHeight)
      );

      // Wind Flow Vectors in Bulk Air
      if (windSpeed > 0) {
        ctx.strokeStyle = 'rgba(56, 189, 248, 0.7)';
        ctx.lineWidth = 2;
        const time = Date.now() * 0.005;
        for (let w = 0; w < 4; w++) {
          const arrowX = ((time * 120 * (windSpeed * 0.3) + w * 220) % (width + 100)) - 50;
          const arrowY = 40 + w * 25;
          ctx.beginPath();
          ctx.moveTo(arrowX, arrowY);
          ctx.lineTo(arrowX + 45, arrowY);
          ctx.stroke();
          // Head
          ctx.beginPath();
          ctx.moveTo(arrowX + 45, arrowY);
          ctx.lineTo(arrowX + 37, arrowY - 4);
          ctx.lineTo(arrowX + 37, arrowY + 4);
          ctx.closePath();
          ctx.fillStyle = '#38bdf8';
          ctx.fill();
        }
      }

      // ======================================================================
      // 4. WATER MOLECULES DIFFUSING THROUGH STOMA
      // ======================================================================
      microParticlesRef.current.forEach((p) => {
        if (isPlaying) {
          // If below stoma: random thermal motion in sub-stomatal cavity
          if (p.y > stomaY - 25) {
            p.x += (Math.random() - 0.5) * 1.2;
            p.y += -0.4 - Math.random() * 0.8;
          } else {
            // Above stoma in boundary layer or bulk air
            if (windSpeed === 0) {
              // Still air: water molecules accumulate right above the pore, diffusing very slowly!
              p.x += (Math.random() - 0.5) * 0.8;
              p.y += -0.3 - Math.random() * 0.4;
              p.alpha -= 0.005;
            } else {
              // High wind: swept violently to the right!
              p.x += windSpeed * 2.2 + Math.random() * 1.2;
              p.y += (Math.random() - 0.5) * 0.8;
              p.alpha -= 0.018;
            }
          }

          // Respawn from wet mesophyll cell walls
          if (p.alpha <= 0 || p.x > width || p.y < 10) {
            p.x = poreCenterX - poreWidth / 2 + Math.random() * poreWidth;
            p.y = stomaY + 20 + Math.random() * 60;
            p.alpha = 0.6 + Math.random() * 0.4;
          }
        }

        // Draw H2O Molecule
        ctx.fillStyle = `rgba(125, 211, 252, ${p.alpha})`;
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
        ctx.fill();
      });

      animFrameIdRef.current = requestAnimationFrame(renderMicro);
    };

    animFrameIdRef.current = requestAnimationFrame(renderMicro);

    return () => {
      isRunning = false;
      if (animFrameIdRef.current) {
        cancelAnimationFrame(animFrameIdRef.current);
      }
    };
  }, [activeView, windSpeed, lightState, leafTreatment, ambientHumidity, isPlaying, bioMetrics]);

  // --------------------------------------------------------------------------
  // QUIZ HANDLING
  // --------------------------------------------------------------------------
  const handleSelectAnswer = (optionId) => {
    setUserAnswers((prev) => ({
      ...prev,
      [KCSE_QUESTIONS[currentQuestionIdx].id]: optionId,
    }));
  };

  const handleNextQuestion = () => {
    if (currentQuestionIdx < KCSE_QUESTIONS.length - 1) {
      setCurrentQuestionIdx((prev) => prev + 1);
      setShowExplanation(false);
    } else {
      // Calculate final score
      let score = 0;
      KCSE_QUESTIONS.forEach((q) => {
        const correctOpt = q.options.find((o) => o.correct);
        if (userAnswers[q.id] === correctOpt.id) {
          score += 1;
        }
      });
      setQuizScore(score);

      if (score >= 3) {
        setCheckpoints((prev) => ({ ...prev, quiz_completed: true }));
        triggerTelemetry('PLANT_TRANSPIRATION_QUIZ_COMPLETED', {
          score,
          total: KCSE_QUESTIONS.length,
          percentage: Math.round((score / KCSE_QUESTIONS.length) * 100),
        });
      }
    }
  };

  const handleResetQuiz = () => {
    setUserAnswers({});
    setCurrentQuestionIdx(0);
    setShowExplanation(false);
    setQuizScore(null);
  };

  return (
    <div className="w-full min-h-screen bg-slate-950 text-slate-100 p-3 sm:p-5 font-sans">
      <div className="max-w-7xl mx-auto space-y-5">
        {/* ================================================================== */}
        {/* SIMULATION HEADER & LEARNING OBJECTIVES                            */}
        {/* ================================================================== */}
        <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-5 shadow-xl backdrop-blur">
          <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4">
            <div className="flex items-center gap-3.5">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-teal-500 to-sky-600 flex items-center justify-center shadow-lg shadow-sky-500/20">
                <Wind className="w-6 h-6 text-white" />
              </div>
              <div>
                <div className="flex items-center gap-2 flex-wrap">
                  <h1 className="text-xl sm:text-2xl font-black tracking-tight text-white">
                    Plant Transpiration Rate: Wind & Boundary Layer Dynamics
                  </h1>
                  <span className="text-xs font-semibold px-2.5 py-0.5 rounded-full bg-teal-500/10 text-teal-400 border border-teal-500/30">
                    Grade 10 Biology • Topic 2
                  </span>
                </div>
                <p className="text-xs sm:text-sm text-slate-400 mt-1">
                  Ganong’s Potometer Lab: Investigate how air movement sweeps away the humid boundary layer to steepen
                  the diffusion gradient and accelerate water uptake.
                </p>
              </div>
            </div>

            {/* Quick Action Controls */}
            <div className="flex items-center gap-2 self-stretch lg:self-auto justify-end">
              <button
                onClick={() => setIsPlaying(!isPlaying)}
                className={`flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold transition-all ${
                  isPlaying
                    ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30 hover:bg-amber-500/30'
                    : 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 hover:bg-emerald-500/30'
                }`}
                title={isPlaying ? 'Pause Simulation' : 'Resume Simulation'}
              >
                {isPlaying ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}
                {isPlaying ? 'Pause' : 'Resume'}
              </button>

              <button
                onClick={handleFullReset}
                className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition-all"
                title="Reset to Calm Baseline (0 m/s)"
              >
                <RotateCcw className="w-4 h-4" />
                Reset Baseline
              </button>
            </div>
          </div>

          {/* Key Metric Status Badges */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4 pt-4 border-t border-slate-800/80">
            <div className="bg-slate-950/60 rounded-xl p-2.5 border border-slate-800">
              <div className="text-[11px] font-medium text-slate-400 flex items-center gap-1">
                <Wind className="w-3.5 h-3.5 text-sky-400" />
                Wind Speed
              </div>
              <div className="text-lg font-extrabold text-sky-300 mt-0.5">
                {windSpeed} <span className="text-xs font-normal text-slate-400">m/s</span>
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">
                {windSpeed === 0 ? 'Calm / Still Air' : windSpeed >= 6 ? 'High Wind / Gale' : 'Breezy'}
              </div>
            </div>

            <div className="bg-slate-950/60 rounded-xl p-2.5 border border-slate-800">
              <div className="text-[11px] font-medium text-slate-400 flex items-center gap-1">
                <Gauge className="w-3.5 h-3.5 text-emerald-400" />
                Transpiration Rate
              </div>
              <div className={`text-lg font-extrabold ${bioMetrics.rateColor} mt-0.5`}>
                {bioMetrics.transpirationRate} <span className="text-xs font-normal text-slate-400">ml/h</span>
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">{bioMetrics.rateCategory}</div>
            </div>

            <div className="bg-slate-950/60 rounded-xl p-2.5 border border-slate-800">
              <div className="text-[11px] font-medium text-slate-400 flex items-center gap-1">
                <Layers className="w-3.5 h-3.5 text-amber-400" />
                Boundary Layer (δ)
              </div>
              <div className="text-lg font-extrabold text-amber-300 mt-0.5">
                {bioMetrics.boundaryLayerMm} <span className="text-xs font-normal text-slate-400">mm</span>
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">
                {windSpeed === 0 ? 'Trapped humid halo' : 'Swept away by air'}
              </div>
            </div>

            <div className="bg-slate-950/60 rounded-xl p-2.5 border border-slate-800">
              <div className="text-[11px] font-medium text-slate-400 flex items-center gap-1">
                <Activity className="w-3.5 h-3.5 text-indigo-400" />
                Capillary Bubble Speed
              </div>
              <div className="text-lg font-extrabold text-indigo-300 mt-0.5">
                {bioMetrics.bubbleSpeedMmMin} <span className="text-xs font-normal text-slate-400">mm/min</span>
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Potometer meniscus drift</div>
            </div>
          </div>
        </div>

        {/* ================================================================== */}
        {/* NAVIGATION TABS                                                    */}
        {/* ================================================================== */}
        <div className="flex items-center gap-2 border-b border-slate-800 pb-2 overflow-x-auto">
          <button
            onClick={() => setActiveTab('experiment')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs sm:text-sm font-bold transition-all ${
              activeTab === 'experiment'
                ? 'bg-teal-600 text-white shadow-lg shadow-teal-600/20'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            <Sliders className="w-4 h-4" />
            Interactive Lab
          </button>

          <button
            onClick={() => setActiveTab('analysis')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs sm:text-sm font-bold transition-all ${
              activeTab === 'analysis'
                ? 'bg-teal-600 text-white shadow-lg shadow-teal-600/20'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            <Table className="w-4 h-4" />
            Data Logger & Graphs ({dataLog.length})
          </button>

          <button
            onClick={() => setActiveTab('theory')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs sm:text-sm font-bold transition-all ${
              activeTab === 'theory'
                ? 'bg-teal-600 text-white shadow-lg shadow-teal-600/20'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            <BookOpen className="w-4 h-4" />
            Biology Concepts & Fick’s Law
          </button>

          <button
            onClick={() => setActiveTab('quiz')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs sm:text-sm font-bold transition-all ${
              activeTab === 'quiz'
                ? 'bg-teal-600 text-white shadow-lg shadow-teal-600/20'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            <Award className="w-4 h-4" />
            KCSE Exam Readiness
          </button>
        </div>

        {/* ================================================================== */}
        {/* TAB 1: INTERACTIVE LAB BENCH                                       */}
        {/* ================================================================== */}
        {activeTab === 'experiment' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
            {/* Left 8 Cols: Visualizer & View Mode */}
            <div className="lg:col-span-8 space-y-4">
              <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-4 shadow-xl">
                {/* Visualizer Header Toolbar */}
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-3">
                  <div className="flex items-center gap-2 bg-slate-950/80 p-1 rounded-2xl border border-slate-800">
                    <button
                      onClick={() => setActiveView('potometer')}
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                        activeView === 'potometer'
                          ? 'bg-teal-600 text-white shadow'
                          : 'text-slate-400 hover:text-white'
                      }`}
                    >
                      <Beaker className="w-3.5 h-3.5" />
                      Potometer Setup (Macro)
                    </button>
                    <button
                      onClick={() => setActiveView('micro_stoma')}
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                        activeView === 'micro_stoma'
                          ? 'bg-teal-600 text-white shadow'
                          : 'text-slate-400 hover:text-white'
                      }`}
                    >
                      <Microscope className="w-3.5 h-3.5" />
                      Stoma & Boundary Layer (Micro)
                    </button>
                  </div>

                  {/* Reservoir Tap Reset Button */}
                  <button
                    onClick={handleResetBubble}
                    disabled={isRefillingTap}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold bg-amber-500/20 text-amber-300 border border-amber-500/40 hover:bg-amber-500/30 transition-all disabled:opacity-50"
                  >
                    <RefreshCw className={`w-3.5 h-3.5 ${isRefillingTap ? 'animate-spin' : ''}`} />
                    Turn Tap (Reset Bubble to 0 mm)
                  </button>
                </div>

                {/* Canvas Container */}
                <div className="relative rounded-2xl overflow-hidden border border-slate-800 bg-slate-950 aspect-[800/460] shadow-inner">
                  {activeView === 'potometer' ? (
                    <canvas ref={potometerCanvasRef} className="w-full h-full object-contain block" />
                  ) : (
                    <canvas ref={microCanvasRef} className="w-full h-full object-contain block" />
                  )}

                  {/* Interactive Overlays on Canvas */}
                  <div className="absolute bottom-3 left-3 bg-slate-950/80 backdrop-blur border border-slate-800 px-3 py-1.5 rounded-xl text-[11px] text-slate-300 flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                    <span>
                      {activeView === 'potometer'
                        ? `Bubble: ${bubblePos.toFixed(1)} mm • Timer: ${elapsedTimeSec}s`
                        : `Stomatal Diffusion Gradient: ${bioMetrics.gradientDesc}`}
                    </span>
                  </div>

                  {/* Biological Callout Box on Canvas */}
                  <div className="absolute top-3 right-3 max-w-[240px] bg-slate-900/90 backdrop-blur border border-slate-700/60 p-2.5 rounded-xl text-[11px] text-slate-300 shadow-lg pointer-events-none hidden sm:block">
                    <div className="font-bold text-teal-300 flex items-center gap-1 mb-1">
                      <Sparkles className="w-3.5 h-3.5 text-teal-400" />
                      Biological Consequence:
                    </div>
                    {windSpeed === 0 ? (
                      <p className="text-slate-300 leading-tight">
                        <strong className="text-white">Still Air:</strong> Evaporated water forms a dense humid boundary
                        layer hugging the leaf. The gentle gradient keeps transpiration slow.
                      </p>
                    ) : (
                      <p className="text-slate-300 leading-tight">
                        <strong className="text-sky-300">High Wind:</strong> Air movement sweeps the boundary layer
                        away, creating a very steep diffusion gradient. Transpiration surges!
                      </p>
                    )}
                  </div>
                </div>

                {/* Potometer Capillary Status Bar */}
                <div className="mt-3 p-3 rounded-2xl bg-slate-950/70 border border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs">
                  <div className="flex items-center gap-2">
                    <div className="w-2.5 h-2.5 rounded-full bg-sky-400 animate-ping" />
                    <span className="text-slate-300">
                      Capillary Scale: <strong>{bubblePos.toFixed(1)} / 100 mm</strong> (Bubble drifts at{' '}
                      <strong className="text-indigo-300">{bioMetrics.bubbleSpeedMmMin} mm/min</strong>)
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleRecordData}
                      className="px-3 py-1.5 rounded-xl text-xs font-bold bg-teal-600 hover:bg-teal-500 text-white shadow transition-all flex items-center gap-1.5"
                    >
                      <Table className="w-3.5 h-3.5" />
                      Log Trial in Notebook
                    </button>
                  </div>
                </div>
              </div>

              {/* Guided Learning Checkpoints Card */}
              <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-4 shadow-xl">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-bold text-white flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-teal-400" />
                    Guided Experimental Checkpoints
                  </h3>
                  <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-slate-800 text-slate-300">
                    {Object.values(checkpoints).filter(Boolean).length} / 5 Done
                  </span>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                  <div
                    className={`p-2.5 rounded-xl border flex items-center gap-2.5 ${
                      checkpoints.calm_observed
                        ? 'bg-teal-950/40 border-teal-500/40 text-teal-200'
                        : 'bg-slate-950/40 border-slate-800 text-slate-400'
                    }`}
                  >
                    {checkpoints.calm_observed ? (
                      <CheckCircle2 className="w-4 h-4 text-teal-400 shrink-0" />
                    ) : (
                      <div className="w-4 h-4 rounded-full border border-slate-600 shrink-0" />
                    )}
                    <span>1. Observe Calm Air (0 m/s) boundary layer halo</span>
                  </div>

                  <div
                    className={`p-2.5 rounded-xl border flex items-center gap-2.5 ${
                      checkpoints.wind_tested
                        ? 'bg-teal-950/40 border-teal-500/40 text-teal-200'
                        : 'bg-slate-950/40 border-slate-800 text-slate-400'
                    }`}
                  >
                    {checkpoints.wind_tested ? (
                      <CheckCircle2 className="w-4 h-4 text-teal-400 shrink-0" />
                    ) : (
                      <div className="w-4 h-4 rounded-full border border-slate-600 shrink-0" />
                    )}
                    <span>2. Increase Wind to ≥ 6 m/s & see vapor sweep</span>
                  </div>

                  <div
                    className={`p-2.5 rounded-xl border flex items-center gap-2.5 ${
                      checkpoints.bubble_reset_used
                        ? 'bg-teal-950/40 border-teal-500/40 text-teal-200'
                        : 'bg-slate-950/40 border-slate-800 text-slate-400'
                    }`}
                  >
                    {checkpoints.bubble_reset_used ? (
                      <CheckCircle2 className="w-4 h-4 text-teal-400 shrink-0" />
                    ) : (
                      <div className="w-4 h-4 rounded-full border border-slate-600 shrink-0" />
                    )}
                    <span>3. Use Reservoir Tap to reset air bubble</span>
                  </div>

                  <div
                    className={`p-2.5 rounded-xl border flex items-center gap-2.5 ${
                      checkpoints.vaseline_tested
                        ? 'bg-teal-950/40 border-teal-500/40 text-teal-200'
                        : 'bg-slate-950/40 border-slate-800 text-slate-400'
                    }`}
                  >
                    {checkpoints.vaseline_tested ? (
                      <CheckCircle2 className="w-4 h-4 text-teal-400 shrink-0" />
                    ) : (
                      <div className="w-4 h-4 rounded-full border border-slate-600 shrink-0" />
                    )}
                    <span>4. Test Vaseline on Lower Epidermis</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Right 4 Cols: Interactive Controls Panel */}
            <div className="lg:col-span-4 space-y-4">
              {/* PRIMARY VARIABLE: WIND SPEED */}
              <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-5 shadow-xl">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-sky-400 flex items-center gap-1.5">
                    <Wind className="w-4 h-4" />
                    Primary Variable
                  </span>
                  <span className="text-xs font-mono bg-sky-500/20 text-sky-300 px-2 py-0.5 rounded-full border border-sky-500/30">
                    {windSpeed} m/s
                  </span>
                </div>

                <h3 className="text-base font-bold text-white mb-1">Fan Wind Velocity</h3>
                <p className="text-xs text-slate-400 mb-4">
                  Controls the rate of air displacement across the leaf surface.
                </p>

                {/* Wind Slider */}
                <input
                  type="range"
                  min="0"
                  max="10"
                  step="0.5"
                  value={windSpeed}
                  onChange={(e) => setWindSpeed(parseFloat(e.target.value))}
                  className="w-full h-2.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400 mb-3"
                />

                <div className="flex justify-between text-[10px] text-slate-400 font-mono mb-4">
                  <span>0 (Still Air / Calm)</span>
                  <span>5.0 (Breeze)</span>
                  <span>10.0 (High Wind)</span>
                </div>

                {/* Wind Presets */}
                <div className="grid grid-cols-2 gap-2">
                  {WIND_PRESETS.map((p) => (
                    <button
                      key={p.id}
                      onClick={() => setWindSpeed(p.speed)}
                      className={`p-2.5 rounded-xl text-left border transition-all text-xs ${
                        windSpeed === p.speed
                          ? 'bg-sky-500/20 border-sky-500/50 text-white shadow-sm'
                          : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:text-slate-200 hover:bg-slate-800/60'
                      }`}
                    >
                      <div className="font-bold">{p.name}</div>
                      <div className="text-[10px] text-slate-500 mt-0.5">{p.speed} m/s</div>
                    </button>
                  ))}
                </div>
              </div>

              {/* SECONDARY PRACTICAL: PETROLEUM JELLY (VASELINE) LEAF COATING */}
              <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-5 shadow-xl">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-amber-400 flex items-center gap-1.5">
                    <ShieldCheck className="w-4 h-4" />
                    Practical Investigation
                  </span>
                  <span className="text-xs text-amber-300 font-semibold">Stomatal Distribution</span>
                </div>

                <h3 className="text-base font-bold text-white mb-1">Petroleum Jelly Treatment</h3>
                <p className="text-xs text-slate-400 mb-3">
                  Smearing vaseline physically blocks stomatal pores on the selected epidermis.
                </p>

                <div className="space-y-2">
                  {LEAF_TREATMENTS.map((t) => (
                    <label
                      key={t.id}
                      onClick={() => setLeafTreatment(t.id)}
                      className={`flex items-start gap-2.5 p-2.5 rounded-xl border cursor-pointer transition-all ${
                        leafTreatment === t.id
                          ? 'bg-amber-500/10 border-amber-500/40 text-amber-200'
                          : 'bg-slate-950/50 border-slate-800 text-slate-400 hover:bg-slate-800/50'
                      }`}
                    >
                      <input
                        type="radio"
                        name="leafTreatment"
                        checked={leafTreatment === t.id}
                        onChange={() => setLeafTreatment(t.id)}
                        className="mt-1 accent-amber-400"
                      />
                      <div>
                        <div className="text-xs font-bold text-white">{t.label}</div>
                        <div className="text-[11px] text-slate-400 mt-0.5">{t.desc}</div>
                      </div>
                    </label>
                  ))}
                </div>
              </div>

              {/* ENVIRONMENTAL MODIFIERS: HUMIDITY & LIGHT */}
              <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-5 shadow-xl space-y-4">
                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                  <Sun className="w-4 h-4 text-teal-400" />
                  Additional Environmental Factors
                </h3>

                {/* Ambient Humidity */}
                <div>
                  <div className="flex justify-between text-xs mb-1.5">
                    <span className="text-slate-300">Ambient Air Humidity:</span>
                    <span className="font-mono text-sky-400 font-bold">{ambientHumidity}% RH</span>
                  </div>
                  <input
                    type="range"
                    min="20"
                    max="90"
                    step="5"
                    value={ambientHumidity}
                    onChange={(e) => setAmbientHumidity(parseInt(e.target.value))}
                    className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-sky-400"
                  />
                  <div className="flex justify-between text-[10px] text-slate-500 font-mono mt-1">
                    <span>Dry (20%)</span>
                    <span>Standard (50%)</span>
                    <span>Humid (90%)</span>
                  </div>
                </div>

                {/* Stomatal State (Light Condition) */}
                <div>
                  <div className="text-xs text-slate-300 mb-1.5">Light & Stomatal Aperture:</div>
                  <div className="grid grid-cols-3 gap-1.5">
                    <button
                      onClick={() => setLightState('bright')}
                      className={`py-1.5 px-2 rounded-xl text-xs font-semibold border transition-all ${
                        lightState === 'bright'
                          ? 'bg-teal-500/20 border-teal-500/50 text-teal-200'
                          : 'bg-slate-950/60 border-slate-800 text-slate-400'
                      }`}
                    >
                      Bright (Open)
                    </button>
                    <button
                      onClick={() => setLightState('dim')}
                      className={`py-1.5 px-2 rounded-xl text-xs font-semibold border transition-all ${
                        lightState === 'dim'
                          ? 'bg-teal-500/20 border-teal-500/50 text-teal-200'
                          : 'bg-slate-950/60 border-slate-800 text-slate-400'
                      }`}
                    >
                      Dim (Partial)
                    </button>
                    <button
                      onClick={() => setLightState('dark')}
                      className={`py-1.5 px-2 rounded-xl text-xs font-semibold border transition-all ${
                        lightState === 'dark'
                          ? 'bg-teal-500/20 border-teal-500/50 text-teal-200'
                          : 'bg-slate-950/60 border-slate-800 text-slate-400'
                      }`}
                    >
                      Dark (Closed)
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ================================================================== */}
        {/* TAB 2: DATA LOGGER & COMPARISON GRAPHS                            */}
        {/* ================================================================== */}
        {activeTab === 'analysis' && (
          <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-6">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div>
                <h2 className="text-xl font-bold text-white flex items-center gap-2">
                  <Table className="w-5 h-5 text-teal-400" />
                  Potometer Experimental Notebook & Graph
                </h2>
                <p className="text-xs sm:text-sm text-slate-400 mt-1">
                  Plotting Wind Speed (m/s) versus Transpiration Rate (ml/h) and Capillary Bubble Movement.
                </p>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleRecordData}
                  className="px-4 py-2 rounded-xl text-xs font-bold bg-teal-600 hover:bg-teal-500 text-white shadow transition-all flex items-center gap-1.5"
                >
                  <Table className="w-3.5 h-3.5" />
                  Record Current Trial
                </button>
                <button
                  onClick={() => setDataLog([])}
                  className="px-3 py-2 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700"
                >
                  Clear Table
                </button>
              </div>
            </div>

            {/* Simulated Live SVG Graph: Transpiration Rate vs Wind Speed */}
            <div className="bg-slate-950 rounded-2xl p-4 border border-slate-800">
              <div className="text-xs font-bold text-slate-300 mb-2 flex items-center justify-between">
                <span>Curve: Transpiration Rate (ml/h) vs Wind Speed (m/s)</span>
                <span className="text-[11px] text-teal-400 font-mono">Current: {bioMetrics.transpirationRate} ml/h @ {windSpeed} m/s</span>
              </div>

              <div className="w-full h-56 relative flex items-end">
                {/* SVG Graph Plot */}
                <svg className="w-full h-full" viewBox="0 0 600 200" preserveAspectRatio="none">
                  {/* Grid Lines */}
                  <line x1="40" y1="20" x2="580" y2="20" stroke="#1e293b" strokeWidth="1" />
                  <line x1="40" y1="65" x2="580" y2="65" stroke="#1e293b" strokeWidth="1" />
                  <line x1="40" y1="110" x2="580" y2="110" stroke="#1e293b" strokeWidth="1" />
                  <line x1="40" y1="155" x2="580" y2="155" stroke="#1e293b" strokeWidth="1" />

                  {/* Axes */}
                  <line x1="40" y1="15" x2="40" y2="175" stroke="#475569" strokeWidth="2" />
                  <line x1="40" y1="175" x2="580" y2="175" stroke="#475569" strokeWidth="2" />

                  {/* Reference Curve: Theoretical Transpiration Curve */}
                  <path
                    d="M 40 155 Q 160 80, 320 42 T 580 32"
                    fill="none"
                    stroke="#0284c7"
                    strokeWidth="3"
                    strokeDasharray="4,4"
                  />

                  {/* Plotted Data Points */}
                  {dataLog.map((pt, i) => {
                    const plotX = 40 + (pt.windSpeed / 10) * 540;
                    const numRate = parseFloat(pt.rate);
                    const plotY = 175 - (numRate / 28) * 155;
                    return (
                      <g key={pt.id || i}>
                        <circle cx={plotX} cy={plotY} r="6" fill="#14b8a6" stroke="#ffffff" strokeWidth="2" />
                        <text x={plotX} y={plotY - 10} fill="#5eead4" fontSize="10" textAnchor="middle" fontWeight="bold">
                          {pt.rate}
                        </text>
                      </g>
                    );
                  })}

                  {/* Current Operating Point Marker */}
                  <circle
                    cx={40 + (windSpeed / 10) * 540}
                    cy={175 - (bioMetrics.transpirationRate / 28) * 155}
                    r="8"
                    fill="#f43f5e"
                    className="animate-pulse"
                  />
                </svg>
              </div>

              <div className="flex justify-between text-[11px] text-slate-500 font-mono px-8 mt-2">
                <span>0 m/s (Calm)</span>
                <span>2.5 m/s</span>
                <span>5.0 m/s</span>
                <span>7.5 m/s</span>
                <span>10.0 m/s (Gale)</span>
              </div>
            </div>

            {/* Logged Data Table */}
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-950 border-b border-slate-800 text-slate-400 font-semibold">
                    <th className="py-3 px-4">Trial #</th>
                    <th className="py-3 px-4">Wind Speed</th>
                    <th className="py-3 px-4">Condition</th>
                    <th className="py-3 px-4">Capillary Bubble Speed</th>
                    <th className="py-3 px-4">Transpiration Rate</th>
                    <th className="py-3 px-4">Boundary Layer (δ)</th>
                    <th className="py-3 px-4">Diffusion Gradient</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60">
                  {dataLog.map((row) => (
                    <tr key={row.id} className="hover:bg-slate-800/30 transition-colors">
                      <td className="py-3 px-4 font-mono text-slate-400">#{row.id}</td>
                      <td className="py-3 px-4 font-bold text-sky-400">{row.windSpeed} m/s</td>
                      <td className="py-3 px-4 text-slate-300">{row.condition}</td>
                      <td className="py-3 px-4 font-mono text-indigo-300">{row.bubbleSpeed}</td>
                      <td className="py-3 px-4 font-bold text-emerald-400">{row.rate}</td>
                      <td className="py-3 px-4 text-amber-300 font-mono">{row.boundaryLayer}</td>
                      <td className="py-3 px-4 text-slate-300">{row.gradient}</td>
                    </tr>
                  ))}
                  {dataLog.length === 0 && (
                    <tr>
                      <td colSpan={7} className="py-6 text-center text-slate-500">
                        No trials logged yet. Switch to the interactive lab and click &quot;Log Trial in Notebook&quot;.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* ================================================================== */}
        {/* TAB 3: BIOLOGY CONCEPTS & FICK'S LAW                               */}
        {/* ================================================================== */}
        {activeTab === 'theory' && (
          <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-6">
            <div>
              <h2 className="text-xl font-bold text-white flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-teal-400" />
                Biological Principles of Transpiration & Boundary Layer Dynamics
              </h2>
              <p className="text-xs sm:text-sm text-slate-400 mt-1">
                Grade 10 Plant Physiology: Fick’s First Law of Diffusion and Stomatal Water Relations.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {/* Concept 1: The Boundary Layer */}
              <div className="bg-slate-950 p-5 rounded-2xl border border-slate-800 space-y-3">
                <div className="w-10 h-10 rounded-xl bg-sky-500/20 text-sky-400 flex items-center justify-center font-bold">
                  1
                </div>
                <h3 className="text-base font-bold text-white">The Diffusive Boundary Layer (δ)</h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  When water evaporates from moist mesophyll surfaces through open stomata into still air, it does not
                  disperse immediately into the room. Instead, it accumulates in a thin, stagnant layer of humid air
                  clinging to the leaf surface, known as the <strong>diffusive boundary layer</strong>.
                </p>
                <div className="p-3 bg-slate-900 rounded-xl border border-slate-800 text-xs text-sky-300 space-y-1">
                  <p>
                    <strong>In Calm Air:</strong> δ ≈ 3.5 – 4.0 mm. External humidity matches sub-stomatal cavity →
                    Gentle diffusion gradient → Slow transpiration.
                  </p>
                  <p>
                    <strong>In High Wind:</strong> Air movement shears and strips δ down to &lt;0.5 mm → Direct contact
                    with dry air → Steep diffusion gradient → Rapid transpiration.
                  </p>
                </div>
              </div>

              {/* Concept 2: Fick's Law of Diffusion */}
              <div className="bg-slate-950 p-5 rounded-2xl border border-slate-800 space-y-3">
                <div className="w-10 h-10 rounded-xl bg-teal-500/20 text-teal-400 flex items-center justify-center font-bold">
                  2
                </div>
                <h3 className="text-base font-bold text-white">Fick’s First Law Applied to Transpiration</h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  The rate of water vapor diffusion ($E$) across the leaf epidermis obeys Fick’s Law of diffusion:
                </p>
                <div className="p-3 bg-slate-900 rounded-xl border border-slate-800 text-center font-mono text-xs text-emerald-300 font-bold">
                  Transpiration Rate (E) = (D × A × ΔC) / (r_stomata + r_boundary)
                </div>
                <ul className="text-xs text-slate-400 space-y-1 list-disc list-inside">
                  <li>
                    <strong className="text-white">ΔC (Gradient):</strong> Concentration difference between leaf air space
                    (100% RH) and outer atmosphere.
                  </li>
                  <li>
                    <strong className="text-white">r_boundary:</strong> Resistance imposed by boundary layer. High wind
                    makes this resistance approach zero!
                  </li>
                  <li>
                    <strong className="text-white">r_stomata:</strong> Resistance of stomatal pores governed by guard
                    cell turgor.
                  </li>
                </ul>
              </div>

              {/* Concept 3: Cohesion-Tension Theory in Potometer */}
              <div className="bg-slate-950 p-5 rounded-2xl border border-slate-800 space-y-3">
                <div className="w-10 h-10 rounded-xl bg-indigo-500/20 text-indigo-400 flex items-center justify-center font-bold">
                  3
                </div>
                <h3 className="text-base font-bold text-white">Cohesion-Tension & Potometer Working</h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  Water molecules form continuous hydrogen-bonded columns extending from the capillary tube through the cut
                  stem up to leaf veins. Evaporation generates negative hydrostatic pressure (<strong>transpiration pull</strong>),
                  drawing the air bubble forward along the graduated tube.
                </p>
                <div className="p-3 bg-slate-900 rounded-xl border border-slate-800 text-xs text-indigo-300">
                  <strong>Crucial Exam Precaution:</strong> The stem MUST be cut under water to prevent air from entering
                  xylem vessels, which would cause an air embolism (cavitation) and break cohesion.
                </div>
              </div>

              {/* Concept 4: Xerophytic Adaptations to Wind */}
              <div className="bg-slate-950 p-5 rounded-2xl border border-slate-800 space-y-3">
                <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center font-bold">
                  4
                </div>
                <h3 className="text-base font-bold text-white">Plant Adaptations Against Wind Desiccation</h3>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  Plants growing in windy or arid environments (xerophytes) evolve anatomical modifications to physically
                  trap their boundary layer even during high winds:
                </p>
                <ul className="text-xs text-slate-300 space-y-1.5 list-disc list-inside">
                  <li>
                    <strong>Epidermal Trichomes (Hairs):</strong> Create micro-pockets of motionless air over the leaf
                    surface, shielding the boundary layer from wind.
                  </li>
                  <li>
                    <strong>Sunken Stomata in Pits:</strong> Keeps the stomatal pore recessed beneath turbulent wind currents.
                  </li>
                  <li>
                    <strong>Inrolled Leaves (e.g. Marram Grass):</strong> Traps saturated vapor within an enclosed cylinder.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        )}

        {/* ================================================================== */}
        {/* TAB 4: KCSE EXAM READINESS QUIZ                                    */}
        {/* ================================================================== */}
        {activeTab === 'quiz' && (
          <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 shadow-xl max-w-3xl mx-auto space-y-6">
            <div className="flex items-center justify-between border-b border-slate-800 pb-4">
              <div>
                <h2 className="text-xl font-bold text-white flex items-center gap-2">
                  <Award className="w-5 h-5 text-teal-400" />
                  KCSE Biology Exam Check: Transpiration & Potometer
                </h2>
                <p className="text-xs text-slate-400 mt-1">
                  Test your mastery of boundary layer diffusion, potometer methodology, and stomatal physiology.
                </p>
              </div>

              {quizScore !== null && (
                <div className="text-right">
                  <div className="text-2xl font-black text-teal-400">
                    {quizScore} / {KCSE_QUESTIONS.length}
                  </div>
                  <div className="text-[11px] text-slate-400">Score Achieved</div>
                </div>
              )}
            </div>

            {quizScore === null ? (
              <div className="space-y-5">
                {/* Question Header */}
                <div className="flex items-center justify-between text-xs text-slate-400">
                  <span className="font-semibold text-teal-400">
                    Question {currentQuestionIdx + 1} of {KCSE_QUESTIONS.length}
                  </span>
                  <span>Select the single best answer</span>
                </div>

                <div className="text-base font-bold text-white">
                  {KCSE_QUESTIONS[currentQuestionIdx].prompt}
                </div>

                {/* Multiple Choice Options */}
                <div className="space-y-3">
                  {KCSE_QUESTIONS[currentQuestionIdx].options.map((opt) => {
                    const isSelected = userAnswers[KCSE_QUESTIONS[currentQuestionIdx].id] === opt.id;
                    return (
                      <button
                        key={opt.id}
                        onClick={() => handleSelectAnswer(opt.id)}
                        className={`w-full text-left p-4 rounded-2xl border transition-all text-xs sm:text-sm flex items-start gap-3 ${
                          isSelected
                            ? 'bg-teal-500/20 border-teal-500/60 text-white shadow-md'
                            : 'bg-slate-950/60 border-slate-800 text-slate-300 hover:bg-slate-800/60 hover:text-white'
                        }`}
                      >
                        <span
                          className={`w-6 h-6 rounded-full flex items-center justify-center font-bold text-xs shrink-0 ${
                            isSelected
                              ? 'bg-teal-500 text-slate-950'
                              : 'bg-slate-800 text-slate-400'
                          }`}
                        >
                          {opt.id}
                        </span>
                        <span className="leading-relaxed mt-0.5">{opt.text}</span>
                      </button>
                    );
                  })}
                </div>

                {/* Feedback / Explanation Box */}
                {showExplanation && (
                  <div className="p-4 rounded-2xl bg-slate-950 border border-teal-500/30 text-xs sm:text-sm space-y-2 animate-fadeIn">
                    <div className="font-bold text-teal-400 flex items-center gap-1.5">
                      <Info className="w-4 h-4" />
                      Detailed Biological Rationale:
                    </div>
                    <p className="text-slate-300 leading-relaxed">
                      {KCSE_QUESTIONS[currentQuestionIdx].explanation}
                    </p>
                  </div>
                )}

                {/* Quiz Navigation Buttons */}
                <div className="flex items-center justify-between pt-4 border-t border-slate-800">
                  <button
                    onClick={() => setShowExplanation(!showExplanation)}
                    className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300"
                  >
                    {showExplanation ? 'Hide Explanation' : 'Show Explanation'}
                  </button>

                  <button
                    onClick={handleNextQuestion}
                    disabled={!userAnswers[KCSE_QUESTIONS[currentQuestionIdx].id]}
                    className="px-5 py-2 rounded-xl text-xs font-bold bg-teal-600 hover:bg-teal-500 text-white shadow disabled:opacity-40 flex items-center gap-1.5"
                  >
                    {currentQuestionIdx < KCSE_QUESTIONS.length - 1 ? 'Next Question' : 'Finish Quiz'}
                    <ChevronRight className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ) : (
              /* Quiz Results Card */
              <div className="text-center py-8 space-y-4">
                <div className="w-16 h-16 rounded-full bg-teal-500/20 text-teal-400 border border-teal-500/40 flex items-center justify-center mx-auto">
                  <Award className="w-8 h-8" />
                </div>
                <h3 className="text-2xl font-black text-white">
                  Quiz Completed: {quizScore} / {KCSE_QUESTIONS.length}
                </h3>
                <p className="text-sm text-slate-300 max-w-md mx-auto">
                  {quizScore >= 3
                    ? 'Outstanding! You have mastered the relationship between wind velocity, diffusive boundary layers, and whole-plant transpiration!'
                    : 'Good attempt! Review the biology principles tab to understand how air movement sweeps away the boundary layer to steepen the diffusion gradient.'}
                </p>

                <div className="flex items-center justify-center gap-3 pt-4">
                  <button
                    onClick={handleResetQuiz}
                    className="px-4 py-2 rounded-xl text-xs font-bold bg-teal-600 hover:bg-teal-500 text-white shadow"
                  >
                    Retake Quiz
                  </button>
                  <button
                    onClick={() => setActiveTab('experiment')}
                    className="px-4 py-2 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-slate-300"
                  >
                    Back to Lab Bench
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
